### ISSUE TITLE
How often does Open-digger compute and update?

### ISSUE THREAD

**Issue by Peng99999** [X-lab2017/open-digger#1002]
Hi, we want to analyze some new metrics, such as the number of downloads of a release. This metric is time-sensitive, so we want to know how often Open-digger calculates and updates? Thanks.

**Comment by xgdyp** [comment]
Hello, I think you want to do some work such as calculating some metrics using sample data. Our sample data comes from gharchive.org. They collect all GitHub logs. 
If using sample data, your data is fixed within a period and not real-time updated.
But in our central database, we will synchronize log data with a several-day delayed time(no more than 2 days I think)

**Comment by Peng99999** [comment]
Thank you! If the log data is synchronized every two days, I think our work is feasible, because the number of downloads delayed for two days does not change much.

**Comment by frank-zsy** [comment]
Actually the delay is only several hours, but the number of release downloads is not part of the events log, the count can be retrieved only by API with authorized token I think.

**Comment by Peng99999** [comment]
In "open-digger/docs/assets/data_description.csv", line 123, does the field "release_assets.download_count" means the number of downloads for this release?

**Comment by frank-zsy** [comment]
> In "open-digger/docs/assets/data_description.csv", line 123, does the field "release_assets.download_count" means the number of downloads for this release?

Yes, but actually the events log only record on release create, that means the `release_assets.download_count` is always 0 in the log.

**Comment by Peng99999** [comment]
Thank you for your answers! Thanks!
