### ISSUE TITLE
Calculation method of project activity

### ISSUE THREAD

**Issue by 100liusir** [X-lab2017/open-digger#1006]
Regarding the open source community activity calculation method, should we consider the weight of the metric in the calculation formula? Can we change the length of time needed to complete the metric into the weight, and then add it to the activity calculation formula? If we define open source community activity as the total amount of time investment that an open source community attracts from around the world, divided by unit time. Let's say it takes a user 1 second to click on a star. fork a warehouse, about 2 to 3 seconds. It takes about 5 minutes to submit an issue. The time to resolve an issue can take hours, along with other metrics such as PR. From this point of view, the weight of star is at the level of seconds, while the weight of issue, PR should be at the level of minutes or even hours. Is this a reasonable calculation that we can consider?

**Comment by xgdyp** [comment]
Thanks for your feedback. I think you're right. It's obvious that different types of events may take different time. Do you mean give each event type a time weight? For every event type, does the weight a fixed number or changed based on event time information?

**Comment by xgdyp** [comment]
I probably understand what you mean. In the first idea, do you mean change the params 
(![image](https://user-images.githubusercontent.com/37795442/197109715-95044a3e-0769-47bb-baab-29aed70c6443.png))
but sometimes it would be tough. Three are three examples:
1. An issue may be open for a long time but no one want to solve it. It's common in some mature projects. How to meature this.
2. The time from the open of a PR to the closed may be very short, this does not equal the actual development time of this PR. So I think it's hard to reprensent the workload using time
3. In our model， PRreview event has the hightest weight. But how to calculate it's time. I think this may have some problems, too.

In the second, I'm not sure what is `commit factor`. In my understanding, this includes the message of commit level such as `commit nums in a pr`and `commit diff lines`.Is it right? I'm interested in commit level data, too.

**Comment by 100liusir** [comment]
Thank you for your reply. 1. My idea is that the average time for the issue to be solved in the project can be used. 2. As for the time of PR, the time of submitting PR and the time of approval of PR can be calculated, and the average time difference of PR can be calculated. 3. You can add the COMMIT parameter, which is the number of commits added to the project, to the formula for calculating activity. Measurements of these data can be made using mature projects to determine the final time parameters.

**Comment by xgdyp** [comment]
OK, I think different people have different perceptions on how to meature opensource and that's definitely great for our community. In my opinion, `active score` reflects how a person participate in a project and it's different from `community reaction`. But I also think your ideas are valuable, too. Whatever, I think you can have a try on your idea(such as write down a new formula or prepare an example or other things). We can discuss it on next Wednesday's weekly huddle. Thanks for your contribution again!

**Comment by frank-zsy** [comment]
@100liusir Thanks for the valuable discussion. Here is my opinion.

1. You are trying to use time cost as the factor of each events, this is definitely a good economics point and very similar to the suggestion in [here](https://zhuangbiaowei.github.io/opensource/economics/2022/02/05/economic-model-of-open-source-ecology.html). But the average time cost of an issue or a PR is really hard to calculate, time span from open to close/merge is not quite accurate even we are not considering the time should be `social average labor time` in economics. The `social average labor time` is not just a statistical time span, it is also related to technical skills of each developer on each project. I admit the factor right now is not quite scientific and you can try to calculate the time span of each events, I am also very curious about how the results may look like.
2. Commits are quite tricky on GitHub. The reasons we did not include commits in the activity formula in the first place are:
- For mature communities, commits should not be pushed into the repository directly by anyone, then all the contributions will be from a certain PR, so commits are included in PR related events like `Merge PR`.
- For different communities, commits go into the repository in different methods. You may already find out that there are three merge types on GitHub: `Direct merge`, `Squash merge` and `Rebase merge`. The `direct merge` will add all the commits into the repository while `squash merge` will squash all the commits in a PR into one single commit and push it into the repository. So commit count is quite different from community to community since they may use different merge method for PRs.
These are the two reasons why we don't use commit count in the event types.

Hope the information will help you.

**Comment by 100liusir** [comment]
@frank-zsy @xgdyp Thank you for your reply. 
The response to question 1 is as follows:
It is really difficult to calculate the average time. From the point of view of economics, if we consider the social necessary labor time, it is the labor time needed to produce a certain use value under the existing social normal production conditions and the social average labor proficiency. Socially necessary labor time is a theoretical time, as I understand it, for the open source community, the average or necessary time for a project contributor to complete each event. My idea can refer to this economic idea, if we consider the necessary labor time needed to complete the project, in the case of normal network, such as forking a warehouse, it will take about 2-3 seconds. A star takes only a few milliseconds. The developer submits an issue, and depending on the text of the issue, a vocabulary takes about 2 seconds, and then the time can be calculated based on the amount of text in the issue. A simple issue can take 10-30 minutes from start to close. Corresponding to PR, my idea is whether we can calculate the time of PR in a similar way. Figure out roughly how much time it took based on the amount of code for the PR. For example, we can consider how much time it takes to write a Class, and then figure out the average PR time. Since each developer has different technical abilities, it is really difficult to calculate the average time of PR. Therefore, I consider whether it is possible to calculate the time required for a PR by calculating the amount of code in PR and the amount of code in the code. In this way, the amount of time for different events is calculated. star is weighted at the millisecond level, fork is weighted at the second level, issue is weighted at the minute level, and PR is weighted at the hour level. However, how to measure the time of different events may need to be analyzed by mining data from some mature open source projects, and finally determine how to assign the value of time weight. Is it feasible to give time weight to each event by considering time?

**Comment by 100liusir** [comment]
@frank-zsy Thank you for your reply.
The responses to question 2 is as follows:
For different communities, there are different ways to commit. Whether we can use the most communities to represent the commit, or give different weight to different types of commit, I feel that this is really difficult to achieve. However, I feel that the commit event can also reflect project activity to a certain extent, and we may not be able to find a proper way to calculate it right now. Maybe there will be a way to do that in the future.
The commit event type is not added. The first reason I considered the commit event was that I noticed that there were some mirrored projects on github that seemed to have issue or PR turned off, in which case the activity of the project might not be efficiently calculated using this calculation model.

**Comment by frank-zsy** [comment]
@100liusir For question 1:

Yes, I think you can use time span to recalculate the factors. But there is a tiny trick about use line of code(LOC) to estimate the time developers used. Another reference is [equivalent line of code(ELOC)](https://www.merico.cn/blog/equivalent-line-of-code2) which uses code AST edit distance to value a code change, but it also requires code content analysis.

**Comment by frank-zsy** [comment]
@100liusir For question 2:

Yes, it is not fair to ignore the repositories which do not use issue and pull request functions on GitHub.

But use commit information in event log is also tricky here, the type should be `PushEvent` and Git and GitHub are different systems so you may find that you can not find out how many commits are from a specific developer.

Take [postgres](https://github.com/postgres/postgres) as an example, all the commits in the repository on GitHub are from a robot account [postgres-mirror](https://github.com/postgres-mirror), so you can not separate commits to different accounts.
