### ISSUE TITLE
Request to add a topic 'hacktoberfest' on this repo

### ISSUE THREAD

**Issue by LinuxSuRen** [X-lab2017/open-digger#1007]
See also

![image](https://user-images.githubusercontent.com/1450685/196448744-7d720cea-f048-442a-86a7-982a8210bc55.png)

![image](https://user-images.githubusercontent.com/1450685/196448852-d66f1e2a-6ea1-4e3a-90be-4f68e2f11d7c.png)

**Comment by frank-zsy** [comment]
It is great that OpenDigger to participant in Hacktoberfest this year, I will add the topic now.

**Comment by LinuxSuRen** [comment]
hi @frank-zsy thanks for the help.

![image](https://user-images.githubusercontent.com/1450685/196582325-109d1eb4-8fa9-4d41-b706-63fe122fc067.png)
