### ISSUE TITLE
[Discussions] How to separate python kernel and nodejs kernel

### ISSUE THREAD

**Issue by xgdyp** [X-lab2017/open-digger#1008]
Hi All, as @frank-zsy said in #968, we need to separate two kernel so developers can focus on one. But now I don't have ideas on how to organize code. One possible method is to create folders like `src/node/` and src/python/`. Is there any other possible methods？

**Comment by xgdyp** [comment]
Thanks @bifenglin's advice. How about this?
![image](https://user-images.githubusercontent.com/37795442/197118694-5b300a18-722d-42cf-924b-b6b346344f5e.png)

**Comment by xgdyp** [comment]
> Thanks @bifenglin's advice. How about this? ![image](https://user-images.githubusercontent.com/37795442/197118694-5b300a18-722d-42cf-924b-b6b346344f5e.png)

Hi @frank-zsy, do you think it's OK?

**Comment by xgdyp** [comment]
OK, I'll work on this.

**Comment by frank-zsy** [comment]
@xgdyp What's the progress here?

**Comment by xgdyp** [comment]
Hi @frank-zsy , I'm still working on it. I'd finish this before Wednesday's biweekly meeting.

**Comment by frank-zsy** [comment]
Closed by #1035
