### ISSUE TITLE
【FEATURE】Does opendigger collect the package data from libraries.io?

### ISSUE THREAD

**Issue by bifenglin** [X-lab2017/open-digger#1014]
I have noticed that **Libraries.io Open Data** is quite high-quality data, which can support our 3 network data, although the archive data is only before 2020.
They track over 2.7m unique open source packages, 33m repositories and 235m interdependencies between them. 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/15813364/197730098-9f5c7fdf-aa2f-41e2-be6f-680e0752582d.png">

**Comment by xgdyp** [comment]
I think we've stored them in MongoDB.

**Comment by xgdyp** [comment]
Hi @bifenglin ,do you have other questions on this ?
