### ISSUE TITLE
We need to update a  python kernel container to our dockerhub

### ISSUE THREAD

**Issue by xgdyp** [X-lab2017/open-digger#1015]

**Comment by frank-zsy** [comment]
Done. The docker image URL is: docker-hub.x-lab.info/opendigger/open-digger-jupyter-python:1.0 , we can add the doc to Python related resources after #1008 finished.

**Comment by xgdyp** [comment]
So quick！Thanks！

**Comment by frank-zsy** [comment]
Can I close this now, or you need to add the docs then close this?
