### ISSUE TITLE
How roughly is contribution calculated

### ISSUE THREAD

**Issue by Lucyaaaaaaaa** [X-lab2017/open-digger#1016]
The developer contribution to the warehouse can be seen in the active warehouse network diagram. How is the developer contribution to the project roughly calculated?

**Comment by frank-zsy** [comment]
What do you mean by project? A group of repository or any other definition?

**Comment by tmyisgod** [comment]
> What do you mean by project? A group of repository or any other definition?

How are the nodes in the Most Participated Repos calculated.
