### ISSUE TITLE
[label] submit Chinese developr labeled data

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/open-digger#1017]
I want to add some Chinese developer labeled data into OpenDigger to help us for our community analysis.

Label: China

Type: Region

Users:

- zhicheng-ning
- xgdyp

**Comment by xgdyp** [comment]
Thanks for your feedback, I'll add it.

**Comment by frank-zsy** [comment]
@zhicheng-ning Since `:communities/xlab` label is under `China` label, so all the developers in `xlab` will be automatically added into `China` label. So you two are already under `China` now.

**Comment by zhicheng-ning** [comment]
Wow, really embarrassed.Thanks for your reminding.
