### ISSUE TITLE
[CI/CD] Optimize the ci/cd process

### ISSUE THREAD

**Issue by xgdyp** [X-lab2017/open-digger#1020]
In #1007, we find that we should filter opendigger-bot's comment to make our label correct
![image](https://user-images.githubusercontent.com/37795442/198933834-fac15c5d-21a5-4e63-b8fe-89a29ed23f68.png)

This can be fixed by editing  `github/workflows/reply-label-issue-comment.yml` , adding a conditional clause to filter bot's comment.

![image](https://user-images.githubusercontent.com/37795442/198934836-4e1fd919-eb87-4226-9ade-c1b08944ad23.png)

**Comment by xgdyp** [comment]
and open-digger-bot's actor_id is 69946302
<img width="996" alt="image" src="https://user-images.githubusercontent.com/37795442/198937563-64e13239-06f9-45c7-be1b-446071d5a5fd.png">

**Comment by lhbvvvvv** [comment]
I can do it！

**Comment by lhbvvvvv** [comment]
How can I test the correctness of the change?

**Comment by xgdyp** [comment]
you can try in your own repo to check if `id` field equals to `actor_id` field in our database. If it's true, commit and I'll merge to test it.
