### ISSUE TITLE
[proposal] count frequently analyzed column name

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/open-digger#1023]
can we show some important column name like `repo_id`,`org_id`,`type`,`created_at`, since not all columns are frequently analyzed.

**Comment by lhbvvvvv** [comment]
I think that we can use the [description of the data label](https://github.com/X-lab2017/open-digger/blob/master/docs/assets/data_description.csv) to get all the labels. And then we can use the crawler to acess **https:<span></span>//github.com/X-lab2017/open-digger/search?q=_label_name_** (_label_name_ like 'repo_id', 'org_id'). We can go through all the labels. For each tag, we can access the url by the crawler to get the number of times it appears in the repo.
Thus the frequency can be showed by the number of times that the label is used in the repo.

Here is an example of one of these tags.
![1667303554017](https://user-images.githubusercontent.com/104072573/199226776-9a1200d1-4f20-45e1-bd7f-727c20c5525c.png)

**Comment by xgdyp** [comment]
OK, I think that's great! But can you show me how many results a never-used field(such as comment) returned?

**Comment by xgdyp** [comment]
I think you are right!

**Comment by zhicheng-ning** [comment]
> I think that we can use the [description of the data label](https://github.com/X-lab2017/open-digger/blob/master/docs/assets/data_description.csv) to get all the labels. And then we can use the crawler to acess **https://github.com/X-lab2017/open-digger/search?q=_label_name_** (_label_name_ like 'repo_id', 'org_id'). We can go through all the labels. For each label_name, we can access the url by the crawler to get the number of times it appears in the repo. In a block of code, the label is counted only once. Thus the frequency can be showed by the number of times that the label is used in the repo.

good idea！

**Comment by xgdyp** [comment]
Hi @lhbvvvvv , would you like pick this issue?

**Comment by lhbvvvvv** [comment]
> Hi @lhbvvvvv , would you like pick this issue?

Ok, I would like to pick it.

**Comment by lhbvvvvv** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/lenovo/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/lenovo/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">



name | type | description | frequency
-- | -- | -- | --
type | Enum | event instance type,event instances of different event type have   different payload from GitHub API | 184
id | UInt64 | uique identity of this event instance | 32
repo_id | UInt64 | the unique identity of a repository where this event was tragered | 13
created_at | DateTime | when this event instance was generated on GitHub | 13
actor_id | UInt64 | GitHub user id of someone who trigger this envent instance | 12
repo_name | LowCardinality(String) | repository name | 12
actor_login | LowCardinality(String) | GitHub user login of someone who trigger this envent instance | 9
org_id | UInt64 | organization unique identity of this repository | 9
body | String | body of Issues/IssueComment/CommitComment/PullRequestReviewComment event | 9
org_login | LowCardinality(String) | login name of this organization | 7
issue_author_id | UInt64 | GitHub user id of this issue's author | 5
issue_author_login | LowCardinality(String) | GitHub user login of this issue's author | 5
pull_merged | UInt8 | whether this pull request is merged | 5
issue_number | UInt32 | the id of this issue in this repository | 4
action | Enum | action in the payload of event instance | 3
issue_id | UInt64 | unique identity of this issue on GitHub | 3
issue_comments | UInt16 | the number of issue comments | 2
pull_additions | UInt16 | additions in this pull request | 2
pull_deletions | UInt16 | deletions in this pull request | 2



</body>

</html>

Here is the result based on the above method. Words not in the table appear only once in our repo(just in [data_description.csv](https://github.com/X-lab2017/open-digger/blob/master/docs/assets/data_description.csv)). Some common words like `id` ,`type`,`body` may be used as substrings or in some cases do not represent labels, so there are some deviations in the result. However, this doesn't happen often for most words and the result has certain reference value.

**Comment by xgdyp** [comment]
so awesome!

**Comment by lhbvvvvv** [comment]
> So awesome! How to define `frequently`?

 I think that it means the number of times that the label is used in the repo.

**Comment by xgdyp** [comment]
I see, but how can a field be called frequent? What is the threshold?

**Comment by lhbvvvvv** [comment]
The setting of the threshold may depend more on one's own view. I think the threshold could be 7. And `body` in most cases does not represent labels. So words with frequency more than or equal to 7 except for `body` can be called frequent.

**Comment by xgdyp** [comment]
OK, thanks for your work!

**Comment by xgdyp** [comment]
I close this first. If @zhicheng-ning  you have any problems, please reopen it.
