### ISSUE TITLE
[bug] questions in Mertic:issue duration resolution

### ISSUE THREAD

**Issue by longyanz** [X-lab2017/open-digger#1026]
Hi @frank-zsy ,when I read `duration resolution ` metric in `handbook.ipynb`, I found this metric return a value about 4700 days. I think this maybe wrong
![image](https://user-images.githubusercontent.com/91717658/199877686-367c0d89-93ba-4bfd-9203-c588b8cdab22.png)

So I find some issues in our clickhouse and there `issue open` event missed. I think this caused the wrong result.
![image](https://user-images.githubusercontent.com/91717658/199878860-8e21af5d-93c6-4d9e-8992-e4dfc84c2faa.png)
(https://github.com/microsoft/vscode/issues/122346)
and in this clause, `open_at` field return 1970-1-1 .
![image](https://user-images.githubusercontent.com/91717658/199879217-fa9513b1-9b2e-4199-9c23-ad5fef5b07f9.png)

**Comment by frank-zsy** [comment]
It's because the `opened` action was lost in the event log, so `opened_at` return as a null value which is 1970-1-1 when the type is DateTime. We should consider this since there may some lost data in the event log.

When the `opened_at` can not be found, we may use the first comment event instead, does this make sense to you?

**Comment by longyanz** [comment]
Thanks！

**Comment by frank-zsy** [comment]
It is really tricky if some events lost in the log, I will give a detail look into the problem later.

/self-assign

**Comment by xgdyp** [comment]
Hi @frank-zsy , why we don't use `issue_created_at` and `issue_closed_at` field to avoid this problem?

**Comment by frank-zsy** [comment]
> Hi @frank-zsy , why we don't use `issue_created_at` and `issue_closed_at` field to avoid this problem?

Yes! Great point, I think I just forgot the uncommonly used columns which is quite useful in this situation.

**Comment by longyanz** [comment]
Hi, we use `argMax(issue_created_at,created_at) AS opened_at` instead of `maxIf(created_at, action = 'opened') AS closed_at`
![5fbdb9613a7adfb4d093e71329141ac](https://user-images.githubusercontent.com/91717658/200459351-dc046230-990f-496b-906d-92148eef3df1.png)

It seems the result is correct.

![52a95ac1010dfaac72e02f9297115a3](https://user-images.githubusercontent.com/91717658/200459550-3496f99c-5d20-426c-b78e-2ac074a1aaa0.png)

**Comment by frank-zsy** [comment]
@longyanz Great, can you fix this?

**Comment by longyanz** [comment]
I will fix it after @xgdyp finish separating python kernel and nodejs kernel #1008 ~
