### ISSUE TITLE
jianmu-ci-server name need to update

### ISSUE THREAD

**Issue by zhangjinnan** [X-lab2017/open-digger#1027]
Jianmu project is update name from jianmu-ci-server to jianmu. Mulan Community lebel date need to update.

url: https://github.com/X-lab2017/open-digger/blob/master/labeled_data/communities/mulan/index.yml

Label: jianmu

Type: Community

Repos:
- jianmu-dev/jianmu

-

Orgs/Users:

-

**Comment by frank-zsy** [comment]
From the id of the repo, I think you only change the name of the repo but still the same repo right?
