### ISSUE TITLE
I got 404 not found in data doc page.

### ISSUE THREAD

**Issue by gymgym1212** [X-lab2017/open-digger#103]
[description]
I want to know the data description and I got the 404 error after clicking the "data" link. In addition, the same problem occured if i switch  to "data description" in "Contributing Guide" page.
[Snapshot]
![image](https://user-images.githubusercontent.com/37684061/93728151-326e4900-fbf1-11ea-9d16-11c3d9a682aa.png)

**Comment by sunshinemingo** [comment]
Maybe you can refer to **DATA.md** whose path is _github-analysis-report/docs/DATA.md_ to know something about the data.

**Comment by gymgym1212** [comment]
@sunshinemingo It doesn't seem to work. Visiting the path _https://www.x-lab.info/github-analysis-report/docs/DATA.md_, I got _404 file not found_ error.

**Comment by sunshinemingo** [comment]
I think you misunderstand what I mean, the file path is the path in the repo.
![image](https://user-images.githubusercontent.com/37278844/93730017-68afc680-fbf9-11ea-95e2-9a8e2def32d5.png)

**Comment by gymgym1212** [comment]
@sunshinemingo  Oh, thanks! I got it.

**Comment by frank-zsy** [comment]
This is a document bug we should fix.
