### ISSUE TITLE
[Doc] We should add a user section in README

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger#1030]
Right now, there are lots of users in OpenDigger. Like OpenLeaderboard, Hypercrx, [Mulan dashboard](http://113.31.109.198/link/3qNZ0sCL) and [Apache project insight](https://willemjiang.github.io/Insight/#/).

I think we should add a static data section and a user section in README and invite more developers to use OpenDigger data to implement their own open source applications.

**Comment by zhicheng-ning** [comment]
Actually Mylan dashboard has been updated like [this](http://113.31.109.198/link/1VxPsUCX).

**Comment by xgdyp** [comment]
OK I'll do this

**Comment by frank-zsy** [comment]
@xgdyp You can add a user section and actually I would like to modify the output of OpenDigger. To put all the metrics of a user, repo, label data item, organization into a single place so developers can know about what data they can use.

**Comment by xgdyp** [comment]
Can I close this issue now?

**Comment by frank-zsy** [comment]
We still need a user section about who already used us.

**Comment by xgdyp** [comment]
User section means which downstream applications use OpenDigger, is this right?
I don't quite understand since we have the development part in README.
<img width="973" alt="image" src="https://user-images.githubusercontent.com/37795442/203723761-6f85d718-9b95-4bfb-893b-16f27cea48a6.png">

**Comment by frank-zsy** [comment]
Actually we need to refactor the documentation here, since formerly we do have a cron task to generate data for Hypercrx, now we do not have a specific task for Hypercrx but just an `monthly_export` task for all the applications like Hypercrx, Mulan dashboard, Apache insight project and etc.

The development section should move to users section and add more applications or reports.

**Comment by xgdyp** [comment]
I see
