### ISSUE TITLE
[Feature] Add more label data for certain technical area.

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger#1047]
Right now, the label data is only about company and area, but we need to add more label data for certain technical area.

The most important areas may include:

- [x] Cloud native #1054 
- [x] Big data #1052 
- [x] AI #1196 
- [x] Database #1056 
- [x] Operating System #1058 
- [x] Frontend #1198 
- [x] Block chain #1210 
- [x] IoT #1213

**Comment by xgdyp** [comment]
Hi @frank-zsy , how to distinguish several types of labels? Should OS repos be `Tech-0/Tech-1/reponame` or `Tech-0 reponame`? And I think we can write a README file in labeled_data folder to introduce ladeled_data.(I think we need to add some short descriptions in README.md, too)

**Comment by frank-zsy** [comment]
It is depend on what data we have, big data has 2 levels since the report has 2 levels, cloud native has 3 levels since CNCF landscape has 3 levels. Operating system has only 1 level because the data is from `operating system` topic search API on GitHub, so I don't really have enough information to separate more levels for this one.

If you can find more information or project lists of operating system, we can add more levels to it.

**Comment by xgdyp** [comment]
get it.

**Comment by frank-zsy** [comment]
As the programmer magazine from CSDN published in 2022.12, there is a landscape in the book about softwares, so I can add `AI` and `frontend` area label data according to it. Also we can add `block chain` and `IoT` at same time.

**Comment by xiaoya-yaya** [comment]
Suggesting two technical areas: `DevOps` and `RISC-V`, according to the Linux Foundation training resources

**Comment by frank-zsy** [comment]
> Suggesting two technical areas: `DevOps` and `RISC-V`, according to the Linux Foundation training resources

Great, could you give a link about the resource?

**Comment by xiaoya-yaya** [comment]
[LF Training Resources](https://training.linuxfoundation.org/resources/?_sft_content_type=free-course)
I referred to the navigation bar on the left of the page, Although there is no risc-v catalog but according to the courses I personally think this is an independent technical area.
<img width="311" alt="image" src="https://user-images.githubusercontent.com/56542972/218669653-450f7f85-0ff2-4f88-abe3-687a5064fca0.png">

**Comment by frank-zsy** [comment]
Yes, RISC-V could be an independent technical area but how can extract open source repos from the courses? I can not see lots of open source project information in the course.

**Comment by xiaoya-yaya** [comment]
Oh I was only suggesting two technical areas inspired by the topics of LF courses, while they don't provide detailed project lists.

**Comment by frank-zsy** [comment]
All the related label data has been merged, more fields label data added in the future should attached with new issue.
