### ISSUE TITLE
[Data] Add label data for Database technical area.

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger#1055]
I want to add some labeled data into OpenDigger to help us for our community analysis.

The data is based on [DB-Engines](https://db-engines.com/en/ranking).

Label: Relational

Type: Tech-1

Repos:

- mysql/mysql-server
- postgres/postgres
- sqlite/sqlite
- MariaDB/server
- apache/hive
- FirebirdSQL/firebird
- greenplum-db/gpdb
- prestodb/presto
- ClickHouse/ClickHouse
- h2database/h2database
- cockroachdb/cockroach
- ryenus/hsqldb
- apache/derby
- oracle/nosql-go-sdk
- apache/phoenix
- apache/drill
- pingcap/tidb
- percona/percona-server
- MonetDB/MonetDB
- trinodb/trino
- VoltDB/voltdb
- citusdata/citus
- heavyai/heavydb
- apple/foundationdb
- apache/kylin
- CUBRID/cubrid
- apache/ignite
- tarantool/tarantool
- KxSystems/kdb
- timescale/timescaledb
- apache/druid
- griddb/griddb
- questdb/questdb
- taosdata/TDengine
- openlink/virtuoso-opensource
- vaticle/typedb
- postgis/postgis
- illarionov/SpatiaLite
- orbisgis/h2gis

Label: Document

Type: Tech-1

Repos:

- mysql/mysql-server
- postgres/postgres
- MariaDB/server
- greenplum-db/gpdb
- oracle/nosql-go-sdk
- apache/drill
- pingcap/tidb
- MonetDB/MonetDB
- trinodb/trino
- citusdata/citus
- apple/foundationdb
- redis/redis
- hazelcast/hazelcast
- aerospike/aerospike-server
- tarantool/tarantool
- Alachisoft/NCache
- mongodb/mongo
- couchbase/couchbase-lite-ios
- apache/couchdb
- marklogic/marklogic-data-hub
- realm/realm-cocoa
- googleapis/python-firestore
- arangodb/arangodb
- ravendb/ravendb
- rethinkdb/rethinkdb
- pouchdb/pouchdb
- beardedeagle/mnesiac
- mbdavid/LiteDB
- openlink/virtuoso-opensource
- orientechnologies/orientdb
- elastic/elasticsearch

Label: Spatial

Type: Tech-1

Repos:

- mysql/mysql-server
- postgres/postgres
- MariaDB/server
- greenplum-db/gpdb
- h2database/h2database
- MonetDB/MonetDB
- trinodb/trino
- heavyai/heavydb
- redis/redis
- aerospike/aerospike-server
- tarantool/tarantool
- mongodb/mongo
- couchbase/couchbase-lite-ios
- apache/couchdb
- ravendb/ravendb
- rethinkdb/rethinkdb
- influxdata/influxdb
- openlink/virtuoso-opensource
- elastic/elasticsearch
- apache/solr
- postgis/postgis
- illarionov/SpatiaLite
- geomesa/geomesa-geoserver
- orbisgis/h2gis

Label: Graph

Type: Tech-1

Repos:

- MariaDB/server
- redis/redis
- arangodb/arangodb
- ravendb/ravendb
- neo4j/neo4j
- openlink/virtuoso-opensource
- orientechnologies/orientdb
- JanusGraph/janusgraph
- dgraph-io/dgraph
- apache/giraph
- vesoft-inc/nebula
- vaticle/typedb
- microsoft/GraphEngine
- blazegraph/database

Label: Time Series

Type: Tech-1

Repos:

- ClickHouse/ClickHouse
- trinodb/trino
- redis/redis
- mongodb/mongo
- ravendb/ravendb
- influxdata/influxdb
- KxSystems/kdb
- prometheus/prometheus
- graphite-project/graphite-web
- timescale/timescaledb
- apache/druid
- oetiker/rrdtool-1.x
- OpenTSDB/opentsdb
- griddb/griddb
- kairosdb/kairosdb
- questdb/questdb
- VictoriaMetrics/VictoriaMetrics
- taosdata/TDengine
- basho-labs/Riak-TS-JDBC-Driver
- m3db/m3
- apache/iotdb
- rackerlabs/blueflood
- objectbox/objectbox-java

Label: Key-value

Type: Tech-1

Repos:

- oracle/nosql-go-sdk
- trinodb/trino
- apple/foundationdb
- redis/redis
- memcached/memcached
- etcd-io/etcd
- hazelcast/hazelcast
- ehcache/ehcache3
- basho/riak_kv
- aerospike/aerospike-server
- apache/ignite
- facebook/rocksdb
- google/leveldb
- infinispan/infinispan
- LMDB/lmdb
- apache/geode
- tarantool/tarantool
- zopefoundation/ZODB
- Alachisoft/NCache
- couchbase/couchbase-lite-ios
- arangodb/arangodb
- griddb/griddb
- orientechnologies/orientdb
- microsoft/GraphEngine
- scylladb/scylla
- berkeleydb/libdb

Label: Search engine

Type: Tech-1

Repos:

- trinodb/trino
- redis/redis
- Alachisoft/NCache
- mongodb/mongo
- marklogic/marklogic-data-hub
- arangodb/arangodb
- openlink/virtuoso-opensource
- elastic/elasticsearch
- apache/solr
- sphinxsearch/sphinx
- strapdata/elassandra

Label: Wide column

Type: Tech-1

Repos:

- trinodb/trino
- apache/cassandra
- apache/hbase
- apache/accumulo
- scylladb/scylla
- strapdata/elassandra

Label: Native XML

Type: Tech-1

Repos:

- marklogic/marklogic-data-hub
- openlink/virtuoso-opensource
- berkeleydb/libdb
- BaseXdb/basex
- sedna/sedna
- eXist-db/exist

Label: RDF

Type: Tech-1

Repos:

- marklogic/marklogic-data-hub
- openlink/virtuoso-opensource
- apache/jena
- blazegraph/database
- eclipse/rdf4j
- 4store/4store

Label: Object oriented

Type: Tech-1

Repos:

- iboxdb/db4o-gpl
- objectbox/objectbox-java
- The-Alchemist/perst

Label: Multivalue

Type: Tech-1

Repos:

- cran/scidb
- dioptre/rasdaman
- gregjurman/openqm
- milvus-io/milvus

Label: Event

Type: Tech-1

Repos:

- EventStore/EventStore
- NEventStore/NEventStore

Label: Content

Type: Tech-1

Repos:

- apache/jackrabbit
- ModeShape/modeshape

**Comment by birdflyi** [comment]
Auto crawling tools for ranking data : [birdflyi](https://github.com/birdflyi)/[db_engines_ranking_table_crawling](https://github.com/birdflyi/db_engines_ranking_table_crawling).
Data after manu-labeled will keep updating at [DB_EngRank_tophalf_githubprj_summary-202211](https://www.yuque.com/zhlou/ln7m80/spruaup5gx8qldsm?#eofx).

**Comment by birdflyi** [comment]
I want to add a **extented** labled dataset of this one, I wonder whether it is appropriate to **open another new issue** on labeling Database technical data or just to add it **here**?

**Comment by xgdyp** [comment]
> Auto crawling tools for ranking data : [birdflyi](https://github.com/birdflyi)/[db_engines_ranking_table_crawling](https://github.com/birdflyi/db_engines_ranking_table_crawling). Data after manu-labeled will keep updating at [DB_EngRank_tophalf_githubprj_summary-202211](https://www.yuque.com/zhlou/ln7m80/spruaup5gx8qldsm?#eofx).


Is there more supplementary data by this way. Can you give some examples of labeled data that we don't have yet?
