### ISSUE TITLE
[Refactor] Optimize the `LIMIT` option in metrics interface.

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger#1064]
We need to discuss the `LIMIT` option implementation in metrics.

Like we discussed in [here](https://github.com/X-lab2017/open-digger/pull/1038#discussion_r1026084184), for `LIMIT` option in metrics query, we have two different implementation logics.

- The first one is `inside limit` which means limit the result count for each time period.
- The second one is `outside limit` which means limit the result in the final step and need to calculate all the result first.

For example, like we need query a metric for companies during 2017 to 2019 and group by year and limit is 5, the first approach means get top 5 companies for each year and combine the result in final step. And the second approach means calculate the metric for all companies in all time period and sort the result by the latest value and then limit the count.

For common situation, the second approach is better and really make sense.

But for ranking list like OpenLeaderboard, we need the first approach since we really need the top 5 results for every time period.

Do I make this clear?

And I think we can add a new option `limitOption` and default is `outside`, and can be `inside`, for data export procedure like OpenLeaderboard, we can set it to `inside`.

**Comment by xgdyp** [comment]
I think using `limitOption` is great. But `outside` and `inside` maybe confusing. How about `limitEach&limitTotal`?

**Comment by frank-zsy** [comment]
I think `each` and `all` are good.

**Comment by xgdyp** [comment]
> I think `each` and `all` are good.

Yes, this is better!

**Comment by frank-zsy** [comment]
For `all` situation, we don't really need to sort the result in the inner select clause but only order in the last step but for `each` limit situation, we need to sort the result inside.
