### ISSUE TITLE
[feature]actors metric

### ISSUE THREAD

**Issue by bifenglin** [X-lab2017/open-digger#1068]
there are plenty of metrics for actors. could this is a hug feature for both opendigger and hypertrons-crx.
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/15813364/203897873-3bdd8aff-44a5-42b8-9c59-26f63da7762e.png">

**Comment by xgdyp** [comment]
Do you mean add more metrics?

**Comment by bifenglin** [comment]
I mean is the metrics mainly about repo, and we can glance at these repo data from hypertrons-crx, but as I know, there is no chart about the actors, which is as developers or users count. So we can realize some metrics to support the feature.

**Comment by xgdyp** [comment]
> I mean is the metrics mainly about repo, and we can glance at these repo data from hypertrons-crx, but as I know, there is no chart about the actors, which is as developers or users count. So we can realize some metrics to support the feature.
You are right. I think we can do a lot on developers such as `Which repo does the developer put the most effort into recently?`. So do you have metrics on developers now?
By the way, I think the reason we didn't do this before is that open source governance is always about projects instead of people.

**Comment by bifenglin** [comment]
Ok, maybe open source governance predominately relies on the metrics of repos, but there are some people and institutions who cared about the actors' activities, such as tracing someone's activity or surveying someone's major domain.

**Comment by xgdyp** [comment]
> Ok, maybe open source governance predominately relies on the metrics of repos, but there are some people and institutions who cared about the actors' activities, such as tracing someone's activity or surveying someone's major domain.

Yes, but what do you think we can do? I just think GitHub already has some useful charts to present developers' activities

**Comment by birdflyi** [comment]
Shall we abandon this metric? Otherwise, shall we implement it or call the github interface?

**Comment by birdflyi** [comment]
Okay, got it.
