### ISSUE TITLE
[Proposal] discussion of the organized format of the JSON data offered by OpenDigger

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/open-digger#1074]
Hi @frank-zsy  , we just talk about the format of the JSON data in [DataEase Metting](https://github.com/X-lab2017/open-wonderland/issues/219). We suggest a new data format but not sure whether it is feasible, so could you help us?
For example, [https://oss.x-lab.info/open_digger/github/X-lab2017/open-digger/activity.json](https://oss.x-lab.info/open_digger/github/X-lab2017/open-digger/activity.json), currently, it's data format like below :
```json
{
"20221": 26.08,
"20222": 17.04,
"20229": 45.73,
"202210": 57.06
}
```
we suggest a new data format: 
```json
[
    {
        "org_name": "X-lab2017",
        "repo_name": "open-digger",
        "type": "activity",
        "month": "2022-01",
        "value": 26.08
    },
    {
        "org_name": "X-lab2017",
        "repo_name": "open-digger",
        "type": "activity",
        "month": "2022-02",
        "value": 17.04
    },
    {
        "org_name": "X-lab2017",
        "repo_name": "open-digger",
        "type": "activity",
        "month": "2022-09",
        "value": 45.73
    },
    {
        "org_name": "X-lab2017",
        "repo_name": "open-digger",
        "type": "activity",
        "month": "2022-10",
        "value": 57.06
    }
]
```
@tyn1998, If the data format changed, will it have a big impact on the refactoring of hypercrx? @will-ww @xueqidove @xgdyp could you have other suggestions?

**Comment by xgdyp** [comment]
Can we change the format of the date, the original format may be a little difficult to use.

**Comment by xgdyp** [comment]
> 
> ```json
> {
> "20221": 26.08,
> "20222": 17.04,
> "20229": 45.73,
> "202210": 57.06
> }
> ```
> 
> we suggest a new data format:
> 
> ```json
> [
>     {
>         "org_name": "X-lab2017",
>         "repo_name": "open-digger",
>         "month": "2022-01",
>         "type": "activity"
>         "value": 26.08
>     },
>     {
>         "org_name": "X-lab2017",
>         "repo_name": "open-digger",
>         "month": "2022-02",
>         "type": "activity"
>         "value": 17.04
>     },
>     {
>         "org_name": "X-lab2017",
>         "repo_name": "open-digger",
>         "month": "2022-09",
>         "type": "activity",
>         "value": 45.73
>     },
>     {
>         "org_name": "X-lab2017",
>         "repo_name": "open-digger",
>         "month": "2022-10",
>         "type": "activity",
>         "value": 57.06
>     }
> ]
> ```
why not like this?
```
{
    "org_name": "X-lab2017",
    "repo_name": "open-digger",
    "repo_id": 0,
    "type": "activity",
    "data":[
        {
            "month": "2021-01",
            "value": 123,

        },{
             "month": "2021-02",
            "value": 124,
        }
    ]
}
```

**Comment by zhicheng-ning** [comment]
> why not like this?

It's also a good format.

**Comment by frank-zsy** [comment]
I am not sure why the change suggested? I use the original format because I think org, repo, metric information are already in the URL, so you should fully understand what you are querying. So the org, repo and metrics field are redundant data in this scenario. And the new format will cause a quite large data size expansion, since the original format is the smallest size format I think.

**Comment by frank-zsy** [comment]
Take this file as example, the original file size has 158 characters and even use the format @xgdyp suggested has 447 characters which is:

```
{"org_login":"alibaba","repo_name":"celeborn","repo_id":92392932,"type":"activity","data":[{"month":"20221","value":34.73},{"month":"20222","value":15.52},{"month":"20223","value":36.74},{"month":"20224","value":17.98},{"month":"20225","value":27.46},{"month":"20226","value":44.45},{"month":"20227","value":65.7},{"month":"20228","value":107.35},{"month":"20229","value":126.58},{"month":"202112","value":18.8},{"month":"202210","value":134.93}]}
```

That means we will need about 3 times for data storage and network cost which is also expensive for massive data.

Like for 2022.11, Hypercrx queried 100GB data from OpenDigger OSS, with the change, the data will be 300GB which is 3 times cost. I think we should also consider this.

**Comment by zhicheng-ning** [comment]
ok. I will do a backend service to implement this format which can better used in DataEase.

**Comment by xgdyp** [comment]
Okay, also can we improve the date format a bit? Like `20221`, `202211`, this need downstream apps rewrite a sort function . Is this also a storage cost consideration?

**Comment by zhicheng-ning** [comment]
> I am not sure why the change suggested?

Because current json format will be imported as follow. But it' better just two columns, one is `month`, another is `metric_value`.

![image](https://user-images.githubusercontent.com/39022409/204972493-58d0deee-64e3-4fa9-a7b8-db2a9d851f02.png)

**Comment by frank-zsy** [comment]
> Okay, also can we improve the date format a bit? Like `20221`, `202211`, this need downstream apps rewrite a sort function . Is this also a storage cost consideration?

What does this mean? Do you mean we should change `20221` to `202201`? This is not quite about storage cost, but like if we know the year is `y` and the month is `m`, then the key is `${y}${m}` which is quite easy, if we use `202201`, then we need to padding the `m` to add a `0` before `1`. 

And if you are using a for-loop to get the data item, then it is for sure in order. And since `0` value will not has a key, you can not just sort the key and use the data. So in which scenario you will access all data and need a sort?

**Comment by frank-zsy** [comment]
> > I am not sure why the change suggested?
> 
> Because current json format will be imported as follow. But it would be better just two columns, one is `month`, another is `metric_value`.
> 
> ![image](https://user-images.githubusercontent.com/39022409/204972493-58d0deee-64e3-4fa9-a7b8-db2a9d851f02.png)

Understood, maybe you can develop a backend to transform the data, new format will cost a lot for storage and network, although it looks like much more official.

**Comment by xgdyp** [comment]
I mean like `2022-01`,this is one of the default time type. So we can make charts more easily.
![image](https://user-images.githubusercontent.com/37795442/204978555-7cf40028-25f2-4ce9-bebf-ac8a365ae213.png)

Our current format may cause a result in xAxis like [20221,202210,202211,202212,20222,20223,...,20229]

**Comment by frank-zsy** [comment]
> I mean like `2022-01`,this is one of the default time types. So we can make charts more easily. ![image](https://user-images.githubusercontent.com/37795442/204978555-7cf40028-25f2-4ce9-bebf-ac8a365ae213.png)
> 
> Our current format may cause a result in xAxis like [20221,202210,202211,202212,20222,20223,...,20229]

OK, this makes sense, I can do this. So `2022-01` or `202201`, which is better?

**Comment by tyn1998** [comment]
> So 2022-01 or 202201, which is better?

I prefer `2022-01` 👍

**Comment by zhicheng-ning** [comment]
> ok. I will do a backend service to implement this format which can better used in DataEase.

The backend service is completed！

- [For repo](https://github.com/X-lab2017/open-digger#for-repos):
`http://api.x-lab.info/{org_name}/{repos_name}/{repo_metric}`
eg:  http://api.x-lab.info/X-lab2017/open-digger/openrank
- [For user](https://github.com/X-lab2017/open-digger#for-users):
`http://api.x-lab.info/{user}/{user_metric}`
eg: http://api.x-lab.info/zhicheng-ning/openrank
