### ISSUE TITLE
[Feature] network data for Hypercrx might be regenerated with latest formulas

### ISSUE THREAD

**Issue by tyn1998** [X-lab2017/open-digger#1081]
[Hypercrx](https://github.com/hypertrons/hypertrons-crx) presents network charts in both `Perceptor`s of repo pages and of profile pages. At the moment, there are 4 APIs backing these charts:

- repo
  - related repos: https://hypertrons-oss.x-lab.info/repo/hypertrons/hypertrons-crx.json
  - developer network in this repo: https://hypertrons-oss.x-lab.info/repo/hypertrons/hypertrons-crx_top.json
- developer
  - related developers: https://hypertrons-oss.x-lab.info/actor/tyn1998.json
  - repo network: https://hypertrons-oss.x-lab.info/actor/tyn1998_top.json

These data reflect status of repos and developers in the past **180 days** and they are regenerated each week (I suppose?). However, the formulas underpinning the data generation are really outdated, which makes `Activity` of nodes not consistent with the latest `Activity` we use in other charts.

Also, the data mentioned above are deployed in another oss sever, which in my view is not necessary. So I suggest that these data can be implemented here in OpenDigger with the latest computing methods.

We can talk about the schema of the json files here as well.

**Comment by frank-zsy** [comment]
Of course, we can make the data generated from OpenDigger and we can decide how to do this.

First, I think we can use some standard graph format like GDF, here is a [graph file format overview paper](https://www.researchgate.net/publication/330185503_Overview_of_Standard_Graph_File_Formats), we can discuss which one to use.

**Comment by frank-zsy** [comment]
I think we use the JSON format at first place because the data can directly consumed by ECharts graph component. I think CSV format is also universal. As a user, which one do your prefer? @tyn1998

**Comment by tyn1998** [comment]
JSON is a first-class citizen in JavaScript, while people using Python to do data analysis might be in favour of csv.

Both format is ok for me since a little data parse is not a big deal.

I had a glance at [GDF csv format](https://gephi.org/users/supported-graph-formats/gdf-format/) in the paper, I think it's good.

**Comment by frank-zsy** [comment]
OK, then we should discuss how the data are generated now. The first version use repo - developer relationship to generate the network. Repo - repo and developer - developer also use repo - developer relationship too but just aggregate.

I think the repo - developer network and repo - repo network work just fine with activity index as relationship, but for developer - developer network, some users are confused because they don't really know the other developers in their collaborating network, we can use issue level data to make relationship for developers which may make sense much more.

WDYT.

**Comment by tyn1998** [comment]
Do you mean developer collaboration network on profile by "developer-developer network"? Actually it's fine, at least for me.

Q: what constitute issue level data?

**Comment by frank-zsy** [comment]
Yes, I am talking about the network. The issue level data means only two developers are both active on a same issue, one collaboration relationship will occur. But right now, two developers are both active on a same repo will lead to a collaboration relationship even on totally different issues or pull requests. In this situation you may find some developers related to you but you are not really know him especially if you are active on a quite big repository with many issues and pull requests.

**Comment by frank-zsy** [comment]
I think I will come back to this one after the Clickhouse version upgrade done #1087 . We can have more discuss on this one and further more we can even add the network generation code into OpenDigger as new index.

**Comment by frank-zsy** [comment]
As CH server upgrade completed, I will work on this one.

What data exactly you need @tyn1998 ? I think for all the networks, you need repo/user node name/login, and relationship weight. To get user avatar on GitHub, do you need user id or login is enough?

**Comment by tyn1998** [comment]
> I think for all the networks, you need repo/user node name/login, and relationship weight. 

Yes, that are all Hypercrx need to present network charts.

> To get user avatar on GitHub, do you need user id or login is enough?

`login` is enough :-)

**Comment by frank-zsy** [comment]
@tyn1998 OK, but for node weight, what do you think is a proper value? Activity for last 6 months or OpenRank for last 6 months? 

And actually I think 3 months is also fine to construct network since 6 months involves too much data.

**Comment by frank-zsy** [comment]
OK, I was trying to implement this in ClickHouse with some temporary tables, but I found it is really hard and resource consuming to generate network data because many `join` operations will be involved and ClickHouse is not quite good at `join` operations.

So I will generate these data by Neo4j database.

The node weight will be OpenRank for last 3 months, and the relationship weight for each pair of nodes will be the activity score by harmonic mean method.

So the data will be:
- Repo's developer network
  - Nodes: developers active on this repo in last 3 months
  - Edges: developers activity harmonic mean by repo connection in last 3 months
- Repo's repo network
  - Nodes: repos has collaborative relationship with this repo in last 3 months
  - Edges: repos activity harmonic mean by developer connection in last 3 months
- Developers' developer network
  - Nodes: developers has collaborative relationship with this developer in last 3 months
  - Edges: developers activity harmonic mean by repo connection in last 3 months
- Developers' repo network
  - Nodes: repos that this developer is active on in last 3 months
  - Edges: repos activity harmonic mean by developer connection in last 3 months

Does this make sense to you? And for each network, I will return at most **50** nodes order by the corresponding value.

**Comment by tyn1998** [comment]
That sounds great and reasonable 👍

**Comment by frank-zsy** [comment]
@tyn1998 Is there problems with the original JSON format? What format do you want?

**Comment by tyn1998** [comment]
No big problem, just considering to redundance in those files (since other APIs handle file size so carefully):

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/32434520/208628104-daac597f-16c8-4cb3-ae16-29a866d21a69.png">

> What format do you want?

The aforementioned [GDF](https://gephi.org/users/supported-graph-formats/gdf-format/) looks good to me.

**Comment by frank-zsy** [comment]
But with the GDF format, nodes and edges will be stored into different files right? If I use JSON format with out key, like:

``` JSON
{
  "nodes": [["frank-zsy",3.1],["tyn1988",5.3]],
  "edges": [["frank-zsy","tyn1988",1.4]]
}
```

So for nodes, a node is an array with 2 elements, first one is name and second one is OpenRank. For edges, an edge is an array with 3 elements, first two are source and target and the third one is weight.

I an not sure how to put nodes and edges data into a single file if we use GDF format.

**Comment by frank-zsy** [comment]
If we are quite careful about the file size, I think we can define our own format, like even in GDF or above format, user names in edges are also redundant data. We can use nodes' index to replace the actually user name. Like:

``` JSON
{
  "nodes": [["frank-zsy",3.1],["tyn1988",5.3]],
  "edges": [[0,1,1.4]]
}
```

In the edges, first two elements are not user name but user index in nodes.

**Comment by tyn1998** [comment]
Hi @frank-zsy, @birdflyi also recommands another XML-based format called [GEXF](http://gexf.net/). Well, personally I do not like `<>` pairs very much 😆. I like the JSON based formats you just mentioned. And compared to the more compact one, I like this format more:

```json
{
  "nodes": [["frank-zsy",3.1],["tyn1988",5.3]],
  "edges": [["frank-zsy","tyn1988",1.4]]
}
```

Because it's also readable for humans. Actually both look nice to me. You just choose either of them!

**Comment by frank-zsy** [comment]
Yes, XML-based format has much more redundant data than JSON format. I can use above format and I will constrain the nodes count to 30 which is also the configuration for now, and for 30 nodes, we can have up to 435 edges in a single network, do you think we should also filter out some edges in the data? Too many edges may also not quite elegant after visualization, or I put all the data into the file and you can filter out some edges in Hypercrx.

**Comment by tyn1998** [comment]
Please provide all edges and I'll do the filtering work~

And it could be great if you can list edges in descending order by their weights. So for nodes, just for readability.

**Comment by frank-zsy** [comment]
So you want nodes are sorted by OpenRank in descending order and edges are sorted by relationship weight order right? I think I can do that.

**Comment by tyn1998** [comment]
Actually, I mean that. 👍

**Comment by frank-zsy** [comment]
I have implemented the export task in #1103 , the process may take about 1 day to generate and upload the data. The data will be at:

- https://oss.x-lab.info/open_digger/github/X-lab2017/open-digger/developer_network.json
- https://oss.x-lab.info/open_digger/github/X-lab2017/open-digger/repo_network.json
- https://oss.x-lab.info/open_digger/github/frank-zsy/developer_network.json
- https://oss.x-lab.info/open_digger/github/frank-zsy/repo_network.json

Which are identical with current metrics data.

**Comment by birdflyi** [comment]
> Hi @frank-zsy, @birdflyi also recommands another XML-based format called [GEXF](http://gexf.net/). Well, personally I do not like `<>` pairs very much 😆. I like the JSON based formats you just mentioned. And compared to the more compact one, I like this format more:
> 
> ```json
> {
>   "nodes": [["frank-zsy",3.1],["tyn1988",5.3]],
>   "edges": [["frank-zsy","tyn1988",1.4]]
> }
> ```
> 
> Because it's also readable for humans. Actually both look nice to me. You just choose either of them!

If you have any requirement about gexf format transformer between xml and json, you may try this: [birdflyi](https://github.com/birdflyi)
/
[nx_gexf_xml_json_transformer](https://github.com/birdflyi/nx_gexf_xml_json_transformer)

@frank-zsy @tyn1998 Have fun : )

**Comment by frank-zsy** [comment]
@tyn1998 The process has done within 12 hours, you can check if the data can be used now

**Comment by frank-zsy** [comment]
But there is a thing that we use OpenRank for nodes' size, so in repos' developer network, we can not find out how close the users involved in the repo since the node size is users' global OpenRank and the edge weight is users' global collaboration relationship. It may confuse users.

**Comment by tyn1998** [comment]
@frank-zsy I thought there was something like `local OpenRank` like we do in XSOSI so I replied:

> Hi @frank-zsy, for me OpenRank in 3 months is good.

Global `OpenRank` used in a single repo will definitely lead to confusion, and a similar confusion already happened in the current developer network:

<img width="850" alt="image" src="https://user-images.githubusercontent.com/32434520/208820104-0fc47147-d1c1-4793-ba7d-15b750383eeb.png">

Yet the node value won't affect the graph shape because the graph should be shaped only by in/out degree of nodes. So serveral central developers are still expected to see.

**Comment by frank-zsy** [comment]
@tyn1998 In repository OpenRank takes lots of resource to calculate, we can not generate OpenRank for all the repos right now, yet we can use activity in this repo as the node value, in this way, we can also find out the central developers in the repo.

**Comment by tyn1998** [comment]
Agree, it's better to use local `activity` as node value in repo's developer network.

So will you regenerate those files with `activity` as node value?

**Comment by frank-zsy** [comment]
Yes, I will modify and generate again, and I think there is a same situation for developers' repo network.

**Comment by tyn1998** [comment]
> and I think there is a same situation for developers' repo network.

Yes. However the old version seems handle this situation right:

<img width="863" alt="image" src="https://user-images.githubusercontent.com/32434520/208835912-f97895a4-e793-4437-b159-3554615a8a52.png">

**Comment by frank-zsy** [comment]
OK, I will fix this for both networks.

**Comment by frank-zsy** [comment]
@tyn1998 The data has been updated, you can try them now.

**Comment by tyn1998** [comment]
Hi, @frank-zsy, they are good.

repo's developer network:

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/32434520/209049266-8a22817f-0bed-4a7c-976a-dc522ac8bde4.png">

developer's repo network:

<img width="664" alt="image" src="https://user-images.githubusercontent.com/32434520/209049305-754ec9ca-bf4a-4fd0-a8d7-a95973f29b98.png">

The networks are still [in development](https://github.com/hypertrons/hypertrons-crx/pull/553).  Some edges will be filtered out.
