### ISSUE TITLE
[proposal] GitHub Bot data requirement

### ISSUE THREAD

**Issue by bifenglin** [X-lab2017/open-digger#1089]
There are many auto activities in GitHub, such as the apps in [https://github.com/marketplace](https://github.com/marketplace), and some of them are easy to identify and can accord to the column `user_type,` which divided actors into `User` and `Bot.` However, some Bots also have a `User` type, meaning we have to identify them manually. And these actors are not real human beings and have a high probability produced activities by auto. So I propose the collection of data requires actors' labels about is a Bot or not.

Some of the examples:
- VSCodeTriageBot
- SnoozeThis
- LombiqBot
- renovate-bot
- codestar-github-bot-1
- rjpagano
- zhangsansana

**Comment by frank-zsy** [comment]
@bifenglin Are you going to raise a PR for this?

**Comment by bifenglin** [comment]
> @bifenglin Are you going to raise a PR for this?

yeah, I have found lots of GitHub bot accounts. But I haven't found any docs for how to create a new type of label data until you reply.

> Yes, I think so, you can add a bot folder and index.yml in it. Name should be GitHub Bot and type is Bot, add these accounts into data.github_users as array is fine.  

Thanks for this advice.

**Comment by bifenglin** [comment]
And I have found some accounts belonging to a team or a company, such as `magento-engcom-team` and `fabricteam`. And I found these also a good dataset that can find some interesting findings, like lots of them both have auto activity and human activity. However, it also not appears in our label data.

**Comment by frank-zsy** [comment]
closed by #1132
