### ISSUE TITLE
System requirement？

### ISSUE THREAD

**Issue by yxgt01** [X-lab2017/open-digger#1090]
Hi，I want to use open-digger. What are the minimum system requirements? Such as CPU，memory，disk and so on.

**Comment by frank-zsy** [comment]
Hello, this depends on how do you want to OpenDigger.

- If you only want to use the metrics data OpenDigger produced, you can directly use them like README describes, there are already 10+ metrics data can be retrieved from OSS.
- If you want to develop your own metrics from raw data, you can see [sample data docs](https://github.com/X-lab2017/open-digger/tree/master/sample_data), there are several sample datasets you can use to run data service locally, to init the ClickHouse docker instance you may need 8GB memory and disk usage depends on what dataset you use. CPU is not quite constrained.

And welcome to add the data badge to your application or cite OpenDigger as your reference in your research work.

**Comment by frank-zsy** [comment]
@yxgt01 I will close this for now and you can raise a new issue if you need any help later.
