### ISSUE TITLE
[Feature] Publish more metrics into OSS.

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger#1105]
As we implement more and more data in OpenDigger, we can publish new metrics data into OSS every month.

We already have about a dozen repo metrics right now on OSS, most of which are statistical metrics or indices that can be accumulate by time. So we only generate monthly data for all metrics, but not quarterly or yearly.

But for other time related metrics like issue resolution duration or issue response time, we can not easily add monthly data to get quarterly or yearly data, we need to generate data for different time range separately.

So I think for new metrics data, we can add quarterly and yearly data too.

We can use `2022-04` to indicate monthly data, `2022` to indicate yearly data and `2022-Q1` to indicate quarterly data, and maybe use `all` to generate data for repos' all life cycle.

This may also effect Hypercrx code right? @tyn1998

**Comment by tyn1998** [comment]
Hi @frank-zsy, if APIs of existing metrics all remain the same and only comming new metrics are with different timespans, though extra code is required to parse `2022`, `2022-Q1`, `all` and so on, I think we will not suffer a dirty data migration as we did last time.

**Comment by frank-zsy** [comment]
@tyn1998 Does support for `2022`, `2022-Q1`, `all` key under developing? Can we add more data for 2023.3 data release?

**Comment by tyn1998** [comment]
Sorry for the late reply. I have opened an issue in Hyperxcrx:

- https://github.com/hypertrons/hypertrons-crx/issues/577

The feature support will be finished before March.
