### ISSUE TITLE
[Bug] Data update to OSS does not work for vscode and some other repos.

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger#1109]
As we discussed in #1036 , there are some data can not be updated on OSS like `microsoft/vscode` or other repos.

The reason that some repos' data can not be updated contains several key points:

- The upload process is running under MacOS which is a case insensitive system.
- `microsoft` org name used be `Microsoft` and changed to `microsoft` someday, so in the events log, there are two names for the repos under the org.
- As there are about 12 millions files need to be updated and uploaded every month, it is not easy to remove all the files in local machine and regenerate all the files again(`ls` and `rm` will cause crash of bash since too many files under the folder).
- So for effectiveness, I do not remove local files and just generate new data every month and then upload to OSS.
- And for effectiveness too, I do not remove OSS remote files and just update them by uploading.
- So when I generate network data for microsoft org, somehow I created a folder named `Microsoft` in local disk and even though metrics data are generated to path named `microsoft`, the data goes into `Microsoft` since the system is case insensitive, which makes data under `microsoft` on OSS will not be updated.
- The [jina-ai/docarray/issues_closed.json](https://oss.x-lab.info/open_digger/github/jina-ai/docarray/issues_closed.json) issue is also caused by rename, the repo is named as `docarray/docarray` now and `jina-ai/docarray` is an old name of the repo, so the data will not updated since the name has already changed.

So to avoid such thing, following steps should be established:
- To generate data for all metrics, indices and networks, we should always use the latest name of repos and users, and avoid to use old name for any repo or user.
- To generate data locally, we should remove the local files and regenerate again to handle changes of letter case.
- To upload data, we also need to remove remote files and upload again to remove old names files which maybe left behind after change of names.

**Comment by frank-zsy** [comment]
I have updated the data, you can check if the they are good or not.

But it is still hard to remove old files from OSS, it is really time consuming to remove more than 1 million files, and it will cause service failure for a while.

So what I think is a new process flow:

- Remove old local files.
- Generate data for every month, including metrics data and network data.
- Upload files to OSS.
- NEW: Find out all the orgs and repos that changed their names, and remove all the old names from OSS one by one.

The last step is a new one to remove all the old names with low cost since there are not so much orgs and repos changed their names on GitHub.

And @zhicheng-ning , you find some old repo names from OpenLeaderboard since the ranking list contains data for every month in the history and we will use old name for these repos at that time, so you may find some repos do not have related data on OSS.

**Comment by frank-zsy** [comment]
BTW, I run some queries on database, for all time range and the repos to export, there are only 8,450 orgs and 135,320 repos changed their names so it is feasible to remove the files from OSS.

**Comment by tyn1998** [comment]
> I have updated the data, you can check if the they are good or not.

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/32434520/209543096-e434b7eb-b8a0-416d-a49b-0b68725a1df5.png">

I have checked those failure cases and now they look good.

BTW,  we (and @longyanz ) tested positive for COVID-19 three days ago and are suffering from the disease so recently we may not be as responsive as before 🤧

**Comment by frank-zsy** [comment]
@tyn1998 No problem, me too, so take good care of yourself.
