### ISSUE TITLE
[Data] Re-add missing events into ClickHouse instance.

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger#1122]
`PullRequestReviewEvent` type events are not in ClickHouse right now, we should add them back to database to get more accurate reviewers data.

**Comment by frank-zsy** [comment]
According to the event data payload object, the `PullRequestReviewEvent` contains all the data in `PullRequestEvent` and there is an extra `review` field in the payload.

The `review` field contains some useful data which requires new columns, includes:

- body: review body, maybe `null` or empty.
- state: approve state including `approved`, `commented`, `dismissed`, `changes_requested`.
- author_association: the review author's association to current repo, including `COLLABORATOR`, `CONTRIBUTOR`, `MEMBER`, `NONE`, `OWNER`, `MANNEQUIN`

Is there any other field you want add into the database schema?

**Comment by tisonkun** [comment]
@frank-zsy These columns are sufficient to my use case. I need only to count the number of `PullRequestReviewEvent` and perhaps filter them by state.

**Comment by frank-zsy** [comment]
@tisonkun OK, I will add `pull_review_state` and `pull_review_author_association` columns and reuse `body` column just like other events. The data initialization may take about 2 days to complete.

**Comment by frank-zsy** [comment]
@tisonkun The import process has been completed.

**Comment by tisonkun** [comment]
Thank you! I'm verifying now.

**Comment by tisonkun** [comment]
Verified now. Thanks for your help!
