### ISSUE TITLE
[Data] Add StoneDB labeled data

### ISSUE THREAD

**Issue by Nliver** [X-lab2017/open-digger#1124]
I want to add some labeled data into OpenDigger to help us for our community analysis.

Label: Chinese

Type: 'Project'

Repos:

- stoneatom/stonedb

Orgs/Users:

- stoneatom

**Comment by frank-zsy** [comment]
@Nliver Thanks for the data, and does `StoneDB` project related to any company? So we can add `StoneDB` as a project label and add it to a related company, then add the company to Chinese label.

**Comment by frank-zsy** [comment]
@Nliver That data has been merged into OpenDigger, thanks for the label data again.
