### ISSUE TITLE
[CI] We should add simple tests to OpenDigger

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger#1126]
Right now, OpenDigger does not have any test code to make sure all the functions are working as expected, like labels, metrics and indices.

But recently, with more and more functions added into OpenDigger, and some refactors also break the code. This implies that human review is not sufficient anymore for OpenDigger.

So I think we should add some simple tests to OpenDigger to make sure:

- All label data works fine and returns desirable results.
- All metrics can run successfully and return correct format data.
- All database drivers works fine.

I think a simple test structure with [mocha](https://www.npmjs.com/package/mocha) is enough for now.

**Comment by will-ww** [comment]
Good to see OpenDigger grow and step into the CI/CD stage~
