### ISSUE TITLE
[Feature] Add some ECharts demo support for complex metrics

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger#1163]
### Description

We can add some demo of ECharts to demonstrate how to use the metrics, like:

- Active dates and times, which is working hour distribution.
- Time duration related metrics like issue/change request resolution/response time.
- Contributor related metrics like total/active/inactive contributors.
- Issue/change request count related metrics like open/close.

**Comment by frank-zsy** [comment]
A demo like [this](https://echarts.apache.org/examples/zh/editor.html?c=candlestick-simple&code=G4QwTgBAJiAuIQLwQN4CITAOZoFzoCYAGYgWiIA48BGagOiIE4AaNYspvCgNlfaNLUiNHnQCsfEgNo16BSWWoEaYgnQAsC6uWo0CAZjoV9W8stz7DBCWxLai-vPoLc6l00XV4C612IoeYngA7GJ03MEe3E4UYcEstgT2wXjqCez2VLjU6hRuJon2jCGmQiWFgrq4BnTB1KXm1GE8CgQ6qfTBBextJKmt5I64weH1ib1ew64B4-RBFmrWA0TRuOrys0QpFkbdJL1ZeWKRm8XZaic9gsLZvLMy2fT6M1dKIUYAvqwANgCmwL9vgBnPCEKTkLIAbQkJnqBAAugoBJxcJDNPUiMwEUjrnhIfUMVjEYlpFVISZYcx9MT-IJzJD5JpMeoaXZ2qjmcwCaykmY8Zj5AKefYhpDMeKqcLyJMGVy5RQpUR5vjmEzVYrVuTVcwBcFFdsxXLmYqoZzMWJFWdDSZxVKyhyqTqdXayfV0Vy7fS4ViicsySY1SzlvT5ILnctRdQA07qDyJnj5ITsZtlYyncmris8UIfW64-QDZETIL85QE9rMbHllbo4n8_bocwJPU9QMHviTM3mK37vTeLxMdSvmgAI4AVxAADtYABLP4AfRuYI4WUxJPIZzGtPtG23VTX2_MB7ZRCqlxP5nPvIceDENgy0rwx-v82f9lWb4L5QfZeGHjOV7aPagGVE-DRgZs-7BjQEYQZmkzPr0r7LB-yzbIhEJwfsG5YQQbT2hhDyEUew7jlOs4LlUy7Ilkaj3uCKK7uC9pxPRihVHROJvH-FSnt-F78deQzEOo4geJMRyBIJ754IwIyhB42w-B4WQgSiIHAaUZ7gTxmZVJomyNLBuAYZ4MEpk4YmbKhmzbFu2G_gZmZnJx9w3FYbH4fudBLL23ikRO05zr887mNRmFrDiKJ7IoNy0OkzHaeu3FqUlP6NAlQlOGITknpM1AUK5P7zGpqxiM4ineLl15ZLQdw_gBpQ3BpaVstxUZ-oJvTmNVvRDEQVnwf0Fm6Q5qz2XhX7VMsqnVl1uKjZNDwxfhPUBeRwXzkM4W_iMbHIi59XMTcBCMIwtT7aB2RXtI5j6HUPlsfYZ4XR4PVhL5P5DL4THXpM6i0INJ7zNQmUybgYiMKxlXVNVmTeEk_7SQtLU0ANT10t4hieey-jnTjfSLX1t6vZs-WfQ5INFWNaNofNu1zY8QNLSdHltlUTSk68l7rUFC6TDtWQRFFZw5b90g3GIKxcfpE23ak5UeGeWxvVwLwnkMxyfmZuDcAYUkWLQUR4Nwngw9Q3BHTVt4EOr16NRUmmOxzymO3dV69BxcnQUTgxo71j7VDlyzzOwKEIwTdmmVk-gTb0AFxwtjBW15JsrZjFhiB8HwAFCgJAZF878QJIBAkIAOSFxRIXUOXzCV4F1dbXXDcbQuRAt1Xm3qOX8IANx5-AEAALYAPbTgAFsXpcAPIAEYAFa_AAxrAdAANa_AAnkCAAUMDwJCXd_ECYrwvCACUA-jwADrO4-lygOcQBAs6wH8uCoM_L-v78AAesBP7lwAJJAiBGOX4EAABKxdR7fDHPfScEAAAqM5h6QIAGaj0gDPG-vxJwABEZxYCwL8MAddv4vz-BgwBEBy7L3wbAMh5dv5fG_n_AAgn_GcQJP5Px_hAScIB0FALHpPChAiD4gE_mI2AU8gSsOYN_LeXCeF8MoYI4RvwgGgPAZAmBQI4EIJnA_VB6Dd7fFHlgCAM4kEwB3hfFhL82EvyBGQmcxdP6Qg0fwgRr8t54KAcvKcUAT6zmXuvCRfiZxMOHgAZVgFvD-X8_E_2XnA7BQC57wN-HXCA6TLFgCIFknJeS57YKgGQgAwhksAJSIFlIqdU2pxS6HZIaUo1JLi_FSJkePORxc6DDxADfXew8kAAD4IDH0GcM0ZI5JkpNSRAMAvxYBjjAEggAsnACedBLFYH3nAEAR94SQmHvCCAABqCA1Ar4aOcRfC-nSf65xfvCHOHw-5AA) can be used.

**Comment by frank-zsy** [comment]
This is a [demo for active dates and times](https://echarts.apache.org/examples/zh/editor.html?code=G4QwTgBGCmAOD2A5EBbaEC8EDkANAtADYgBGATAAwCMA7APTyzQB2-AJgJYDmX0Y2AbgBQAEgB0vAC4ApAMoB5RAAohEHAAtJk2AGcAXHQY6dYgB5FSYjswBm8Bk2YB9Tjz50uHSeoCuJOtgQANRQcEio6CHYdCAAxpIcwNAuIJLQOk4gzGxOCWgmAFY68MzYADSqEDY-zPEcJUpsqSAAlBAA3pVqhhCwMFocfPjczPAwXRCxJTqSEOrwPmA6mBAA2hNqathUZCDlOFR7ZTi7-9gAzEc4ACxX2ACsdwBsdzR3ABx3AJx3VBS_h3KG022zIsDOVHBx2wYLO5yhNwRDyRTyRNCR7yRXyRfxxkOwEwAusJNhAen1oAMhiMxtAJlNmDMIE0AJ7LLDrUmk7CyGqss6yVKLfnQgBiYA4IpwABVfEspdgAOrQNjMdIK6U-dUgFlnACyJX5RJJm3J_QS1K4o3GpJ6Oh8KAgPlgEBAhEIEG86AA7mMANbWLhzBZgCagSCgQha9kQeQkArQeJiSPRxrNFpiGBsHyxaBKJSwY6xNoYAB8HWBHBsEALmAwWGYPndbX6i2YkxNpNbYHbsDEKBAsHzwGOHBL5eAwUmqw4hJanYgAF9jo3mwuJj0fDp0IR4EHJPAIDoUPB4N5Pep0E1JCAN3RJvAUGhmLNvBxloRrOgqxAWQsIN6WSvoeW47l-4DMs0YZutGKwpuk_aDkok5lhAeqpOoYi7lwyFTlQLTzhMd4QNaA6fgAXiqnqHhQED4BAfzQZAA6mCs6HeIhphKGIPHwTohGknxcEwQhA5Dih5bsZhuYcIQuEAFQMbR94sQRwhMRA1iwD4kgACLNCsqzEhMdiQMhEFsCsFACMyEAADwQDQNlsEEQRtJ0XJVGMNbhnMVk2eo9kQGQ1wBa57nAmoWk6fpN5iNpOjqEoqzqMcTx0cyxx8aslmKSFU7qISEAAD7FTg-DYHOC5qIuEy1WoEyMAkJQrB5XIJJIhDQHoFaeWoaSmJIPUAAYAIJ1EkECxekECjdkEDShw-ReZAIjtDACDIGgi7DRUfUQF1NhDTguYvnwBKecuwJcBKbA9W1nmXtwmg9Q8FAAKRAvtB6wK9fyfcCV2eaYo2mO-92RZ6LJMK9sSpNAXBjLqe19deIA9fMiw6Cjnk6LAn6SKNMDo71-1HvM3o9ZIYBapD9VckDXIsqD4Ok55kjQ91J3w4jYDI5DaM9ay2OQ3jBNE9AJMPX1iXwJTno03S-306SjOCe-Phuuhv1s1yKDWD1FA43rICmD1fzG6ScOELETakF1VOK5bmxjIML6vfMErkSUN6EF9fWHcd2CnWk_DO2oJBngeKB_fcAOXc724SukPWcn10vs5zHuS5IYn-_tguacw2l6c04ebMQJDQIQENk5ssvy9TtN12rfXQCgsDqCAOisxnfVeO3sgcw7ut14lIBsHLABCUZgObRuQ7jXeT96ADC8C7nPOBgFwJAgEoRsQIfx9iPcLQXXXS6L1fyvAoSdULigLKr13YCSGI26SPIsDNcwShNfUZgAkr4tCAA), change repo name will get more data after new data uploaded.

But there is a [problem](https://github.com/apache/echarts/issues/18210) in loading external data in share mode for ECharts web site. Still we can copy and paste the code to make it work.

**Comment by frank-zsy** [comment]
According to the response from ECharts community, they can not host external data charts. So we can use CodePen to generate the demos, like [Active dates and times](https://codepen.io/frank-zsy/pen/jOpQdZZ). Change repo name will display data for different repos.

**Comment by frank-zsy** [comment]
A boxplot for issue resolution duration metric by ECharts K-line component https://codepen.io/frank-zsy/pen/VwBqwaP

**Comment by frank-zsy** [comment]
[Issue open/close status](https://codepen.io/frank-zsy/pen/mdjaZMw), using stack bar so the bottom of each red bar is remaining issues count in the repo.

**Comment by will-ww** [comment]
So cool~

**Comment by frank-zsy** [comment]
As PR #1179  #1181 merged, this issue should be closed.
