### ISSUE TITLE
[Feature] downstream apps want to know which repos/users have metric files generated for them

### ISSUE THREAD

**Issue by tyn1998** [X-lab2017/open-digger#1168]
### Description

Hi, OpenDigger community!

Currently OpenDigger only generates metric data for those active or filtered out, so a lot of repos and users do not have metric files generated for them. As downstream apps, we want to know which ones are data-enabled so many unnecessary data requests can be saved.

For example, whatever the repo or user profile is, Hypercrx now will try to request all metrics for the repo/user. If we are in a public but not active repo like https://github.com/tyn1998/tyn1998.github.io, many 404 errors will be output to the console:

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/32434520/215703850-4412498b-f9a6-4f28-8d70-7c0c25cfbeda.png">

And those errors cannot be catched(actually can be catched but will still be logged into the console) in code so the appearance of them are [inevitable](https://stackoverflow.com/questions/7035466/check-if-file-exists-but-prevent-404-error-in-console-from-showing-up)!

If there can be a way to check if a repo/user is data-enabled, it must be beneficial.

**Comment by frank-zsy** [comment]
@tyn1998 Thanks for reporting this.

In OpenDigger, we decide which repos/users to export by their historical OpenRank value, the code is [here](https://github.com/X-lab2017/open-digger/blob/master/src/cron/tasks/monthly_export.ts#L55-L65).

So currently, we exported 590,858 repos and 379,185 users metrics to OSS, we can generate the list for you, but I am not quite sure how to deliver the data. If we put all the repos and users names into a single file and the file maybe a little bit large, but this is the only way that I can think of to deliver the data to downstream.

Do you have any others idea about this?

**Comment by tyn1998** [comment]
Hi @frank-zsy. Since OpenDigger do not have a service server, I hold the same idea like yours:

- if https://oss.x-lab.info/open_digger/github/{repo_full_name}.json exists, the repo is data enabled
- if https://oss.x-lab.info/open_digger/github/{user_name}.json exists, the user is data enabled

In that way, one file request is still needed and if that file doesn't exist the 404 error is still put to the console. But one error is acceptable for me.

**Comment by frank-zsy** [comment]
This is doable but requires 1 million more files to upload to OSS, if you need a online service to check the data, I think I can develop a server for you. You can request the server to see if the repo or user has data on OSS.

**Comment by tyn1998** [comment]
A well designed service is great, while appending 1 million files seems easier :)

**Comment by frank-zsy** [comment]
OK, I will add the files to export task.

**Comment by frank-zsy** [comment]
@tyn1998 It is quite tricky that for several repos, the logic is not applicable.

The repos are: 

- [openbootball/worldcup](https://github.com/openfootball/worldcup), [openfootball/worldcup.json](https://github.com/openfootball/worldcup.json)
- [fluentassertions/fluentassertions](https://github.com/fluentassertions/fluentassertions), [fluentassertions/fluentassertions.json](https://github.com/fluentassertions/fluentassertions.json)
- [mozilla/contribute](https://github.com/mozilla/contribute), [mozilla/contribute.json](https://github.com/mozilla/contribute.json)

I think you can see the problem here, because there are two repos called `owner/repo` and `owner/repo.json`, we can not use `owner/repo.json` as the file name since it is already a folder. We should find a new way to name the flag file.

**Comment by frank-zsy** [comment]
Or we can still use this method, and the 3 repos above will be effected by the flag rule which is also acceptable for me.

**Comment by tyn1998** [comment]
Oops! How about changing to this way:

- for repos: `owner/repo/meta.json`
- for users: `owner/meta.json`

The meta.json files can be used to store meta datas for repos and users later.

**Comment by frank-zsy** [comment]
Of course, I will update the logic and I can add `update_at` with timestamp into the meta file.

**Comment by frank-zsy** [comment]
@tyn1998 The data has been updated.
