### ISSUE TITLE
[Doc] Add more website docs for implemented metrics

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger#1183]
### Description

As xiaoya opened the issue #1180 , and I add an example [page](http://www.x-lab.info/open-digger/#/metrics/openrank) in OpenDigger website for OpenRank index.

We can add more docs about the metrics and indices we implemented in OpenDigger. The page content should contain:

- The badges about the type( Metric, Index or Network), from (X-lab, CHAOSS), for ( Repo, Developer)
- The definition section for description
- The code section to provide links
- [Optional]The parameters section to show how the parameters are set for the exported data
- CodePen demo section to provide a playground to show how to consume the data

All the CodePen demos are in the README file. We can embed them in the page directly with editable mode enabled.

**Comment by frank-zsy** [comment]
I think we should modify the structure of the doc, CHAOSS metric docs could be used as reference.

- The first section is badge, like type, from and for
- The `Description` section about what the metric is about
- Add an `Objectives` section to show what if the metric for and how to use it
- `Data` section about how to retrieve the data and the data structure
- Use `Implementation` section rather than `Code` to add details about the implementation like `code`, `note` and `parameters`
- CodePen demo as a playground.

WDYT, @xiaoya-yaya @xgdyp

**Comment by xiaoya-yaya** [comment]
Agreed. Should we apply this structure to all the metrics, each as an exclusive page?

**Comment by frank-zsy** [comment]
> Agreed. Should we apply this structure to all the metrics, each as an exclusive page?

I think so, we could updated the exist pages first to see whether this is good enough, change structure when all the docs finished will be lots of work.

**Comment by frank-zsy** [comment]
closed by https://github.com/X-lab2017/open-digger-website/issues/11
