### ISSUE TITLE
Add head_ref and base_ref for pull request events in gh_events scheme

### ISSUE THREAD

**Issue by tisonkun** [X-lab2017/open-digger#1216]
### Description

ClickHouse dataset provides `head_ref` and `base_ref` columns: https://ghe.clickhouse.tech/#download-the-dataset

I found one use case that we can use these columns to separate PRs target to different branches. Thus, I suggest to add these two column in the gh_events scheme.

cc @frank

**Comment by frank-zsy** [comment]
Of course, we can add these two columns, my fault to ignore the ref data which is also quite useful. I will update the scheme after OpenRank updated after 2023.2.

/self-assign

**Comment by frank-zsy** [comment]
@tisonkun The new columns has been added in the ClickHouse instance, `pull_base_ref` and `pull_head_ref` have been added as while as `pull_head_repo_id` and `pull_head_repo_name` to indicate where the pull request comes from.

**Comment by tisonkun** [comment]
Thank you!
