### ISSUE TITLE
[suggestions] offer a Chinese verson of README

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/open-digger#1228]
### Description

I suggest adding a Chinese version of README and OpenDigger's advantages and so on.

**Comment by frank-zsy** [comment]
Actually we have Chinese version README in docs folder and on our website, but the content is too old and not identical with English version. https://github.com/X-lab2017/open-digger/blob/master/docs/zh-cn/README.md

Developers welcome to add more details to the Chinese version file to make it sync with the English version README.

**Comment by yanchaomei** [comment]
Hi, I am new here, maybe I can have a try?

**Comment by xgdyp** [comment]
Sure！



---- Replied Message ----
| From | ***@***.***> |
| Date | 03/10/2023 21:46 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [X-lab2017/open-digger] [suggestions] offer a Chinese verson of README (Issue #1228) |

Hi, I am new here, maybe I can have a try?

**Comment by frank-zsy** [comment]
@yanchaomei Yes, of course. You can use `/self-assign` in issue comment to claim this issue.
