### ISSUE TITLE
[Feature] 帮忙将以下项目添加到ChatGPT

### ISSUE THREAD

**Issue by xueqidove** [X-lab2017/open-digger#1233]
### Description

https://github.com/dataease/dataease
https://github.com/jumpserver/jumpserver
https://github.com/metersphere/metersphere
https://github.com/halo-dev/halo

**Comment by tyn1998** [comment]
Hi @xueqidove, please visit https://github.com/hypertrons/hypertrons-crx/issues/609 and make the request there :)

**Comment by xueqidove** [comment]
ok
