### ISSUE TITLE
[Label Data] Add new org (1Panel-dev) to FIT2CLOUD

### ISSUE THREAD

**Issue by maninhill** [X-lab2017/open-digger#1234]
### Label

FIT2CLOUD

### Type

Company

### Repos/Orgs/Users

- 1Panel-dev

### Other information

https://1panel.cn/

**Comment by xgdyp** [comment]
1Panel-dev/1Panel

**Comment by xgdyp** [comment]
515647260

> 1Panel-dev/1Panel

515647260
