### ISSUE TITLE
[Bug] Data information is missing for two month of the project

### ISSUE THREAD

**Issue by Nliver** [X-lab2017/open-digger#1235]
### Current Behavior

stoneatom/stonedb, the data of January is normal, but some indicators of February data do not exist. I checked that OpenDigger did not provide the data of February

https://oss.x-lab.info/open_digger/github/stoneatom/stonedb/technical_fork.json

![63d4ca2998b49b6171e5fd1ec5ee034](https://user-images.githubusercontent.com/34496563/226567951-ddf4a83b-b857-4d70-b580-dbb0c04058d8.jpg)

### Expected Behavior

Fill in the missing monthly data information~

### Any Additional Comments?

Check why the data is missing?

**Comment by xgdyp** [comment]
Hi, thanks for your feedback. I'll use github API to recheck the data

**Comment by xgdyp** [comment]
I checked this metric by github api and fork nums in `2022-12` and `2023-01` are all correct. 
And it should have 11 forks in `2023-02`, so is it caused by some unexpected bug when exporting data. 
Could we export this repo again? @frank-zsy

**Comment by frank-zsy** [comment]
This may be caused by an upload bug by OSS CLI tools, I will upload all the data next month.

**Comment by tyn1998** [comment]
Hi @Nliver, I believe the data exporting process has not been finished yet 😆 . Maybe you could forced refresh the page to fetch the latest data (if it is ready now)

related PR: https://github.com/hypertrons/hypertrons-crx/pull/635

**Comment by Nliver** [comment]
> Hi @Nliver, I believe the data exporting process has not been finished yet 😆 . Maybe you could forced refresh the page to fetch the latest data (if it is ready now)
> 
> related PR: [hypertrons/hypertrons-crx#635](https://github.com/hypertrons/hypertrons-crx/pull/635)

so now the merger is done? the data still doesn't seem to be there. It shows 0~

**Comment by tyn1998** [comment]
<img width="1715" alt="image" src="https://user-images.githubusercontent.com/32434520/229707301-339a9432-8ae6-47e0-955a-862c08b024bd.png">

Please disable cache and refresh the page, then the data should show.

Hi @frank-zsy, I examined the HTTP response headers of the OSS files the other day, and at the moment no cache control rule is employed, which makes browsers implicitly use [heuristic cache](https://paulcalvano.com/2018-03-14-http-heuristic-caching-missing-cache-control-and-expires-headers-explained/) as caching strategy.

I think we should use an explicit cache rule like the [expires header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expires).

**Comment by tyn1998** [comment]
FYI:

<img width="1724" alt="image" src="https://user-images.githubusercontent.com/32434520/229709052-99efded9-446d-49fc-b675-1ff1dd6af70c.png">

**Comment by frank-zsy** [comment]
@tyn1998 Thanks for the important input, I will check the setting of the OSS server side.

**Comment by frank-zsy** [comment]
@tyn1998 I will use `Cache-Control: no-cache` rather than `expires` header as the cache control policy. But there is no tools to set the settings at once, so I need to modify the upload script to set the header on uploading procedure and upload the data again.

Still the file in my local env is fine but not uploaded to OSS this time too, I assume this is a potential bug of ossutils CLI tool.

**Comment by tyn1998** [comment]
`no-cache` can solve our problem since it makes browsers always check if the HTTP response is out of date(i.e. revalidation). But in my view, those extra HTTP requests for revalidation are redundant and cost much and slow down the application, because generally OpenDigger only exports data in the start of a month, which means data files won't change during a month hence most HTTP requests for revalidation are meaningless if we use `no-cache` as the cache strategy.

That is why I am in favor of `expires`. If we set `expires` to `2023.5.2`, the HTTP response can remain reusable until the expired day comes. After it expires, the browser marks it stale and then make extra revalidation requests for every following requests for that resource until a brand new response with `expires` set to `2023.6.2` is received.

What do you think? @frank-zsy

**Comment by frank-zsy** [comment]
@tyn1998 Great idea, I didn't think of that, this makes sense a lot.

**Comment by Nliver** [comment]
@frank-zsy @tyn1998 So is this problem solved? Is there anything I can do for you? Your open source tool is very good, hopefully can restore the normal data ~

**Comment by Nliver** [comment]
> <img alt="image" width="1715" src="https://user-images.githubusercontent.com/32434520/229707301-339a9432-8ae6-47e0-955a-862c08b024bd.png">
> 
> Please disable cache and refresh the page, then the data should show.
> 
> Hi @frank-zsy, I examined the HTTP response headers of the OSS files the other day, and at the moment no cache control rule is employed, which makes browsers implicitly use [heuristic cache](https://paulcalvano.com/2018-03-14-http-heuristic-caching-missing-cache-control-and-expires-headers-explained/) as caching strategy.
> 
> I think we should use an explicit cache rule like the [expires header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expires).

I've tried that, but it doesn't seem to be working

![image](https://user-images.githubusercontent.com/34496563/232179651-c1db36d9-8a65-4411-b018-4c88d0966aae.png)

I checked this API link（https://oss.x-lab.info/open_digger/github/stoneatom/stonedb/technical_fork.json），there's still no data for February and March on this interface, so I guess just uncaching probably won't work?

**Comment by frank-zsy** [comment]
@Nliver I have updated the data for this repo alone. It is very expensive to update all the data again and set headers make this even more expensive. So I will update other files next month.

![image](https://user-images.githubusercontent.com/8512426/233235920-532075e7-efee-44ba-a0cb-359fb9950d82.png)

**Comment by Nliver** [comment]
> @Nliver I have updated the data for this repo alone. It is very expensive to update all the data again and set headers make this even more expensive. So I will update other files next month.
> 
> ![image](https://user-images.githubusercontent.com/8512426/233235920-532075e7-efee-44ba-a0cb-359fb9950d82.png)

oh! thanks a lot, i got it~
