### ISSUE TITLE
[potential label data] Generative AI OSS

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-digger#1249]
### Description

For Generative AI OSS, this article may provide the label data: 

https://www.decibel.vc/content/launching-the-generative-ai-open-source-genos-index

**Comment by frank-zsy** [comment]
This is a great label data for AI sub tech area.

**Comment by will-ww** [comment]
Anybody interested in put this kind of label data into OpenDigger? @xgdyp @Zzzzzhuzhiwei

**Comment by Zzzzzhuzhiwei** [comment]
> Anybody interested in puting this kind of label data into OpenDigger? @xgdyp @Zzzzzhuzhiwei

I would like to put this kind of label data into OpenDigger~

**Comment by will-ww** [comment]
> > Anybody interested in puting this kind of label data into OpenDigger? @xgdyp @Zzzzzhuzhiwei
> 
> I would like to put this kind of label data into OpenDigger~

Great, thanks~

**Comment by frank-zsy** [comment]
closed by #1251
