### ISSUE TITLE
[Docs] add a row of `activity_details` to the table in README

### ISSUE THREAD

**Issue by tyn1998** [X-lab2017/open-digger#1256]
### Description

In #1187 and #1207, @frank-zsy added support for exporting activity_details.json for repos. The amazing data seems to be forgotten to put in [the README table](https://github.com/X-lab2017/open-digger#for-repos). 😆 I will make a codepen demo then update both the README and the official website docs. 

A data link: https://oss.x-lab.info/open_digger/github/X-lab2017/open-digger/activity_details.json

**Comment by xgdyp** [comment]
hi, can you help fix a typo ?
<img width="879" alt="image" src="https://user-images.githubusercontent.com/37795442/232285517-8c69fd6e-e4c2-4770-bd86-3e26dfb22941.png">
I think we can improve it with user `login name` or `user login` .

**Comment by tyn1998** [comment]
sure :)

**Comment by frank-zsy** [comment]
@tyn1998 I think I just bring open-digger-bot to life again, could you try self assign again to see if it works as expected.

**Comment by frank-zsy** [comment]
OMG, open-digger-bot received the event message but not proceed the component properly, I will checkout why.

**Comment by frank-zsy** [comment]
@tyn1998 open-digger-bot finally back to life again.
