### ISSUE TITLE
[Feature] Tools like 'Star History' is interesting

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-digger#1263]
### Description

When more and more community use OpenDigger metrics to how the development of the community. For example, see below:

![652949fb310fd85be0f9d63c4c00811](https://user-images.githubusercontent.com/15010826/233823209-7f3bf526-b161-4ef3-b979-d5c28b5fb4b8.jpg)

 I think we can provide more convenient way to help developers. For example, the project of [Star History](https://github.com/star-history/star-history),

![image](https://user-images.githubusercontent.com/15010826/233823301-c4092e63-e526-4847-871b-4d3a55fba566.png)

This kind of tool is so funny and help to propagate~

https://star-history.com/#X-lab2017/open-digger&Date

**Comment by frank-zsy** [comment]
Actually, with the `stars` metrics produced by OpenDigger, we can easily generate the star history chart just like CodePen demo: https://codepen.io/frank-zsy/pen/MWBdpNg?type=stars

![image](https://user-images.githubusercontent.com/8512426/233889668-bfcbf8c1-d52f-453d-a5ed-f5bd86f5229b.png)

If we change the repo name of the code, then we can get other repos data, like DataEase:

![image](https://user-images.githubusercontent.com/8512426/233889863-f8e00616-9b57-4123-98b1-e7d5aa4f6acf.png)

The only difference is that we only have data points for every month and not up-to-date until every month ends, but the trending is identical.

I am not sure what feature should we support in OpenDigger than the data right now?

**Comment by frank-zsy** [comment]
Similar functionality can be found on OpenDigger website now: https://open-digger.cn/docs/user_docs/metrics/playground
