### ISSUE TITLE
[OSPP2023] Data Quality Assurance & Metrics Explanation by case

### ISSUE THREAD

**Issue by xgdyp** [X-lab2017/open-digger#1266]
### Description

During the development of indicators, we need to verify whether the written sql gets the correct query results.Our previous approach was to select a repo and compare the data manually. At the same time, sometimes the data is missing, and we are often not sure whether our implements are wrong or the data is abnormal. This approach is inefficient and error-prone.

So we need some DQA mechanism to finish data-check and metric check automatically.

Further more, I think we can add a dataset and using this for metrics explanation.
e.g. the result of one metric runs on this dataset is 10.
and we can clearly understand which records make this metric 10, and display these records

references:
https://help.aliyun.com/document_detail/116897.html

**Comment by frank-zsy** [comment]
As we already add a simple test framework for Node.js kernel in #1127 , I think we can expand the test to more detailed data.

The online test server contains data for whole `google` in 2015 and 2016, so we can use the data to generate a test static dataset for all the metrics:

- For single repo and for whole org
- For every month, quarter and year
- Group by different types

So we can use the static dataset for Node.js and Python kernel test for all kinds of queries with all kinds of configs, and the result should be identical.

**Comment by yanchaomei** [comment]
Hi, I'm very interested in this project. Is there someone currently applying for the project or working on it? Also, would it be possible to contact via email or WeChat for further communication?

**Comment by Zzzzzhuzhiwei** [comment]
I have relevant experience with Opendigger metrics, and I have a high interest in this project and hope to contribute my efforts. I really hope to get the chance to participate in this project on OSPP. ^ ^

**Comment by dwxa** [comment]
I'm very interested in this project and I have relevant experience in data warehouse and data analysis and get a start on this project. Hope to have a chance to develop this project in OSPP.

**Comment by frank-zsy** [comment]
@yanchaomei @Zzzzzhuzhiwei @dwxa Thanks for the interest in this issue, you can submit your application on the OSPP platform, if you have any questions about this task, just comment here and I will discuss with you guys about the details.

**Comment by Lllllolita** [comment]
I am very interested in this project and hope to contribute my own efforts. I am researching data mining and data warehousing. I hope to have the opportunity to apply for this project in OSPP.

**Comment by frank-zsy** [comment]
@Zzzzzhuzhiwei As the [CI script](https://github.com/X-lab2017/open-digger/blob/38f125f47d6e444f495cbdd52396fb04874bf6c1/package.json#L17) shows, the public readonly CI database is http://106.15.39.211:8123 with `default` as user name and no password.

You can generate as detailed metrics data as possible from the database as the verification data for test script first. Like all the metrics implemented by month, quarter and year, and inject label data to get result for company, technical area. And also different ordering and precision level.

Then we can use the data in CI test to verify the OpenDigger scripts.

**Comment by Zzzzzhuzhiwei** [comment]
> @Zzzzzhuzhiwei As the [CI script](https://github.com/X-lab2017/open-digger/blob/38f125f47d6e444f495cbdd52396fb04874bf6c1/package.json#L17) shows, the public readonly CI database is http://106.15.39.211:8123 with as user name and no password.`default`
> 
> You can generate as detailed metrics data as possible from the database as the verification data for test script first. Like all the metrics implemented by month, quarter and year, and inject label data to get result for company, technical area. And also different ordering and precision level.
> 
> Then we can use the data in CI test to verify the OpenDigger scripts.

Thank you very much. I will first use data for whole in 2015 and 2016 to obtain the metrics implemented by month, quarter and year. I will also ensure that the data includes various ordering and precision levels to test the OpenDigger scripts.

**Comment by frank-zsy** [comment]
@Zzzzzhuzhiwei How is your progress now?

**Comment by Zzzzzhuzhiwei** [comment]
> @Zzzzzhuzhiwei How is your progress now?

Now I finished data-check and metric check of two metrics: issuesNew and issuesClosed. I get the data from GitHub REST API, and compare the data from open-digger. I choose the data of opendigger last month. 

![image](https://github.com/X-lab2017/open-digger/assets/115639837/eb933283-c352-4ae9-9a85-1efb84c40988)
From the image, it can be seen that the number of open issues obtained from the API is equal to the value obtained from the opendigger indicator. However, the number of closed issues varies.
![image](https://github.com/X-lab2017/open-digger/assets/115639837/7dc01d53-ad97-4648-b9da-bf89162f438d)
This is the data obtained by the open digger, and it can be seen that the data with issue numbers 1300, 1312 and 1318 are missing.

**Comment by frank-zsy** [comment]
Here is a misunderstanding, you don't really need to fetch the data by GitHub API, you should still obtain the data from the test ClickHouse instance since the log data may not exactly identical with the online data.

The purpose for this task is that:
- You should generated the metrics data from the ClickHouse instance manually to make sure the data is correct in ClickHouse.
- We will add the data result in OpenDigger for test, so the scripts in OpenDigger should generate the same results as the data you provide.
- Any further code change should not change the result of the existing metrics.

Am I clear here?

**Comment by Zzzzzhuzhiwei** [comment]
So, I first generate different metric results with different granularity on the test dataset. Then write a script to obtain these indicator data. Every time the code changes and PR is merged, compare whether the two are the same. Is my current understanding correct？

**Comment by frank-zsy** [comment]
Yes, actually you could just add these data into OpenDigger repo first, we can use the data in the unit test. But you should make sure the data is correct in the first place, so try not to use current OpenDigger API to get the data.

**Comment by Zzzzzhuzhiwei** [comment]
> Yes, actually you could just add these data into OpenDigger repo first, we can use the data in the unit test. But you should make sure the data is correct in the first place, so try not to use current OpenDigger API to get the data.

hi @frank-zsy, I have a question, Does "Try not to use the current OpenDigger API to get the data" mean retrieve the metric data from the database using SQL, or through other better ways.

**Comment by frank-zsy** [comment]
I mean you should use ClickHouse query to get the data rather than use OpenDigger API since I am not sure the current OpenDigger API can return correct results for all options right now.

**Comment by Zzzzzhuzhiwei** [comment]
I first choose the metric 'issueClosed'
the first picture is that I get the data by using ClickHouse query.

![image](https://github.com/X-lab2017/open-digger/assets/115639837/1e875cf2-c122-4497-8016-c9a31a85d220)
the two pictures are the data by python kernel and js kernel. 
I set 'limit : 3' , but python kernel return 4 results.  the python kernel data of 'google/ExoPlayer' is different from the js kernel data and  the data by using ClickHouse query. The data of JS is consistent with the data of using ClickHouse query.

![image](https://github.com/X-lab2017/open-digger/assets/115639837/bb6acc11-4566-4118-adc1-34d66e6276f4)
![image](https://github.com/X-lab2017/open-digger/assets/115639837/82e2c14c-4db6-4135-adc8-dffb41f15b0a)

**Comment by lhbvvvvv** [comment]
After the initial refactoring of the python kernel in #1346, the python/js inconsistencies mentioned by @Zzzzzhuzhiwei  should be fixed.

**Comment by Zzzzzhuzhiwei** [comment]
| ![Image 1](https://github.com/X-lab2017/open-digger/assets/115639837/63e50a7c-c114-4dca-96bc-5c9ab8777b8b) | ![Image 2](https://github.com/X-lab2017/open-digger/assets/115639837/caa72f4b-7408-4978-a111-d83cbc861fb6) |
| --- | --- |
| Image 1 | Image 2 |



Because there are many repositories that don't decline the PR , their metric 'changeRequestsAcceptanceRatio' is 1. I set 'limit' is 3, and 'order' is 'DESC' , however the result is random. There is no definite result.

**Comment by frank-zsy** [comment]
@Zzzzzhuzhiwei You could open a PR first, and add the data you retrieved. So we can discuss the details in the PR.

**Comment by frank-zsy** [comment]
> Because there are many repositories that don't decline the PR , their metric 'changeRequestsAcceptanceRatio' is 1. I set 'limit' is 3, and 'order' is 'DESC' , however the result is random. There is no definite result.

This really is a problem, you could open an issue about this, maybe we can return the result order by ratio first and if the ratio is equal, we can use accepted_count as the secondary order key.

**Comment by Zzzzzhuzhiwei** [comment]
| ![Image 1](https://github.com/X-lab2017/open-digger/assets/115639837/24cc0f05-8d9a-44f5-af76-50e2b8adaef5) | ![Image 2](https://github.com/X-lab2017/open-digger/assets/115639837/0c85695b-54e5-4ed8-97a8-b1f0ebd48f17) | ![Image 3](https://github.com/X-lab2017/open-digger/assets/115639837/46c433fc-4248-4d63-95e3-d3fb54803b38) |
| --- | --- | --- |

I change `limitoption` and `groupby` , however, the results do not change.

**Comment by frank-zsy** [comment]
The options field should be `limitOption` and `groupBy`, it is case sensitive.

**Comment by Zzzzzhuzhiwei** [comment]
> it is case sensitive.

Thank you! and I can do it now.

![image](https://github.com/X-lab2017/open-digger/assets/115639837/f62a1e8a-ae53-4433-86e7-57b97bac0b11)

The total number of Google/ExoPlayer shown in the picture is 1568, and the data for March and April 2015 were 0. 

![image](https://github.com/X-lab2017/open-digger/assets/115639837/6944fd64-d3dc-43be-a201-630c949d5303)

however, I write SQL to query from Clickhouse, and there are a total of 36 pieces of data.


I appreciate any help or suggestions you can provide.

**Comment by frank-zsy** [comment]
Close issue since OSPP task has finished.
