### ISSUE TITLE
[Feature] CommitCommentEvent records in opensource.gh_events may need a commit sha to retrieve the parent nodes

### ISSUE THREAD

**Issue by birdflyi** [X-lab2017/open-digger#1268]
### Description

CommitCommentEvent records in opensource.gh_events has related columns:

|id| type| action| actor_id| actor_login| repo_id| repo_name| org_id| org_login| created_at| ...| body|...| commit_comment_id| commit_comment_author_id| commit_comment_author_login| commit_comment_author_type| commit_comment_author_association| commit_comment_path| commit_comment_position| commit_comment_line| commit_comment_created_at| commit_comment_updated_at|
|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|
|28197255023|CommitCommentEvent|added|87379|lucabelluccini|507775|elastic/elasticsearch|6764390|elastic|2023-04-04 14:53:23|...|Hello @abdonpijpelink and @ramdaspotale \n\nI have few comments.\n\nThe changes added here are incorrect.\nThey lead to malfunctioning Stack Monitoring data or to be completely ignored.\n\n1) The new index templates DO NOT MERGE together. [Index Templates doc](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-template.html).\nIf you set the index template as in the docs, the default `.monitoring-*` Index Templates will be ignored, leading to indices with no mappings.\nCustomizing the index template for `.monitoring` indices is not possible until https://github.com/elastic/elasticsearch/issues/84149 is solved.\n\n2) The built in index templates are installed by Elasticsearch itself, they do not rely on Metricbeat.\n|...|107503652|87379|lucabelluccini|User|CONTRIBUTOR|""|""|""|2023-04-04 14:53:23|2023-04-04 14:53:23|
|28197602033|CommitCommentEvent|added|9715543|abdonpijpelink|507775|elastic/elasticsearch|6764390|elastic|2023-04-04 15:04:47|...|Thanks @lucabelluccini . I will revert this change.|...|107505561|9715543|abdonpijpelink|User|CONTRIBUTOR|""|""|""|2023-04-04 15:04:47|2023-04-04 15:04:47|

The commit_comment_id 107503652 relates to https://github.com/elastic/elasticsearch/commit/8218c473d3eb9fdbc0ec2b16eddb49eaab2590ae#commitcomment-107503652 .
There are 2 comments on commit 8218c47. However, without commit sha 8218c47 or 8218c473d3eb9fdbc0ec2b16eddb49eaab2590ae，it is really hard to **Retrieve** the parent node or  **Concatenate Web Page Address** with commit_comment_id 107503652.
I'd like to know if there is a way to get commit sha like 8218c473d3eb9fdbc0ec2b16eddb49eaab2590ae for each commit comment?

**Annotations**
---
**Case SQL**: SELECT * FROM opensource.gh_events WHERE created_at between '2023-04-01 00:00:00' and '2023-04-10 00:00:00' and repo_name='elastic/elasticsearch' and type='CommitCommentEvent' limit 2;

**Retrieve**: 
Parent node id as P, This node id as T, Child node id as C
- 'PullRequestEvent' related columns: issue_id (P), pull_merge_commit_sha (T), ...
- 'PullRequestReviewEvent': pull_merge_commit_sha (P), pull_review_id (T), ...
- 'PullRequestReviewCommentEvent': pull_review_id (P), pull_review_comment_id (T), ...

The relations between 'PullRequestEvent', 'PullRequestReviewEvent' are linked by pull_merge_commit_sha, and the relations between 'PullRequestReviewEvent', 'PullRequestReviewCommentEvent' are linked by pull_review_id. Hence there exists an event dependency based retrieval path among them.

**Concatenate Web Page Address**: 
schema pattern + arguments value dict
e.g. `https://github.com/elastic/elasticsearch/commit/8218c473d3eb9fdbc0ec2b16eddb49eaab2590ae#commitcomment-107503652` can be concatenated by 
- schema pattern: `https://github.com/{repo_name}/commit/{commit_sha}#commitcomment-{commit_comment_id}`
- arguments value dict: `{"repo_name": "elastic/elasticsearch", "commit_sha":"8218c473d3eb9fdbc0ec2b16eddb49eaab2590ae", "commit_comment_id":"107503652"}`

**Comment by frank-zsy** [comment]
There actually is a `commit_sha` in the original log data, but I just delete the data because commit SHA is a quite large part of data just smaller than body in GitHub event log data. Since this is necessary to relate commit comment to a certain commit and can be used to make more relationships, so I will add this column along with pull request base head and ref as #1216 described.

The new schema will apply to our new ClickHouse instance as described in https://github.com/X-lab2017/open-wonderland/issues/275 .

**Comment by frank-zsy** [comment]
@birdflyi `commit_comment_sha` column has been added in the ClickHouse instance.

**Comment by birdflyi** [comment]
Notes: 
1. The patterns of commitcomment links and the Markdown display format of commitcomment links on github websites: 

- `PullRequestEvent` type Parent node:
  `https://github.com/{repo_name}/commit/{commit_sha}#r{commit_comment_id}` -> `{repo_name}@{commit_sha_abbr}#r{commit_comment_id}`
  arguments value dict: `{"repo_name": "elastic/elasticsearch", "commit_sha":"c720cdbbbf175b0dc07a70a8332038e0d1751eb6", "commit_comment_id":"111001100", "commit_sha_abbr":"c720cdb"}`
  e.g. https://github.com/elastic/elasticsearch/commit/c720cdbbbf175b0dc07a70a8332038e0d1751eb6#r111001100. 

- `PushEvent` type Parent node:
  `https://github.com/{repo_name}/commit/{commit_sha}#commitcomment-{commit_comment_id}` -> `{repo_name}@{commit_sha_abbr}#commitcomment-{commit_comment_id}`
  arguments value dict: `{"repo_name": "elastic/elasticsearch", "commit_sha":"8218c473d3eb9fdbc0ec2b16eddb49eaab2590ae", "commit_comment_id":"107503652", "commit_sha_abbr":"8218c47"}`
  e.g. https://github.com/elastic/elasticsearch/commit/9ad91f20e5cf586254e04a5612ea795229da94f5#commitcomment-86357466 or https://github.com/elastic/elasticsearch/commit/8218c473d3eb9fdbc0ec2b16eddb49eaab2590ae#commitcomment-107503652 used above.

2. The **`commit_comment_sha` column** added in the ClickHouse instance is related to the **commit sha union column** of [`pull_merge_commit_sha`, `push_head`], The relationship between them is **1:1**, however, the relationship between the records with values in them(records where type in `CommitCommentEvent` and records where type in [`PullRequestEvent`, 'PushEvent']) is **m:1**. In other words, many `CommitCommentEvent` type records identified by different `commit_comment_id` values, can share one same `commit_comment_sha`, which is come from the `pull_merge_commit_sha` column of `PullRequestEvent` type records(see 2.1) or the `push_head` column of `PushEvent` type records(see 2.1).
  - 2.1 `commit_comment_sha` come from the `pull_merge_commit_sha` column of `PullRequestEvent` type records
    - feature: with a `#r{commit_comment_id}` pattern.
    - case: commit_comment_sha='c720cdbbbf175b0dc07a70a8332038e0d1751eb6', see https://github.com/elastic/elasticsearch/commit/c720cdbbbf175b0dc07a70a8332038e0d1751eb6#r111001100.
      - query commit_comment_sha sql: `select type, pull_merge_commit_sha, push_head, commit_comment_id, commit_comment_sha from opensource.gh_events where repo_name='elastic/elasticsearch' and type='CommitCommentEvent' and commit_comment_sha='c720cdbbbf175b0dc07a70a8332038e0d1751eb6';`
      - query commit_comment_sha result:

      |type|pull_merge_commit_sha|push_head|commit_comment_id|commit_comment_sha|
      |----|----|----|----|----|
      |CommitCommentEvent|""|""|111001100|c720cdbbbf175b0dc07a70a8332038e0d1751eb6|
      |CommitCommentEvent|""|""|112935834|c720cdbbbf175b0dc07a70a8332038e0d1751eb6|
      |CommitCommentEvent|""|""|112939433|c720cdbbbf175b0dc07a70a8332038e0d1751eb6|
      |CommitCommentEvent|""|""|113048794|c720cdbbbf175b0dc07a70a8332038e0d1751eb6|

      - check sql: `select type, pull_merge_commit_sha, push_head, commit_comment_id, commit_comment_sha from opensource.gh_events where repo_name='elastic/elasticsearch' and pull_merge_commit_sha='c720cdbbbf175b0dc07a70a8332038e0d1751eb6';`
      - check result:

      |type|pull_merge_commit_sha|push_head|commit_comment_id|commit_comment_sha|
      |----|----|----|----|----|
      |PullRequestEvent|c720cdbbbf175b0dc07a70a8332038e0d1751eb6|""|0|""|

  - 2.2 `commit_comment_sha` come from the `push_head` column of `PushEvent` type records
    - feature: with a `#commitcomment-{commit_comment_id}` pattern.
    - case: commit_comment_sha='9ad91f20e5cf586254e04a5612ea795229da94f5', see https://github.com/elastic/elasticsearch/commit/9ad91f20e5cf586254e04a5612ea795229da94f5#commitcomment-86357466.
      - query commit_comment_sha sql: `select type, pull_merge_commit_sha, push_head, commit_comment_id, commit_comment_sha from opensource.gh_events where repo_name='elastic/elasticsearch' and type='CommitCommentEvent' and commit_comment_sha='9ad91f20e5cf586254e04a5612ea795229da94f5';`
      - query commit_comment_sha result:

      |type|pull_merge_commit_sha|push_head|commit_comment_id|commit_comment_sha|
      |----|----|----|----|----|
      |CommitCommentEvent|""|""|86357466|9ad91f20e5cf586254e04a5612ea795229da94f5|
      |CommitCommentEvent|""|""|86605878|9ad91f20e5cf586254e04a5612ea795229da94f5|
      |CommitCommentEvent|""|""|86609487|9ad91f20e5cf586254e04a5612ea795229da94f5|

      - check sql: `select type, pull_merge_commit_sha, push_head, commit_comment_id, commit_comment_sha from opensource.gh_events where repo_name='elastic/elasticsearch' and push_head='9ad91f20e5cf586254e04a5612ea795229da94f5';`
      - check result:

      |type|pull_merge_commit_sha|push_head|commit_comment_id|commit_comment_sha|
      |----|----|----|----|----|
      |PushEvent|""|9ad91f20e5cf586254e04a5612ea795229da94f5|0|""|
