### ISSUE TITLE
[Feature] I would like to have an API that gets all the repos that can query metrics, for a login.

### ISSUE THREAD

**Issue by stevending1st** [X-lab2017/open-digger#1270]
### Description

https://github.com/X-lab2017/od-api/issues/39

**Comment by stevending1st** [comment]
> So it is really hard to provide a single interface to return all the data at once.

I also think that is a bad API interface design. It's not what I want, here's what I thought:
If I send a get request: `http://api.x-lab.info/login_name/repos.json`,  I would get a return value similar to the following:
```
["repo1", "repo3"]
```
This means that metrics for `login_name/repo1` and `login_name/repo3` can be queried from the APIs provided by open-digger, but not for `login_name/repo2`.

---

> So right now, if you want to know whether a repo's data has been exported, you can get the meta data file like https://oss.x-lab.info/open_digger/github/X-lab2017/open-digger/meta.json , if the meta file not exists, the repo data is not exported.

This api returns a time(`{"updatedAt":1680421471256}`)

---

> And can you describe more detail about how would you want to use the data?

I want to know more automatically which repos can query metrics for an organization or a person so that I can develop some apps.

**Comment by zhicheng-ning** [comment]
> If I send a get request: `http://api.x-lab.info/login_name/repos.json`, I would get a return value similar to the following:
> 
> ```
> ["repo1", "repo3"]
> ```

I think it's not difficult to verify it. 
For example, there are two repo：[X-Engineer/x-tiktok](https://github.com/X-Engineer/x-tiktok) and [X-Engineer/x-rpc](https://github.com/X-Engineer/x-rpc).
You can send two request like this：
1. http://api.x-lab.info/X-Engineer/x-tiktok/openrank ：return code is `200`
2. http://api.x-lab.info/X-Engineer/x-rpc/openrank ： return code is `404`

So we can confirm that for X-Engineer, the repo x-tiktok can be queried from the APIs provided by open-digger, but repo x-rpc cant.

**Comment by stevending1st** [comment]
> I think it's not difficult to verify it. For example, there are two repos：[X-Engineer/x-tiktok](https://github.com/X-Engineer/x-tiktok) and [X-Engineer/x-rpc](https://github.com/X-Engineer/x-rpc). You can send two requests like this：
> 
> 1. http://api.x-lab.info/X-Engineer/x-tiktok/openrank ：return code is `200`
> 2. http://api.x-lab.info/X-Engineer/x-rpc/openrank ： return code is `404`
> 
> So we can confirm that for X-Engineer, the repo x-tiktok can be queried from the APIs provided by open-digger, but repo x-rpc cant.

I also know that the problem can be solved by this way. This seems to be a little trouble.
 
If open-digger provides api, I only need a request to solve the problem. 

Now, however, I need to send a request to GitHub to get a list of projects. Then iterate through the list of projects. 

This increases the complexity of the project.

**Comment by frank-zsy** [comment]
@stevending1st I think it is fair enough to add the repo list into the meta data of an organization, and also, as issue #1269 described, we can also add label info into the meta data too. So the meta data may like below:

```json
{
  "updated_at": 1680421471256,
  "repos": [{
    "id": 111111,
    "name": "some-repo"
  }],
  "labels": [{
    "id": ":technology/ai",
    "name": "AI"
  }]
}
```

The above structure is meta data for organization and for repo meta data, no `repos` field in it.

Does this make sense to you and solve your problem?

**Comment by stevending1st** [comment]
> @stevending1st I think it is fair enough to add the repo list into the meta data of an organization, and also, as issue #1269 described, we can also add label info into the meta data too. So the meta data may like below:
> 
> ```json
> {
>   "updated_at": 1680421471256,
>   "repos": [{
>     "id": 111111,
>     "name": "some-repo"
>   }],
>   "labels": [{
>     "id": ":technology/ai",
>     "name": "AI"
>   }]
> }
> ```
> 
> The above structure is meta data for organization and for repo meta data, no `repos` field in it.
> 
> Does this make sense to you and solve your problem?

Sorry, I don't understand how the method you said solves my problem.

Let me describe my requirements in detail to help you better understand why I want to add this feature.

First, let me tell you the user story. I want to generate a report based on an owner. Yes, **you only need to enter an owner here.** Then, it is necessary to get the metrics of all the repositories of this owner. This requires us to get all the repository IDs that are indexed for this owner.

In the previous discussion, we discussed three scenarios, one is to get all the repositories of the owner through the GitHub API, and then determine whether it is included or not through the return status of the open-digger API request one by one. There are many disadvantages with this scheme, such as the GitHub API needs to configure tokens for free access; Excessive network requests cause waste of resources; The requirements for writing programs become higher, and many exceptions need to be handled additionally. Querying the list of repositories by tags is a manual process, which makes a lot of information untimely and inaccurate.If you're lucky enough to implement this feature, then all of this will be easy!

Secondly, I think that this list of included repositories itself is an indicator that has certain reference value for the owner.

Thanks for your reply.

**Comment by frank-zsy** [comment]
Still, I think you need the repository list of an owner, both organization and user I assume. So the meta data I provide will give you the list.

Like if you request the meta data of `X-lab2017` org, maybe a URL like https://oss.x-lab.info/open_digger/github/X-lab2017/meta.json , then the return content will be something like:

```json
{
  "updated_at": 1680421471256,
  "repos": [{
    "id": 111111,
    "name": "X-lab2017/open-digger"
  }]
}
```

So you know that there will be a repo called `X-lab2017/open-digger` which is indexed by OpenDigger and you can request metrics data for this repo.

I think this really solve your problem, tell me if I misunderstand you.

**Comment by stevending1st** [comment]
> Still, I think you need the repository list of an owner, both organization and user I assume. So the meta data I provide will give you the list.
> 
> Like if you request the meta data of `X-lab2017` org, maybe a URL like https://oss.x-lab.info/open_digger/github/X-lab2017/meta.json , then the return content will be something like:
> 
> ```json
> {
>   "updated_at": 1680421471256,
>   "repos": [{
>     "id": 111111,
>     "name": "X-lab2017/open-digger"
>   }]
> }
> ```
> 
> So you know that there will be a repo called `X-lab2017/open-digger` which is indexed by OpenDigger and you can request metrics data for this repo.
> 
> I think this really solve your problem, tell me if I misunderstand you.

Thank you, this is really what I need! 

With regard to the repo field, whether repositories other than those observed by open-digger will be listed, if so, you want one more field to distinguish. 

What is the schedule for this feature?

**Comment by frank-zsy** [comment]
@stevending1st I am currently working on this. Will take effect after 6.1 data update procedure.

/self-assign

**Comment by stevending1st** [comment]
> am currently working on this. Will take effect after 6.1 data update procedure.
> 
> /self-assign

Thank you very much!

**Comment by frank-zsy** [comment]
@stevending1st Actually I already deployed the procedure and took effect, you can check the meta files now for org repos and org/repo/user labels in the meta file. Raise new issue if there is any problem as you will.

**Comment by stevending1st** [comment]
> @stevending1st Actually I already deployed the procedure and took effect, you can check the meta files now for org repos and org/repo/user labels in the meta file. Raise new issue if there is any problem as your will.

@frank-zsy  Thank you very much, this is fine. This API also meets my needs.
