### ISSUE TITLE
[sample_data]open-digger/sample_data/README.md

### ISSUE THREAD

**Issue by 318352733** [X-lab2017/open-digger#1274]
### Description

Why is the sample data garbled after import？
![c1b7fed5939ef3e6ff1f7472de837d3](https://user-images.githubusercontent.com/117413703/235302129-0694adfa-f70a-4af6-83d1-95168c665982.jpg)

**Comment by xgdyp** [comment]
Shown here is the text information in issue or pr. And it is raw markdown table format.
