### ISSUE TITLE
[Sample Data] 

### ISSUE THREAD

**Issue by 318352733** [X-lab2017/open-digger#1276]
### Usage

For SODA openDigger Visualize the large screen

### Extract SQL

I want some data to make a visual dashboard of product data analysis, such as user activity, attention, engagement, problem resolution time, etc.

**Comment by xgdyp** [comment]
Hi, you can use our data interface in README.md.
![image](https://user-images.githubusercontent.com/37795442/236091173-5dd64c6a-30d6-4d22-a44d-5a807baf1bec.png)
