### ISSUE TITLE
[lable miss] miss X-lab lable user

### ISSUE THREAD

**Issue by bifenglin** [X-lab2017/open-digger#1286]
### Description

As XSOSI shows that have a user named `springyulu`, but there is no info about him in https://github.com/X-lab2017/open-digger/blob/master/labeled_data/communities/xlab/index.yml

So is this a bug?

**Comment by frank-zsy** [comment]
As we use user id to calculate the result, user login change may lead to this situation. `springyulu`'s former login is `lucky-xmyu` which is in the list. We can fix the comment login name in the config file.

**Comment by Zzzzzhuzhiwei** [comment]
![image](https://user-images.githubusercontent.com/115639837/236773162-84c8f51f-05d3-4da6-b83f-c49b7b9a33cb.png)
His login name is lucky-xmyu, and he has changed his login name.

**Comment by bifenglin** [comment]
OK，This issue has fixed.
