### ISSUE TITLE
[Data truncation] Data too long for column

### ISSUE THREAD

**Issue by 318352733** [X-lab2017/open-digger#1291]
### Description

![image](https://github.com/X-lab2017/open-digger/assets/117413703/3a0b959a-b2f6-43f7-9c36-49a6b0f7914c)
![image](https://github.com/X-lab2017/open-digger/assets/117413703/cd8fff69-305e-4cf8-926e-f594198ac3bd)

In this DDL：“ type                                   Enum8('CommitCommentEvent' = 1, 'CreateEvent' = 2, 'DeleteEvent' = 3, 'ForkEvent' = 4, 'GollumEvent' = 5, 'IssueCommentEvent' = 6, 'IssuesEvent' = 7, 'MemberEvent' = 8, 'PublicEvent' = 9, 'PullRequestEvent' = 10, 'PullRequestReviewCommentEvent' = 11, 'PushEvent' = 12, 'ReleaseEvent' = 13, 'WatchEvent' = 14, 'PullRequestReviewEvent' = 15)”,the database hint is too long, and there are many columns that are null or 0, is something wrong?

**Comment by xgdyp** [comment]
hi. I tested create a new table and export from csv file in datagrip. There's no problem. I think it may casued by dataease. 
@zhicheng-ning have you ever encountered such a problem？

**Comment by zhicheng-ning** [comment]
> have you ever encountered such a problem？

Yes. Here is a solution, just follow the steps @318352733 ：
- required：**Login in your server which has deployed dataeae**
- dataease mysql config：/opt/dataease/conf/dataease.properties
~~~
[root@centos ~]# docker exec -it mysql /bin/bash
bash-4.2# mysql -uroot -p{your-password} 

mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| dataease           |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
5 rows in set (0.00 sec)

mysql> use dataease;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> desc dataset_table_field;
+------------------+---------------+------+-----+---------+-------+
| Field            | Type          | Null | Key | Default | Extra |
+------------------+---------------+------+-----+---------+-------+
| id               | varchar(50)   | NO   | PRI | NULL    |       |
| table_id         | varchar(50)   | NO   |     | NULL    |       |
| origin_name      | longtext      | NO   |     | NULL    |       |
| name             | longtext      | NO   |     | NULL    |       |
| dataease_name    | varchar(255)  | NO   |     | NULL    |       |
| group_type       | varchar(50)   | YES  |     | NULL    |       |
| type             | varchar(255) | YES  |     | NULL    |       |
| size             | int(11)       | YES  |     | NULL    |       |
| de_type          | int(10)       | NO   |     | NULL    |       |
| de_type_format   | int(10)       | YES  |     | NULL    |       |
| de_extract_type  | int(10)       | NO   |     | NULL    |       |
| ext_field        | int(10)       | YES  |     | NULL    |       |
| checked          | tinyint(1)    | NO   |     | 1       |       |
| column_index     | int(10)       | NO   |     | NULL    |       |
| last_sync_time   | bigint(13)    | YES  |     | NULL    |       |
| accuracy         | int(11)       | YES  |     | 0       |       |
| date_format      | varchar(255)  | YES  |     | NULL    |       |
| date_format_type | varchar(255)  | YES  |     | NULL    |       |
+------------------+---------------+------+-----+---------+-------+
18 rows in set (0.00 sec)

mysql> ALTER TABLE dataset_table_field MODIFY type VARCHAR(1000);


~~~

**Comment by zhicheng-ning** [comment]
I suggest the issue title can be changed as 'Data truncation: Data too long for column', so that other contestants can get the solution because they may meet the same problem.
