### ISSUE TITLE
[Feature] When the pull request header starts with [WIP], the PR is not merged.

### ISSUE THREAD

**Issue by stevending1st** [X-lab2017/open-digger#1299]
### Description

https://probot.github.io/apps/wip/

**Comment by frank-zsy** [comment]
Thanks for the advice, it is my fault that I did not notice the WIP tag in PR #1296 , but I think we can use Draft status on GitHub just like PR #1209 .

**Comment by stevending1st** [comment]
Thank for your answer. Does this draft need to be set up by the PR author himself?

**Comment by frank-zsy** [comment]
Yes, draft can be set by author and maintainer at here.

<img width="710" alt="image" src="https://github.com/X-lab2017/open-digger/assets/8512426/35fb18c0-c171-4e7e-8a69-570328fef639">

**Comment by stevending1st** [comment]
> Yes, draft can be set by author and maintainer at here.
> 
> <img alt="image" width="710" src="https://user-images.githubusercontent.com/8512426/241456401-35fb18c0-c171-4e7e-8a69-570328fef639.png">

Thanks for your help！
