### ISSUE TITLE
[Suggestion] Proposal to Start Using Releases for Version Management of Labeled_data and Metrics

### ISSUE THREAD

**Issue by Zzzzzhuzhiwei** [X-lab2017/open-digger#1321]
### Description

I would like to propose the introduction of releases as a version management practice for label data in OpenDigger. As of now, we haven't utilized releases to mark our project milestones or provide structured versions to users. By adopting GitHub releases, we can enhance our development process and improve user experience. Please feel free to share your suggestions.

**Comment by xgdyp** [comment]
hi @Zzzzzhuzhiwei  can you post your current format on this issue first and we can talk about it.

I think we need to help user get labels they need easily.

**Comment by Zzzzzhuzhiwei** [comment]
> hi @Zzzzzhuzhiwei can you post your current format on this issue first and we can talk about it.
> 
> I think we need to help user get labels they need easily.

hi, there are three sheets in this excel file, including github_user, github_repo, github_org.

![image](https://github.com/X-lab2017/open-digger/assets/115639837/b5428636-8d96-41bf-94f2-21999e1b15e9)

![image](https://github.com/X-lab2017/open-digger/assets/115639837/9198c36c-4cc0-4f8e-bfb8-95e268c3c3c2)

![image](https://github.com/X-lab2017/open-digger/assets/115639837/e74fc442-d4cc-4eeb-856c-5758a0cbb1c5)

**Comment by Zzzzzhuzhiwei** [comment]
> hi @Zzzzzhuzhiwei can you post your current format on this issue first and we can talk about it.
> 
> I think we need to help user get labels they need easily.

The modified format is shown in the following figure~
![image](https://github.com/X-lab2017/open-digger/assets/115639837/c60aa8e2-b866-4948-aacf-bcd274c847cd)

**Comment by bifenglin** [comment]
As data demander, I'd like to use `.csv` file.

**Comment by Zzzzzhuzhiwei** [comment]
now there are three sheets in the excel file: github_org, github_repo, data_description.
- 'github_org' contains the information of organizations of conpanies
- 'github_repo' contains the information of repositories of conpanies
- 'data_description' contains the description of column name
![image](https://github.com/X-lab2017/open-digger/assets/115639837/ebdf23c7-5908-4d30-a2b3-27e73770d189)
![image](https://github.com/X-lab2017/open-digger/assets/115639837/ca22caa4-c2b3-4db6-9468-d53f01049ca9)
![image](https://github.com/X-lab2017/open-digger/assets/115639837/e1ad97c3-7ce5-43ea-baf8-f0b585a9e4c7)

**Comment by Zzzzzhuzhiwei** [comment]
Now, the data description sheet has updated. I added an introduction to the content of each sheet,  the relationship with the company, organization, and warehouse, and the adobe sample diagram.
![image](https://github.com/X-lab2017/open-digger/assets/115639837/b691a30a-2cf2-47f1-b93f-53b5e47f4948)
