### ISSUE TITLE
[Feature] Add type for meta data of owner

### ISSUE THREAD

**Issue by stevending1st** [X-lab2017/open-digger#1331]
### Description

I think owner's meta data should add a type field to mark whether the owner is `org` or `user`. 

e.g.
https://[oss.x-lab.info/open_digger/github/X-lab2017/meta.json](https://oss.x-lab.info/open_digger/github/X-lab2017/meta.json)
```
{
    ...
    type: "org“
    ...
}
```

https://[oss.x-lab.info/open_digger/github/stevending1st/meta.json](https://oss.x-lab.info/open_digger/github/stevending1st/meta.json)

```
{
    ...
    type: "user"
    ...
}
```

Although github provides this interface, I still think it's a good feature.

**Comment by frank-zsy** [comment]
Thanks for the advice, this can be done in the monthly export task and I will do that.

/self-assgin

**Comment by frank-zsy** [comment]
The work has been done in #1332 , I will update the data before tomorrow.

But for this month, the type will only added into the accounts with exported repos. So if you get a meta data without `type` and `repos` field, it is a user account.

And for next month, the `user` type will also be added into the user accounts that has exported metrics but no exported repos.

**Comment by stevending1st** [comment]
> The work has been done in #1332 , I will update the data before tomorrow.
> 
> But for this month, the type will only added into the accounts with exported repos. So if you get a meta data without `type` and `repos` field, it is a user account.
> 
> And for next month, the `user` type will also be added into the user accounts that has exported metrics but no exported repos.

This is really good news. Thank you very much for your work.
