### ISSUE TITLE
the results of metric 'changeRequestsAcceptanceRatio'  is random

### ISSUE THREAD

**Issue by Zzzzzhuzhiwei** [X-lab2017/open-digger#1360]
### Description

As mentioned in the issue #1266 ，because there are many repositories that don't decline the PR , their metric 'changeRequestsAcceptanceRatio' is 1. I set 'limit' is 3, and 'order' is 'DESC' , however the result is random. There is no definite result.
![image](https://github.com/X-lab2017/open-digger/assets/115639837/9c5a0281-cc3e-40fd-8d79-a92de391f141)

**Comment by frank-zsy** [comment]
@Zzzzzhuzhiwei Add a secondary order key is quite difficult right now, since this feature will only be used in unit test, I will not implement this one soon.
