### ISSUE TITLE
[Metrics]How to use the provided JSON data？

### ISSUE THREAD

**Issue by jhzhou002** [X-lab2017/open-digger#1366]
### Usage

For SODA openDigger Visualize the large screen

### Extract SQL

In the provided data source top300_metrics, I want to use this json data for visualization, so how does the front end get this data? Is the back end importing the database to create the interface or what?

**Comment by frank-zsy** [comment]
@bifenglin Can you give a guide about this?

**Comment by xgdyp** [comment]
Hi, this is not quite related to OpenDigger itself and you can use JSON data in any way you are familiar with. 

And this issue has been solved through WeChat group so I'll close this issue first.
