### ISSUE TITLE
[question]  How to get quartly data from the monthly data 

### ISSUE THREAD

**Issue by WillemJiang** [X-lab2017/open-digger#1388]
### Description

As I need to generate the quarterly project report,  some metrics can be summarized from the monthly data.  
But it doesn't make sense if we put the index monthly data together for a quarterly index.  
Can we get the index data quarterly from the open digger?

**Comment by frank-zsy** [comment]
@WillemJiang Thanks for mentioning this.

For some simple statistical metrics, we can use monthly data to generate the quarterly data.

Actually according to #1105 , for all the metrics in OpenDigger, we are planning to export quarterly and yearly data as well, but not implemented yet. I will work on this recently so we can easily retrieve quarterly and yearly data in the metrics file too.
