### ISSUE TITLE
[Bug] The README ChangeRequestDemo link is wrong

### ISSUE THREAD

**Issue by WillemJiang** [X-lab2017/open-digger#1397]
### Description

In the README ChangeRequestDemo link is https://codepen.io/frank-zsy/pen/bGjPGxw which shows the big data states, it doesn't show the change request status.

**Comment by frank-zsy** [comment]
That is my fault to modify the pen to big data evolving status, I will change it back soon.

/self-assign

**Comment by frank-zsy** [comment]
The demo has been fixed to show change requests related data.
