### ISSUE TITLE
[Discussion] I hope to donate stevending1st/open-digger-cli to the x-lab2017

### ISSUE THREAD

**Issue by stevending1st** [X-lab2017/open-digger#1430]
### Description

I am very happy to participate in the openSODA competition. Although the competition has ended today, the iteration and update of [the project](https://github.com/stevending1st/open-digger-cli) have not. I hope that the project can continue to be maintained. However, my personal ability and time are limited. If the project can be donated to x-lab, together with other members and contributors in the community, it will benefit the development of the project and openDigger.

This project has the following characteristics compared to other projects. First, the technology stack used here is consistent with openDigger for ease of maintenance. Second, this project implements functionality through plugins, which will reduce the core code.

It is expected that the project will take 6-8 months to be refactored if it needs to be improved to a level that can be donated.

**Comment by tyn1998** [comment]
Hi @stevending1st I watched your presentation on the competition. The KISS style the project adopted is much appreciated. Congratulations!

**Comment by stevending1st** [comment]
> Hi @stevending1st I watched your presentation on the competition. The KISS style the project adopted is much appreciated. Congratulations!

Thank you very much. 
I hope we can maintain the project together and enrich the ecology of OpenDigger.

**Comment by frank-zsy** [comment]
@stevending1st Thanks for the proposal and congrats. Since X-lab is not a legal entity, I think donate to X-lab just mean to transfer the project into X-lab2017 org. You can add me as the admin of your project and I will transfer the project to this org. WDYT?

**Comment by stevending1st** [comment]
> @stevending1st Thanks for the proposal and congrats. Since X-lab is not a legal entity, I think donate to X-lab just mean to transfer the project into X-lab2017 org. You can add me as the admin of your project and I will transfer the project to this org. WDYT?

OK, I'll send out the invitation right away.

**Comment by frank-zsy** [comment]
@stevending1st Thanks, I already accept your invitation but I think right now I only have write access to the repo, to transfer the repo, I need admin access to the repo.

**Comment by stevending1st** [comment]
> @stevending1st Thanks, I already accept your invitation but I think right now I only have write access to the repo, to transfer the repo, I need admin access to the repo.

@frank-zsy Thanks, it seems that you need to transfer the project to your account and you will do other work for you. Thank you.

**Comment by frank-zsy** [comment]
The repo has been transferred to X-lab2017 org, thanks @stevending1st

**Comment by stevending1st** [comment]
> The repo has been transferred to X-lab2017 org, thanks @stevending1st

Thanks for @frank-zsy's helpping!
