### ISSUE TITLE
[🔥🔥🔥 OpenDigger Hackathon] From Idea to  Successful Implementation 

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-digger#1447]
### Description

🔥🔥🔥 各位社区朋友们，我们将在本周末（16、17号两天）在[开放原子开发者大会](https://openatomcon.openatom.cn/)上举办为期两天的 OpenDigger 黑客马拉松互动，欢迎大家参加、交流、爽爽的写代码，从创意到实现~

早几天，我们已经通过[这个帖子](https://github.com/X-lab2017/open-wonderland/issues/338)总结些想法，欢迎大家加入~

![e4f04a6be60a4373903514bbc32de3c](https://github.com/X-lab2017/open-digger/assets/15010826/5beca5c8-3a69-48b5-986a-75fc21af55ce)

预计现场 OpenDigger 项目会有大约 10 支队伍，大家可以在此贴下面组队、交流想法，enjoy 🚀🚀🚀~

相关信息，我们也会在此帖子下面，持续刚需，有什么问题，可以联系 @PureNatural ，作为本次大赛的接头人 💁~

📣📣📣

- **参会指南**：[链接](https://mp.weixin.qq.com/s/6j5ah_Ic799AsFa0UeUeRw)（内含报名通道、大赛地址、交通等信息）
- **微信交流群**：

<div align=center>
<img src="https://github.com/X-lab2017/open-digger/assets/15010826/e4fa9eb3-c56d-496a-8e18-23224105e5b7" width="300px">
</div>

**Comment by PureNatural** [comment]
时间：2023年12月16-17日
地点：江苏·无锡·梁鸿湿地丽笙度假酒店 三水厅
时间表：
<img width="452" alt="image" src="https://github.com/X-lab2017/open-digger/assets/29674550/86227c21-216e-4d6e-9f78-326f72a7e178">
比赛形式：大概3-5人组成一个小组，现场讨论一些关于Opendigger的一些想法，这些想法可以参考[之前列举出来的题目](https://github.com/X-lab2017/open-wonderland/issues/338)，也可以自己再发挥，最后基于这些想法实现一个作品出来。17号下午出最后的比赛结果。

**Comment by will-ww** [comment]
<img width="452" alt="image" src="https://github.com/X-lab2017/open-digger/assets/15010826/b927f901-eeb4-4fd6-b66c-9ac8c0488b6a">

**Comment by frank-zsy** [comment]
黑客松期间的住宿具体是如何安排的啊？是参与者自己订还是统一预订的啊？

**Comment by PureNatural** [comment]
> 黑客松期间的住宿具体是如何安排的啊？是参与者自己订还是统一预订的啊？

我们都是自己订的哈

**Comment by will-ww** [comment]
![image](https://github.com/X-lab2017/open-digger/assets/15010826/c7f33558-4d69-4ef2-9d9d-9215d2b51672)
![image](https://github.com/X-lab2017/open-digger/assets/15010826/5036aec5-1e67-4540-884c-079374872191)
![image](https://github.com/X-lab2017/open-digger/assets/15010826/99462771-8d55-44fc-ae91-bb1a9bc99d53)
