### ISSUE TITLE
[Feature] Solution of implementing the Python kernel

### ISSUE THREAD

**Issue by birdflyi** [X-lab2017/open-digger#1463]
### Description

Should we implement the entire python kernel function or only the python caller interface of the nodejs kernel?

**Comment by frank-zsy** [comment]
This is a good question actually. Right now Node.js kernel and Python kernel are independently implemented which means if any changes applied to Node.js kernel we need to manually migrate the changes to Python kernel. This procedure is quite time consuming.

I think there is an alternative that we can bridge the Node.js implementation into Python kernel.

Which means the Python kernel will only have a very light layer like APIs for requesting data, but when users call the API, actually the underlying layer will redirect to Node.js library to send the real requests to database. In this way, we will not need to maintain two different implementations of OpenDigger interfaces.

**Comment by frank-zsy** [comment]
We can use some libraries like [node_vm2](https://pypi.org/project/node-vm2/) to start a Node.js VM in Python kernel and directly call the Node.js API.

**Comment by birdflyi** [comment]
I can quickly using [node_vm2](https://pypi.org/project/node-vm2/) to implement a python caller layer.
However, Here are some details that may require our attention:
- The [node_vm2](https://pypi.org/project/node-vm2/) has been abandoned, we may need to use [deno_vm](https://github.com/eight04/deno_vm) instead.
- A python caller for Node.js is no longer a python kernel. In order to distinguish it from other Python kernels and to save existing works, I'd like to add another directory named by `pycjs`(which means python caller for js or python connector for js) to implement it.
- Since there is not much interface code, we can discuss whether to save both and how to save both implementation methods after this attempt.

**Comment by frank-zsy** [comment]
- I found deno_vm is not quite active or has lots of stars which means it should be the next version of node_vm2 but not.
- `pycjs` is fine and if this one is stable we can remove old `python` and `python_v2` kernel files since they can be retrieved from Git history.

**Comment by birdflyi** [comment]
According to your suggestion, I've implement a pycjs based on [node_vm2](https://pypi.org/project/node-vm2/) and [deno_vm](https://github.com/eight04/deno_vm)~
Perhaps we should keep the `python` and `python_v2` kernel files for a few weeks before conducting sufficient test on this `pycjs` ~

**Comment by frank-zsy** [comment]
Yes, I agree with you about the old versions.
