### ISSUE TITLE
[Label Data] Add LF AI & Data Foundation label data

### ISSUE THREAD

**Issue by longyanz** [X-lab2017/open-digger#1474]
### Label

LF AI&Data Foundation

### Type

Foundation

### Repos/Orgs/Users

Orgs:
- acumos
- Adlik
- 1chipML
- Trusted-AI
- amundsen-io
- Angel-ML
- artigraph
- Beyond-ML-Labs
- bitol-io
- claimed-framework
- datapractices
- datashim-io
- docarray
- Delta-ML
- DeepRec-AI
- deepcausality-rs
- elyra-ai
- elasticdeeplearning
- odpi
- FlagAI-Open
- feathr-ai
- feast-dev
- FederatedAI
- horovod
- ForestFlow
- flyteorg
- KomputeProject
- kedro-org
- JanusGraph
- intersectional-fairness
- machine-learning-exchange
- ludwig-ai
- lakesoul-io
- kserve
- milvus-io
- MarquezProject
- OpenDataology
- Project-OpenBytes
- onnx
- nnstreamer
- pyro-ppl
- OpenLineage
- securefederatedai
- sapientml
- rwkv
- RosaeNLG
- recommenders-team
- Substra 
- sparklyr
- soajs
- inferenceengine
- xtreme1-io
- tony-framework

**Comment by frank-zsy** [comment]
fix by #1475
