### ISSUE TITLE
[Label Data] Add label data for LF Edge Foundation

### ISSUE THREAD

**Issue by longyanz** [X-lab2017/open-digger#1483]
### Label

 LF Edge Foundation

### Type

Foundation

### Repos/Orgs/Users

- akraino-edge-stack
- project-alvarium
- baetyl
- edgexfoundry
- lf-edge
- fido-device-onboard
- fledge-iot
- nanomq
- nexoedge
- open-horizon
- State-of-the-Edge

**Comment by frank-zsy** [comment]
@longyanz Next time, leave an extra blank line after the last repo or org, then it will be correctly parsed, otherwise it will be mixed with template text.

**Comment by longyanz** [comment]
> @longyanz Next time, leave an extra blank line after the last repo or org, then it will be correctly parsed, otherwise it will be mixed with template text.

Ok, Thanks!
