### ISSUE TITLE
[Label Data] Add label for OpenSSF, Hyperledger, FinOps, O3DE, RISCV foundation

### ISSUE THREAD

**Issue by longyanz** [X-lab2017/open-digger#1488]
### Description

Hi, I want to add label for OpenSSF, Hyperledger, FinOps, O3DE, RISCV foundation.

Label: OpenSSF Foundation
Type: Foundation
Orgs:

- ossf
- guacsec
- gittuf
- repository-service-tuf
- sbomit
- sigstore

Repos:

- coreinfrastructure/best-practices-badge

Label: Hyperledger Foundation
Type: Foundation
Orgs:

- hyperledger-labs 
- hyperledger

Label: FinOps Foundation
Type: Foundation
Orgs:

- finopsfoundation

Label: O3DE Foundation
Type: Foundation
Orgs:

- o3de

Label: RISCV Foundation
Type: Foundation
Orgs:

- riscv
- riscv-collab
- riscv-non-isa
- riscv-admin
- riscv-software-src
- riscv-android-src
- riscvarchive

**Comment by frank-zsy** [comment]
@longyanz Are you going to add the labels into OpenDigger?

**Comment by longyanz** [comment]
> @longyanz Are you going to add the labels into OpenDigger?

Sorry, I have already added the labels, but i forgot to close this issue.
