### ISSUE TITLE
How are open-diggers used

### ISSUE THREAD

**Issue by hiraeth-wangd** [X-lab2017/open-digger#1520]
### Description

Do you have documentation

**Comment by frank-zsy** [comment]
OpenDigger mainly provides metrics data for open source repositories. We publish metric data monthly for everyone to use.

You can find the supported metric data and how to access them [here](https://open-digger.x-lab.info/docs/user_docs/intro) and there is a simple [playground](https://open-digger.x-lab.info/docs/user_docs/playground) to check the data instantly.

Other documents especially for developers are still under develop, welcome to raise issue about what you want in the [website repo](https://github.com/X-lab2017/open-digger-website).
