### ISSUE TITLE
[Feature] Does OpenDigger provide a way to add a repo to be calculated

### ISSUE THREAD

**Issue by flyfishzy** [X-lab2017/open-digger#1523]
### Description

Hi, does OpenDigger provide a way to add a repo to be calculated. I found that some popular github projects can not find openrank values, such as https://github.com/faker-js/faker.
The request to https://oss.x-lab.info/open_digger/faker-js/faker/openrank.json returns a 'NoSuchKey' error.

**Comment by frank-zsy** [comment]
All the popular projects should be calculated and the data should be exported to OSS including faker.js, the URL should includes the platform which is GitHub, so the data is at https://oss.x-lab.info/open_digger/github/faker-js/faker/openrank.json .
