### ISSUE TITLE
[API error] https://oss.x-lab.info/open_digger/github/X-lab2017/open-digger/repo_network.json

### ISSUE THREAD

**Issue by ljcui** [X-lab2017/open-digger#1524]
### Description
![image](https://github.com/X-lab2017/open-digger/assets/15341849/4abca8cb-ba5f-4c98-b5a9-82198a7b808b)

**Comment by frank-zsy** [comment]
Sorry for the inconvenience, our infrastructure is partially unavailable for a few days, will recover recently.

**Comment by ljcui** [comment]
Api service is now ok, close issue.

**Comment by binary5** [comment]
![1e1d21a814f5ed8e2e07f78cfe116ee](https://github.com/X-lab2017/open-digger/assets/66581447/738ff77b-8213-446d-8d2e-49f2fc8e1990)
就是这个问题了，还有一些访问不正常
