### ISSUE TITLE
[Bug] Why can't your docker image be pulled down

### ISSUE THREAD

**Issue by tony08-08** [X-lab2017/open-digger#1533]
### Current Behavior

I encountered an error while pulling your docker image on the server
![K_MV5UMAJ~RCXNCY7G8@N3H](https://github.com/X-lab2017/open-digger/assets/135690722/c8f08869-a7c3-4201-9e74-40e990be3ee4)

**Comment by frank-zsy** [comment]
The docker image service of OpenDigger is not available right now, we will fix this soon.
