### ISSUE TITLE
[Bug] Error response from daemon: Get "https://docker-hub.x-lab.info/v2/": EOF

### ISSUE THREAD

**Issue by PureNatural** [X-lab2017/open-digger#1536]
### Current Behavior

![image](https://github.com/X-lab2017/open-digger/assets/29674550/dab958cd-4242-4093-b0ea-f208060f96a9)
<img width="1014" alt="image" src="https://github.com/X-lab2017/open-digger/assets/29674550/4341fbc5-5afc-4776-8c90-1d26e712dfc1">

**Comment by frank-zsy** [comment]
The docker image service of OpenDigger is not available right now, we will fix this soon.
