### ISSUE TITLE
[Chinese Developer] Daocloud contributors

### ISSUE THREAD

**Issue by pacoxu** [X-lab2017/open-digger#1548]
### Users

- AdamDang
- Adityayxt
- AllenZMC
- Archimedes-Dear
- BinL233
- BingGuanqi
- Carlory
- CharlesLvw
- Coderhypo
- ErikJiang
- FangtingYan
- Fish-pro
- Frapschen
- FreeZhang61
- HeavenTonight
- HuiWang0025
- Icarus9913
- JaredTan95
- JiaweiGithub
- JoeWrightss
- LronDC
- Michelle951
- NiuYinlong1994
- Onion-of-dreamed
- OwenYang1996
- Penguin-zlh
- RachaelLuo
- Rei1010
- Revolution1
- SAMZONG
- SSmallMonster
- SenXuDC
- Songjoy
- TianTianBigWang
- Vacant2333
- WPH95
- WillardHu
- XSAM
- Ye-Ting
- Zhuzhenghao
- alexzhc
- allencloud
- angel0507
- anniedy
- arugaki
- bertreyking
- brooksmtownsend
- buffalo1024
- bzsuni
- calvin0327
- carlo-zhang
- chaunceyjiang
- chuanhaojin
- cl2017
- cleverhu
- cyclinder
- dapengJacky
- dbdd4us
- dengyi1996
- donggangcj
- donghui12
- drivebyer
- dzzg
- ethan-daocloud
- falser101
- fangshun-z
- feeltimeQ
- gq94205
- gssjl2008
- hangscer8
- hanxiaop
- heliping
- huan555
- huangjiuyuan
- ii2day
- jamiefang
- jiecloud
- jiuker
- jpanda-cn
- justedennnnn
- jzhupup
- kebe7jun
- kerthcet
- learner0810
- liyuerich
- lou-lan
- lrx0014
- lsq645599166
- mengjiao-liu
- my-git9
- nameYULI
- nicole-lihui
- niulechuan
- orangegzx
- pacoxu
- panpan0000
- qar
- qiupingdai
- rokkiter
- sakeven
- sun7927
- sylvia0409
- tangming1996
- tangyanhan
- tomwei7
- tukwila
- vonsago
- wangkai1994
- wawa0210
- weizhouBlue
- willnay
- wilsonwu
- windsonsea
- wlq1212
- wwwnay
- wzshiming
- xiaopeng-han
- xiezongzhe
- xuxiawei
- xuzhenglun
- yangchuansheng
- yanggangtony
- yank1
- yankay
- yanrongshi
- yeya24
- youhonglian
- yowenter
- yttan
- yulng
- yunyu950908
- zc2638
- zgfh
- zhaosimon
- zhe
- zhouya0
- zjcomeon
- zqm19941101
- zwwhdls

All are from https://www.daocloud.io/.

### Other Information

The user list can be dumped from https://github.com/cncf/gitdm/blob/9ca4f3f8f36b877318eaad3ebf48a5be7a8cd366/company_developers3.txt#L244-L384.

**Comment by pacoxu** [comment]
BTW, we have founded several projects and joined the CNCF later.

https://github.com/DaoCloud

### [CNCF Projects](https://www.cncf.io/sandbox-projects/) founded by DaoCloud
- [clusterpedia](https://github.com/clusterpedia-io/clusterpedia): The Encyclopedia of Kubernetes clusters.
- [hwameistor](https://github.com/hwameistor/hwameistor): Hwameistor is an HA local storage system for cloud-native stateful workloads.
- [kubean](https://github.com/kubean-io/kubean): :seedling: Kubernetes lifecycle management operator based on kubespray.
- [merbridge](https://github.com/merbridge/merbridge): Use eBPF to speed up your Service Mesh like crossing an Einstein-Rosen Bridge.
- [spiderpool](https://github.com/spidernet-io/spiderpool): Underlay and RDMA network solution of the Kubernetes, for bare metal, VM and any public cloud
- [piraeus](https://github.com/piraeusdatastore/piraeus): High Available Datastore for Kubernetes

### CNCF Projects with DaoCloud [maintaners](https://github.com/cncf/foundation/blob/main/project-maintainers.csv)

- [Kubernetes](https://github.com/kubernetes/kubernetes) [**Graduated**]: Production-Grade Container Scheduling and Management
- [Istio](https://github.com/istio/istio) [**Graduated**]: Connect, secure, control, and observe services.
- [containerd](https://github.com/containerd/containerd) [**Graduated**]: An open and reliable container runtime
- [Karmada](https://github.com/karmada-io/karmada) [**Incubating**]: Open, Multi-Cloud, Multi-Cluster Kubernetes Orchestration
- [KubeEdge](https://github.com/kubeedge/kubeedge) [**Incubating**]: Kubernetes Native Edge Computing Framework
- [k-sigs/kubespray](https://github.com/kubernetes-sigs/kubespray): Deploy a Production Ready Kubernetes Cluster
- [k-sigs/KWOK](https://github.com/kubernetes-sigs/kwok): Kubernetes WithOut Kubelet -  Simulates thousands of Nodes and Clusters.
- [k-sigs/kueue](https://github.com/kubernetes-sigs/kueue): Kubernetes-native Job Queueing
- [k/kubeadm](https://github.com/kubernetes/kubeadm/): Aggregator for issues filed against kubeadm
- [k-sigs/kube-scheduler-wasm-extension](https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension): All the things to make the scheduler extendable with wasm.
- [k-sigs/lws](https://github.com/kubernetes-sigs/lws): LeaderWorkerSet: An API for deploying a group of pods as a unit of replication
- [wasmCloud/kasmcloud](https://github.com/wasmCloud/kasmcloud): Running and managing Wasm(actors) and capability providers in Kubernetes

### [CNCF LandScape](https://landscape.cncf.io/) Projects founded by DaoCloud or with DaoCloud maintainers
- [cloudtty](https://github.com/cloudtty/cloudtty): A Friendly Kubernetes CloudShell (Web Terminal) !
- [HAMi](https://github.com/Project-HAMi/HAMi): OpenAIOS vGPU scheduler for Kubernetes is originated from the OpenAIOS project to virtualize GPU device memory.

### Tools & Other Projects founded by DaoCloud or DaoClouder
- [public-image-mirror](https://github.com/DaoCloud/public-image-mirror): 很多镜像都在国外。比如 gcr 。国内下载很慢，需要加速。
- [kubernetes-lts](https://github.com/klts-io/kubernetes-lts): Kubernetes LTS(long term support)
- [kdoctor](https://github.com/kdoctor-io/kdoctor): data plane testing utility of cloud native
- [egressgateway](https://github.com/spidernet-io/egressgateway): Network egress policy for Kubernetes
- [miragedebug](https://github.com/miragedebug/miragedebug): MirageDebug: Local remote debugging for Kubernetes apps, enabling fully authentic environment debugging.
- [fedstate](https://github.com/fedstate/fedstate): Federated middleware based on Karmada
- [kube-node-tuning](https://github.com/kubean-io/kube-node-tuning): Manage kubernetes node-level kernel tuning ( using sysctl ).
- [datatunerx](https://github.com/DataTunerX/datatunerx): Large language model fine-tuning capabilities based on cloud native and distributed computing.

**Comment by frank-zsy** [comment]
@pacoxu Thanks for the rich information, and with `founded`, what exactly do you mean here?

**Comment by pacoxu** [comment]
> @pacoxu Thanks for the rich information, and with `founded`, what exactly do you mean here?

for founded, it means that DaoCloud created the project or created the project together with a partner. Later, these projects joined CNCF Sandbox.
