### ISSUE TITLE
OSGraph 2.0 is coming

### ISSUE THREAD

**Issue by ljcui** [X-lab2017/open-digger#1549]
### Description

The new web site is  https://osgraph.com

The old site http://osgraph.tugraph.com.cn/ will be going offline soon. we know http://osgraph.x-lab.info/ references it

**Comment by frank-zsy** [comment]
Thanks for informing us, we will redirect http://osgraph.x-lab.info to https://osgraph.com soon.

**Comment by frank-zsy** [comment]
Has modified the URL redirection.
