### ISSUE TITLE
能提供公开查询指标数据的接口，这很棒！但是感觉不如 OSS Compass 活跃，有点可惜

### ISSUE THREAD

**Issue by binary5** [X-lab2017/open-digger#1553]
### Description

OSS Compass 与 CHAOSS 和 魔法书 做了联动（CHAOSS 官网上写了 OSS Compass 是合作伙伴），还参与开源之夏等活动，这带来了许多流量；OSS Compass 在其官网上有详细的文档，每个模型和指标都有介绍，还可以自选指标自定义模型，可以清楚了解数据计算过程。但 OSS Compass 最大缺点是其指标数据库不是完全开放查阅的，需要单独联系专人获取（还不一定给），相比之下有些封闭。
希望 OpenDigger 更加完善一下文档和官网，多做一些联动，丰富生态，兼容更多托管平台，做出更强大的开源评价模型与方法。
祝Xlab和OpenDigger越来越好！越来越有影响力！

**Comment by frank-zsy** [comment]
Thanks for the support and suggestion, we are currently building our website and documentation. And actually we also cooperate with OSS Compass in long term, but OpenDigger is totally maintained by students and teachers in universities so the community may not be so efficient. We really appreciate the participations and contributions from universities and research institutes. And we also participate in OSPP every year, welcome to apply: https://summer-ospp.ac.cn/org/prodetail/245520513 ，https://summer-ospp.ac.cn/org/prodetail/245520536 .

---

感谢支持，我们也在积极完善文档和官网建设，OSS Compass 与我们也是长期合作关系，但与 OSS Compass 有企业员工长期全职开发不同，OpenDigger 完全是由高校实验室开发维护的，效率上可能确实较低一些，我们也希望可以支持更多的科研群体参与到开源研究之中，同时也欢迎大家的贡献，我们也参与了 OSPP 的活动，欢迎申请：https://summer-ospp.ac.cn/org/prodetail/245520513 ，https://summer-ospp.ac.cn/org/prodetail/245520536 。

**Comment by binary5** [comment]
感谢！
