### ISSUE TITLE
[OSS101] Task1: Add the label data about AIGC

### ISSUE THREAD

**Issue by Peng99999** [X-lab2017/open-digger#1559]
### Description

AIGC (AI-Generated Content) refers to a new method of content production that utilizes AI technology (generative AI approaches) to create content. 

There is now a label classification system for generative large language models (LLMs), and there is already some label data available. Specific classification systems and data can be found in #1418. 

Recently, many latest generative large language models have emerged. It is now necessary to update and add the label data.

Plase add these data in this repository/labeled_data/technology/ai/genertaive_ai:
![image](https://github.com/X-lab2017/open-digger/assets/78625977/8771b143-9343-4150-ac22-178036794974)

**Comment by Peng99999** [comment]
yml里面的ID就是各个仓库的id，后面备注则是仓库中的仓库名，可以参考opendigger中其他需要查询的指标的方法，通过sql语句来查询相关仓库的id～

**Comment by wouldmm** [comment]
你好，我还是不知道怎么查询ID，是需要把opendigger的仓库clone到本地，然后运行起来才能去查询吗？还想是否能给个简单的例子，麻烦了！

**Comment by wouldmm** [comment]
我查看了例如indices.ts 文件中的函数getRepoOpenrank ，以及其中的sql语句，但是不知道该如何才能使用它们

**Comment by Peng99999** [comment]
有两种办法，第一种在本地部署运行opendigger，查询仓库的id，可以参考使用getRepoOpenrank等类似的查询指标，查询每个仓库的id；还有一种简单的办法，直接用dbeaver类似的数据库软件，连接clickhouse通过sql语句查询每个仓库的（日志数据中）所包含的该仓库的id
