### ISSUE TITLE
[Docs] Add more details of submitting PR especially with SQL files into Contributing Guide

### ISSUE THREAD

**Issue by sunshinemingo** [X-lab2017/open-digger#156]
Although we have a workflow in appendix of [Workflow](https://www.x-lab.info/github-analysis-report/#/workflow), I think the workflow should be placed in Contributing Guide and explained with text to help participants better understand the process of submitting PR especially with SQL files.

Maybe a specific case can help better.

**Comment by frank-zsy** [comment]
Yes, I think it is a good idea to add the workflow detail to contributing guide. I will do it later.

/self-assign
