### ISSUE TITLE
[OSS101] Task6:  Data Insight Report or Visualization Work

### ISSUE THREAD

**Issue by Peng99999** [X-lab2017/open-digger#1564]
### Description

The goal of this task is to complete a data insight report or visualization work based on the existing data provided by OpenDigger or data obtained by oneself.

Refer to : 

1. Jupyter: open-digger/notebook/China_open_source_blue_paper_2022.ipynb

2. CodePen: https://codepen.io/frank-zsy/pen/abjMXBV

3. CodePen: https://codepen.io/analyticsforlawyers/pen/oLZyOK
4. Badge: https://github.com/yoshi389111/github-profile-3d-contrib

The relevant code and Report/Work for this task need to be provided in the repository.

**Comment by Thrrreeee** [comment]
请问一下，这个到时候作业提交是需要提交PR给这个仓库吗？
其次 ，我们对数据进行处理和可视化是直接使用python包画图然后进行分析，还是说需要使用codepen进行web端的渲染？

**Comment by Peng99999** [comment]
最好是提交到仓库~
上述提供的codepen是一个建议可以参考，也可以选用自己熟悉的方法，实现数据洞察报告即可
