### ISSUE TITLE
[OSS101] Task7: Open source domain visualization dashboard

### ISSUE THREAD

**Issue by Peng99999** [X-lab2017/open-digger#1565]
### Description

The task objective is to create an open source domain visualization dashboard based on the **data provided by OpenDigger** or **obtained independently**. This dashboard will primarily be used to display real-time status, trends, and relationships of large-scale data, enabling users to quickly and accurately understand the overall situation of the data.

In terms of visualization libraries, popular open-source options include D3.js, Echarts, Highcharts, AntV, etc. For frontend frameworks, React, Vue, Angular, and others are highly favored.
Additionally, there are numerous data visualization and analysis tools available. Open source tools like DataEase, Superset, Metabase, as well as commercial tools like Power BI, FineBI, Tableau, etc., can assist users in analyzing data rapidly and gaining insights into business trends.

Refer to:

1. https://[dataease.nzcer.cn/#/delink?link=VBUnBtSHpoJsJKnGJWsDbhuX7Js9mi2jhQvVt5nqVlyHIyn2uAvAO0h%2BJCR7OiyfoxIqnVG7F7qo8HlMBBWNYw&user=gdj4ml2CihGOrtwIFyMIW%2BKZq1l7bZBb34K%2FTg3uKiph2AvSvsG%2FzjFBZ1TSJRFu1%2B3JYQ%2F4yOmgIasmNbUUgA](https://dataease.nzcer.cn/#/delink?link=VBUnBtSHpoJsJKnGJWsDbhuX7Js9mi2jhQvVt5nqVlyHIyn2uAvAO0h%2BJCR7OiyfoxIqnVG7F7qo8HlMBBWNYw&user=gdj4ml2CihGOrtwIFyMIW%2BKZq1l7bZBb34K%2FTg3uKiph2AvSvsG%2FzjFBZ1TSJRFu1%2B3JYQ%2F4yOmgIasmNbUUgA)

2. https://dataease.nzcer.cn/link.html?link=KcbYHnTCu1UOtKDl6xM4AReMV8OTtVNM2w/Hbv+HKmEE9qvzp9q/FIMrJWr6OREd8D8HQhKDEKKLOABsNjwS8A==&user=tFKg7LbjBr9YjnHFoJ8JqcIxGljN2DDlxW1yJ25LtQ6h0KaUxl0OLCG989V6ED+JWCQME60MXNyI//Em3K2eKA==

**Comment by pry666** [comment]
我想请问一下如果用自己的数据obtained independently，在数据上有什么要求吗

**Comment by Peng99999** [comment]
没有要求~，可以使用opendigger所提供的数据，也可以使用自己补充的数据~

**Comment by pry666** [comment]
所以用自己数据的话，就做一个能反映出我自己数据的具体情况的leaderboard就行了，是吗？

**Comment by Peng99999** [comment]
只要是与开原生态相关的即可~

**Comment by pry666** [comment]
我在open digger使用npm run notebook的时候报了下面的错：
![2183aed339eb87c120557be6b7e7653](https://github.com/X-lab2017/open-digger/assets/71428854/b07e656a-76a4-41e5-afde-3d2525544989)

**Comment by pry666** [comment]
没事了，换成python的就可以了

**Comment by pry666** [comment]
不对，应该是用python version是可以打开notebook的，但是运行不了，因为是js的语法，但是如果用js的话，npm run notebook就会报上面的错误

**Comment by pry666** [comment]
应该是open-digger/src/cron/tasks/issue_reaction_importer.ts文件的问题，好像是部分库的改动导致有些方法不再支持了，我重新改完之后的文件发在下面了你们也可以看一下

**Comment by pry666** [comment]
主要改动的一些部分
![f89e72a3bcd46ac71c3235a251a002b](https://github.com/X-lab2017/open-digger/assets/71428854/38b3061d-5ff5-44cf-a7d8-45cd4bd5bff9)

**Comment by Peng99999** [comment]
使用不同的语言build npm run notebook，应使用不同的requirements，这个解决方案也许可以参考~#1578

**Comment by birdflyi** [comment]
> getInstallationAccessToken

Well try! getInstallationAccessToken方法似乎存在冗余，应该可以做得更好~

**Comment by birdflyi** [comment]
> 使用不同的语言build npm run notebook，应使用不同的requirements，这个解决方案也许可以参考~#1578

这个解决方案已经实现并在Windows和模拟linux环境下完成测试（try https://github.com/birdflyi/open-digger/tree/master in https://github.com/X-lab2017/open-digger/pull/1589 ），欢迎测试 @Peng99999 @pry666 😆

**Comment by pry666** [comment]
好的，我自己再尝试一下

**Comment by pry666** [comment]
![6ab5d8eefd1280835968ba45ba5c43e](https://github.com/user-attachments/assets/c0a44592-9c9d-4d40-9fd5-6d6abbe8f768)
在运行handbook_py.ipynb的时候报错这个是怎么回事

**Comment by pry666** [comment]
我换nodejs好像可以用了，但是在读取clickhouse的时候好像还是有如下报错
![86c86a294b25ec53ebbd32beee82c19](https://github.com/user-attachments/assets/88c4041f-8f00-43c8-a19b-5fb368e3ed39)

**Comment by birdflyi** [comment]
> ![6ab5d8eefd1280835968ba45ba5c43e](https://private-user-images.githubusercontent.com/71428854/349401992-c0a44592-9c9d-4d40-9fd5-6d6abbe8f768.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDQwMjYsIm5iZiI6MTcyMTIwMzcyNiwicGF0aCI6Ii83MTQyODg1NC8zNDk0MDE5OTItYzBhNDQ1OTItOWM5ZC00ZDQwLTlmZDUtNmQ2YWJiZThmNzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA4MDg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmNzJkMmQ5NWYwNDI2ZGJiNzZlMmJiN2FlMGVkYmU1N2E5NWQ5M2I5OTM2MWMxMjM2YzQ2YzgyYmJiZWRlOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EH7W3fm1Cyc8sXib1NxxidErPkrd20IS7joBsF2nptw) 在运行handbook_py.ipynb的时候报错这个是怎么回事


这是由于python kernel的此函数已经过时了。相关函数在`label_data_utils.py`中，其上一次有效维护记录是去年的commit https://github.com/X-lab2017/open-digger/commit/dc29bf3f617081d10d16f3e3b3a93c3a9345c470。

我使用如下命令追溯了当时的文件结构：
`
git clone git@github.com:X-lab2017/open-digger.git
cd open-digger/
git checkout -b tmp dc29bf3
head labeled_data/companies/360/index.yml
`
发现标签目录结构与当前版本的结构不同：
![image](https://github.com/user-attachments/assets/19c81372-c660-47ee-9664-7f6aa90d0988)
当前版本多出来了一个层次，包含了`labels`, `platforms`等新的标签划分，导致旧的python kernel无法正常处理相关的逻辑。

建议：可以尝试通过维护此kernel或换用node.js、pycjs等方式解决。

**Comment by pry666** [comment]
作业提交：仓库https://github.com/pry666/final_opendigger
