### ISSUE TITLE
[Feature] Enrich project-level data tags under various open-source foundation labels.

### ISSUE THREAD

**Issue by Nliver** [X-lab2017/open-digger#1568]
### Description

Hey there! So, I just checked out OpenDigger’s cool new ranking of open-source foundations worldwide, and I gotta say, some of the findings are quite surprising! Like, who would’ve thought OpenAtom is ahead of CNCF in terms of influence? I’m thinking this might have something to do with missing data. Don’t get me wrong, OpenDigger’s algorithm is awesome, but it could use some more juicy details to really capture the essence of the open-source world. Looking forward to seeing more data added, and I’m totally up for helping out!

**Comment by frank-zsy** [comment]
Thanks for the issue. Right now we only have a full project level label for OpenAtom in all foundations, we should definitely add project level label data to all foundations to make sure that we can compare them in same dimension.

Will do this soon.
