### ISSUE TITLE
[Bug] The "issue-author-association" field in the cloud based clickhouse database only has the "COLLABORATOR" type, and querying other types cannot obtain results.

### ISSUE THREAD

**Issue by zhingoll** [X-lab2017/open-digger#1579]
### Current Behavior

May I ask if the "issue author association" field here represents the relationship between the user who opened the issue and the repository? If so, but I tried to query other relationships and did not get any results.
![image](https://github.com/X-lab2017/open-digger/assets/113612424/f1771979-c420-4cfa-b8cc-b73fd9e76563)
However, the column "issue-comment-author-association" can reflect the actual situation very well.
![image](https://github.com/X-lab2017/open-digger/assets/113612424/958452f6-3380-4c6d-82bf-7054d0de22ae)
Is this a bug or my misunderstanding?

### Expected Behavior

If "issue author association" represents the relationship between the user who opened the issue and the repository, then it should be able to reflect the actual relationship between the user who performed the behavior and the current repository, just like the column "issue_comment-author-association".For example, like the following:
![image](https://github.com/X-lab2017/open-digger/assets/113612424/250afebb-f947-4a14-b496-e792d75214e5)

### Any Additional Comments?

I have been searching for some indicators that can be used to distinguish between peripheral developers (possibly newcomers) and core developers (possibly veterans) for a certain repository recently, so I have this confusion while following Github event information.

**Comment by frank-zsy** [comment]
Sure, I found that this is a bug in the importer program, I will fix this soon and re-import the GitHub log recently. Thanks for the report.

**Comment by frank-zsy** [comment]
The re-import process has been started and will finish in about 3 days. The reason that all the value is `COLLABORATOR` is that this value is the default value for this column, but in the new data, `NONE` will be the default value instead to avoid ambiguity.

**Comment by frank-zsy** [comment]
The issue about the data has been fixed and the data now is up-to-date with new format.
