### ISSUE TITLE
[Bug] The command `/self-assign` did not work as expected.

### ISSUE THREAD

**Issue by birdflyi** [X-lab2017/open-digger#1588]
### Current Behavior

              /self-assign

_Originally posted by @birdflyi in https://github.com/X-lab2017/open-digger/issues/1582#issuecomment-2198493494_
            
After commenting on the issue, I was not assigned. 

### Expected Behavior

I was assigned to fix issue #1582 .

### Any Additional Comments?

On the other hand, commands `/parse-github-id` are still effective.

**Comment by frank-zsy** [comment]
Hypertrons instance has been disabled for this repo which means `self-assign` and other auto label function like category has been disabled.

However, function with GitHub acitons are still effective since they are not depended on Hypertrons service.
