### ISSUE TITLE
[Bug] 数据下载链接失效

### ISSUE THREAD

**Issue by Thrrreeee** [X-lab2017/open-digger#1591]
### Current Behavior

[配置指导文档](https://github.com/X-lab2017/open-digger/blob/master/sample_data/README.md)中 `Current sample datasets` 表格里面的下载链接

1. [2020_full](https://oss.open-digger.cn/sample_data/2020_full.tar.gz)
2.  [2015_2021_top_50_year](https://oss.open-digger.cn/sample_data/2015_2021_top50_year.tar.gz) 
3. [second_sample](https://oss.open-digger.cn/sample_data/second_sample.tar.gz)
4.  [label_2015](https://oss.open-digger.cn/sample_data/label_2015.tar.gz)

上述数据链接都已经失效

**Comment by frank-zsy** [comment]
Thanks for the report, has been fixed.
