### ISSUE TITLE
[feature] A Simple Data Mirroring Needed

### ISSUE THREAD

**Issue by stevending1st** [X-lab2017/open-digger#162]
I think we need to a simple data mirroring for developers who want to test the SQL statement on their PC.
As <a src="https://github.com/TechQuery">@TechQuery</a>  said, that can also help us with simple automated tests.
I hope to use a script and a simple configuration file to connect the local project and the mirroring.
Thanks for your time.

**Comment by stevending1st** [comment]
> actually we already discussed the problem in #157

Oh, I'm sorry. Should I close this issue, and discuss in #157 ？

**Comment by frank-zsy** [comment]
No problem, we can discuss here instead. Because #157 has a doc label which not right.
