### ISSUE TITLE
Add some companies label

### ISSUE THREAD

**Issue by cuilin123123** [X-lab2017/open-digger#1642]
### Type

Company

### Repos/Orgs/Users

Naddod(武汉纳多德网络技术有限公司)
- naddod/ChatGPT-Next-Web

Dodoedu(湖北博盛数字教育服务有限公司)
- dodoedu/video-chat

E-ray(武汉易瑞信息技术股份有限公司)
- e-Ray/web_platform

Nasinet(湖北钠斯网络科技有限公司)
- Nasinet/live-web
- Nasinet/live-h5

Ygsoft(远光软件（武汉）有限公司_
- ygsoft/fork-sync
- ygsoft/shadowsocksRb-android
- ygsoft/OpenWrt-DIY
- ygsoft/rt-n56u
- ygsoft/SpringBootMovie

Bitland(武汉宝龙达信息技术有限公司)
- bitland/hardentools
- bitland/transfer.sh
- bitland/pullup
- bitland/pixiecore
- bitland/humongous
- bitland/shadow
- bitland/dattobd
- bitland/pflask
- bitland/slate
- bitland/coinbin
- bitland/retire.js
- bitland/pritunl
- bitland/easyrtc
- bitland/coinffeine
- bitland/pageres
- bitland/breach_core
- bitland/snabbswitch
- bitland/gitbucket

Tw-iot(武汉时波网络技术有限公司)
- tw-iot/mop
- tw-iot/pulsar

Gitlab(极狐信息技术（湖北）有限公司)
- GitLab/grape-path-helpers
- GitLab/kubernetes-gitlab

2mui(武汉市二木软件技术有限公司)
- 2mui/ui-market-web

Zte(武汉中兴软件有限责任公司)
- ZTE/Knitter
- ZTE/knitctl
- ZTE/dexcloud-service-mesh-sidecar
- ZTE/winery
- ZTE/BPMN4TOSCAModeler

Sxxfuture(三峡星未来数据科技（宜昌）有限公司)
- sxxfuture/boost
- sxxfuture/estuary
- sxxfuture/lotus

Wutos(湖北烽火平安智能消防科技有限公司)
- wutos/wutos
- wutos/fir

Kongyun(湖北宽云网络科技有限公司)
- Kongyun/hosts

Cqzww(湖北今古传奇数字新媒体有限公司)
- cqzww/CMSIS_5
- cqzww/chubby75
- cqzww/awesome-go
- cqzww/cobra
- cqzww/rttys
- cqzww/rtty
- cqzww/HIVIEW
- cqzww/sitewhere

Douyu(武汉斗鱼鱼乐网络科技有限公司)
- douyu/jupiter
- douyu/jupiter-layout
- douyu/proto
- douyu/juno
- douyu/juno-agent
- douyu/jupiter-examples
- douyu/rocketmq-client-go

Morequick(武汉秒开网络科技有限公司)
- morequick/minhook

Wps(武汉金山办公软件有限公司)
- WPS/egon.io-website
- WPS/domainstorytelling.org
- WPS/radvis

Weisolution(武汉唯案软件有限公司)
- Weisolution/ColossalAI

Huindata(武汉慧因数据科技有限公司)
- huindata/huindata-opensdk-whhealth-covid19

Carbit(武汉卡比特信息有限公司)
- carbit/talkie-apiandroid
- carbit/badvpn

Cenboomh(武汉盛博汇信息技术有限公司)
- Cenboomh/fhir-cn

Kingdee(武汉云启通信息技术有限公司)
- kingdee/kdesign
- kingdee/kd-charts
- kingdee/gantt
- kingdee/create-kdesign-app
- kingdee/kdesign-pro
- kingdee/kdesign-icons
- kingdee/KdDeskTC
- kingdee/kd-visualize

**Comment by frank-zsy** [comment]
There are some concerns about WPS and Kingdee, will update later.
