### ISSUE TITLE
[Feature] Issue, PR response and resolve period SQL component.

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger#207]
We need a SQL component to calculate all issues and PRs for every project in case study. We may also support multiple return values for SQL components(should be discussed).

**Comment by TieWay59** [comment]
I'm so sorry, I mistook the issue title and commented "self-assign" command accidentally. (I have deleted it.)
I didn't mean to do that. Please help me cancel the assignment @frank-zsy if necessary.
