### ISSUE TITLE
[Feature] Developer analysis for case study.

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger#276]
We need a developer case study SQL component.

We can return the most active developer accounts for case study repos.

**Comment by chenxi112** [comment]
Step1: According to the total activity of developers, we select the top 20 developers.
Step2: Based on the top 20 developers, We analyze the activity of each developer on different projects. As a developer may be involved in too many projects, I suggest that the top 10 projects be displayed in descending order according to their own activity on different projects.

**Comment by frank-zsy** [comment]
I think the result is OK but we don't really need to split into 2 steps, the result could be gathered in one SQL I think.

**Comment by chenxi112** [comment]
OK, Of course they will be gathered in one SQL.
