### ISSUE TITLE
[Feature] Release analysis for case study

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger#277]
We need a release analysis SQL component for case study.

**Comment by TieWay59** [comment]
First we can list out the latest release records with version code, publish time, and etc. (list about 10 items or more)
Base on the listed releases item, we can analyze the frequency of the releases, which can laterally tell more detail of project/community liveliness.

**Comment by frank-zsy** [comment]
I think we don't need to list release records, we can use some statistics data instead. The latest release time and version should be included. And there are some other indicators like:

- How many times the project releases in 2020.
- Average release interval.
- Average release body string length.

You may add other indicators as you like too.

**Comment by TieWay59** [comment]
OK, I'll add them in the sql components. 
Should I join them in one component or split indicators respectively?

**Comment by frank-zsy** [comment]
All release indicators should be in one SQL component I think.
