### ISSUE TITLE
[Feature] working hour distribution for case study

### ISSUE THREAD

**Issue by gymgym1212** [X-lab2017/open-digger#291]
Hi, I opened this issue for discussions about working hour distribution for case study. And how can I see the result of working hour distribution in .svg file? I mean the universal report version. @frank-zsy

**Comment by frank-zsy** [comment]
Thanks. Actually you can explore the working hour SQL component to see how it works. I use working hour record count and transfer them into 1 - 10 and then pass into the svg file as a url param, like this: [http://gar2020.opensource-service.cn/svgrenderer/github/X-lab2017/github-analysis-report?path=sqls/working-hour-distribution/image.svg&data=[2,2,3,3,2,4,5,6,7,7,7,7,8,9,10,10,9,9,8,8,7,6,5,4,3,3,4,3,3,3,5,6,7,8,7,7,8,9,10,10,9,9,8,8,7,7,5,4,4,4,4,4,3,3,5,6,7,7,7,7,7,9,10,10,9,8,8,8,7,6,5,4,3,3,4,3,3,3,5,6,7,8,7,7,8,9,10,10,10,9,8,8,7,7,5,4,3,3,4,4,3,3,5,6,7,7,6,6,7,8,9,9,9,8,7,7,6,5,4,3,2,2,2,1,1,1,1,1,2,2,2,2,3,4,4,5,4,4,4,3,3,2,2,1,1,1,1,1,1,1,1,1,2,2,2,3,3,4,4,5,4,4,4,3,3,3,2,1]&lang=en](http://gar2020.opensource-service.cn/svgrenderer/github/X-lab2017/github-analysis-report?path=sqls/working-hour-distribution/image.svg&data=[2,2,3,3,2,4,5,6,7,7,7,7,8,9,10,10,9,9,8,8,7,6,5,4,3,3,4,3,3,3,5,6,7,8,7,7,8,9,10,10,9,9,8,8,7,7,5,4,4,4,4,4,3,3,5,6,7,7,7,7,7,9,10,10,9,8,8,8,7,6,5,4,3,3,4,3,3,3,5,6,7,8,7,7,8,9,10,10,10,9,8,8,7,7,5,4,3,3,4,4,3,3,5,6,7,7,6,6,7,8,9,9,9,8,7,7,6,5,4,3,2,2,2,1,1,1,1,1,2,2,2,2,3,4,4,5,4,4,4,3,3,2,2,1,1,1,1,1,1,1,1,1,2,2,2,3,3,4,4,5,4,4,4,3,3,3,2,1]&lang=en), this means use data as dot size and use English as default language.
