### ISSUE TITLE
[DOC suggestion] shall we open a folder to archive the annual report

### ISSUE THREAD

**Issue by king-gao** [X-lab2017/open-digger#351]
Three things I suggest now ，see follow：
-  Open a floder in root dir
-  Put the release version annual report in the floder
-  Difine the report license

**Comment by frank-zsy** [comment]
@king-gao Thanks for the suggestion, actually as we discussed yesterday, we will open a new folder to archive annual reports, and we use standard CC-BY-4.0 as our License for all reports in this repo, do you have any better ideas?

**Comment by king-gao** [comment]
that's great. @frank-zsy 
Anyway, do you consider add a picture of roadmap about the annual reports in the head , It's like an overview in order to reader deeply understand the report content. For example: Add what new feature this version, next report feature plan.

**Comment by frank-zsy** [comment]
Great idea, we will add roadmap or a feature list about the report and we can discuss about the new features in weekly meeting or issues later.
