### ISSUE TITLE
[Discussion]How to add a repo to Chinese repos?

### ISSUE THREAD

**Issue by zryfish** [X-lab2017/open-digger#470]
Found [activity-repo-top-Chinese](https://github.com/X-lab2017/github-analysis-report/blob/master/sqls/activity-repo-top-Chinese/manifest.json), but why are these repositories? What should I do if I want to add a repo? For example, I think [KubeSphere](https://github.com/kubesphere/kubesphere) is more active than some of repos listed above.

**Comment by frank-zsy** [comment]
Hi, @zryfish thanks for the issue. Actually we collect the Chinese repos from different media or blogs so the data may not update to date. You can comment the repo you want to add in this issue and we will add to the config file. You may also figure out want company the repos belong to.

**Comment by FeynmanZhou** [comment]
> Hi, @zryfish thanks for the issue. Actually we collect the Chinese repos from different media or blogs so the data may not update to date. You can comment the repo you want to add in this issue and we will add to the config file. You may also figure out what companies the repos belong to.

 If you collected the Chinese repos from media or blogs, it might have a certain bias or outdated information. In my view, you would better set up an open survey to investigate and collect them accordingly : )
