### ISSUE TITLE
[Refactor] Add uni-app into Chinese projects list.

### ISSUE THREAD

**Issue by wanganxp** [X-lab2017/open-digger#474]
uni-app的用户量远超你家报告里列的其他开源项目。pinggap和用户量和star都和uni-app没法比

**Comment by frank-zsy** [comment]
@wanganxp Thanks for the issue. We collect Chinese open source projects by some medias and news. The list is definitely not intact right now. Do you mean this project(https://github.com/dcloudio/uni-app)? We will add it into the Chinese projects list, do you know which company does this project belongs to?
