### ISSUE TITLE
[Discussion] How to organization our meeting content using GitHub？

### ISSUE THREAD

**Issue by sunshinemingo** [X-lab2017/open-digger#497]
Maybe we can use issue to update our `progress`, `plan` and `topics` that want to talk about weekly.

If there are some topics discussed not well, we can continue to talk about them firstly in next meeting in the corresponding issue.

**Comment by frank-zsy** [comment]
If there are some new features we need to solve in the future from the meeting, we should add them into issue list to track the progress.

Like contributor location estimation and whether a contributor is a inside or outside contributor to a certain project are two important problems from last meeting.

**Comment by TieWay59** [comment]
WebAssembly community has a meetings repo, which is well organized. I hope this could be inspiring. 

see: [WebAssembly/meetings](https://github.com/WebAssembly/meetings)

**Comment by sunshinemingo** [comment]
Thanks a lot for your suggestion. That repo gives me some ideas to organize meetings well.
