### ISSUE TITLE
[Doc suggestion]Enrich data description document

### ISSUE THREAD

**Issue by wengzhenjie** [X-lab2017/open-digger#500]
I think we could add value description of field to the data description [document](https://github.com/X-lab2017/github-analysis-report/tree/master/docs/csv). 

For example, `issue_author_type` has four values(User, Bot, User,Mannequin). We can add this information to the document.

**Comment by frank-zsy** [comment]
Great idea, we really need more detailed description about the data. 

Do you know other columns which need more details other than `issue_autor_type`?

**Comment by wengzhenjie** [comment]
For a finite number of discrete variables, I think all the value sets should be listed. For continuous variables, I think we can list the value range.
