### ISSUE TITLE
[feature] Analyzing the project source code

### ISSUE THREAD

**Issue by stevending1st** [X-lab2017/open-digger#511]
Now the analysis of the project is only based on the activities of the project, but there is very little or no analysis of the source code of the project. It would be wonderful if you can analyze the source code. For example, it would be very good if we can classify different items for analysis. In this case, we can see the Top 10 of machine learning projects, the Top 10 of the web front-end, the Top 10 of the operating system... Manually labeling all items is a completely impossible goal. **We need to use machine learning to analyze the source code** to achieve this function.

**Comment by frank-zsy** [comment]
Thanks for the advise. As far as I know, source code is not easy to get(.git contains all source tree of a project which is quite large).

If you want to analysis the tech domain of a certain project, I think topics or NLP on README file is quite enough for this which is much easier than global source code analyze.

**Comment by stevending1st** [comment]
> If you want to analysis the tech domain of a certain project, I think topics or NLP on README file is quite enough for this which is much easier than global source code analyze.
I agree.

That sounds like a big challenge. Automated machine tagging of projects is a necessity, and I think it will introduce us to quality projects that we don't know about. In the future, producing analysis reports for specific industries will also be beneficial.

**Comment by frank-zsy** [comment]
Yes, right now we only have GitHub event log which does not contain any category information. I think we should add GitHub repo basic information into account and for top repos, they tagged their repo manually which is quite accurate and I think we just need to analyze the tags. The only challenge here is we need find out same tag with different expression by some methods like editing distance.
