### ISSUE TITLE
[Discussion] Design of Merit System

### ISSUE THREAD

**Issue by sunshinemingo** [X-lab2017/open-digger#516]
The ides of merit system design is like this : https://shimo.im/docs/wvvYgTC8g68CVg6q/read

**Comment by stevending1st** [comment]
Evaluation commands are too complex and can become a burden for community members. A newcomer to the community will first have to learn a set of evaluation commands before he can post an evaluation that is beneficial to the commenter's points. The rating categories are also very subjective, and there are many things outside of comments that can determine this. Whether or not a comment can be made via the emoji that comes with GitHub. If you get a positive emoji add points, negative emoji do not add or subtract points. If there are several positive emojis only one counts. The Q&A community is a good example of this.

It's best to have different scores for different types of issues.

**Comment by bifenglin** [comment]
Here are some of my throughts:
1. History points should called Experience point。This will make it easier to understand.
2. Experience point are designed to increase the motivation to contribute. It has an incentive effect, which can degin according to the leveling system in the game. The community could assign a logo or title to someone who has reached a certain level of experience point. And the community could hold meeting to award  a medal to these guys. And the community measure the contrabution by experience.
3. To judge whether the experience point given is convincing, I think it needs to be prove by comparing a large number of experimental data.
And here some thougts about the setting experience given standards：
- degine several sets of experience given standards
- Experimented several sets of experience given standards in multiple communities，for example, a set of criteria for implementing several communities, according to the number of people in the community and the proportion of people who reach a certain experience point can also find some interesting result in the case of large data. And the comparison between the number of people in the community of the same order of magnitude and the number of people who reach a certain experience value, etc., In this situation, we can find many dimensions in the case of large amount of data,which can also promote community research and publish certain papers. Also it needs community implementation.
- There needs to be a standard for setting experience points for different systems. What I have in mind for the moment is how many points each channel can't get in a day or a week. For example, if all channels participate in the process, then the number of points a week can't be more than 60.

**Comment by gymgym1212** [comment]
@bifenglin Thanks for your great advice. I wonder if we can create brand new titles in GitHub.
