### ISSUE TITLE
[Docs] Update Contributing Guide

### ISSUE THREAD

**Issue by sunshinemingo** [X-lab2017/open-digger#544]
We need to update contributing guide because the project was renamed.

**Comment by frank-zsy** [comment]
Not only because rename but also need thorough document for developers to understand how the project works and how to develop and test in local environment.

**Comment by wengzhenjie** [comment]
In which directory can we add local development and testing document？

**Comment by frank-zsy** [comment]
We don't have the document of local development and testing right now, I will add to document later.

**Comment by TieWay59** [comment]
Is this local development and testing document still on the schedule?

**Comment by frank-zsy** [comment]
> Is this local development and testing document still on the schedule?

Yes, of course, I will add it recently.
