### ISSUE TITLE
[Discussion] Idea list for Summer 2021 of Open Source Promotion Plan

### ISSUE THREAD

**Issue by sunshinemingo** [X-lab2017/open-digger#552]
Summer 2021 of Open Source Promotion Plan is coming!

Introduction
Open Source Promotion Plan encourages everyone to pay close attention to open source software and open source community, aiming to cultivate and explore more outstanding developers. Summer 2021 will be held in this summer. We will collaborate closely with the open source community to provide one-to-one mentor guidance and invite some specialists to conduct free online lectures. In order to promote the development of open source software and facilitate the construction of excellent open source software community, we encourage researchers, open source enthusiasts, professors as well as students to participate in the development and maintenance of open source software. Furthermore, Summer 2021 is supposed to increase the activity of open source projects, and promote the development of open source ecology.

Home：https://summer.iscas.ac.cn/
Help：https://summer.iscas.ac.cn/help/

### OpenDigger community
OpenDigger has been accepted as the community of Summer 2021.
![image](https://user-images.githubusercontent.com/37278844/117620655-44faba00-b1a3-11eb-8bfb-596b138209dd.png)

### Ideas list for OpenDigger
OpenDiggger will provide some ideas for Summer 2021. If you have any ideas, please comment on this issue. We really appreciate it.

**Please pay attention to that we need to post our ideas before `20 May`.**

**Comment by frank-zsy** [comment]
Great, do we also need a website to host the tasks?

**Comment by sunshinemingo** [comment]
OK, I will add a document file about the tasks after they are approved

**Comment by OSSome01** [comment]
> ### 2、OpenDigger Website Design
> * Description
>   
>   * OpenDigger is expected to have an official website prototype that is consistent with the project style. This project aims to use relevant design tools to design various pages and related components of the OpenDigger official website.
> * Expected outcomes
>   
>   * Website product prototype
> * Skills require
>   
>   * Designing Tools, i.e.Axure
>   * HTML, CSS
>   * Markdown
> * Difficulty
>   
>   * Medium

Hello @frank-zsy @sunshinemingo,
I am interested in developing and designing the OpenDigger website. I would love to know more about the project.
