### ISSUE TITLE
[Feature]Generate weekly reports for specified projects or organizations

### ISSUE THREAD

**Issue by seeflood** [X-lab2017/open-digger#557]
## Requirements:
After user specifying some projects, the program can generate a weekly data report regularly to show the activity of these projects during the week and rank them.

## Detail
The dimensions and format displayed in the weekly report can be based on the "GitHub most active 20 repositories" report, with a general activity indicator, and some detailed data such as pr and commit.
![image](https://user-images.githubusercontent.com/26001097/118353176-b8cc0680-b597-11eb-8d1a-f3114c162d7d.png)

## Why do I have such a demand?
I am currently responsible for the open source governance of the sofastack community. Our community has multiple projects. I hope to visually display the weekly activity of each project through digital operations, and encourage everyone to invest more in open source by publishing a weekly report.
I believe that other communities or foundations will have similar needs.

## Technical solutions
1. Data: The historical log of the specified projects can be obtained using the github API
2. No need to write UI,as long as the statistical results can be written into a file or database, users can generate reports with excel or use grafana to generate dashboards.

I can also participate in the development of this feature

Chinese:
## 需求
由用户指定一些项目，程序每周生成一份数据周报，用于展现这些项目的活跃度，并进行排名。

## 细节
周报展示的维度、形式就按照"GitHub most active 20 repositories"报表即可，有一个概括性的活跃度指标、一目了然的展现出活跃情况，以及一些详细的数据例如pr、commit。
![image](https://user-images.githubusercontent.com/26001097/118353176-b8cc0680-b597-11eb-8d1a-f3114c162d7d.png)

## 为什么我有这样的需求？
我目前负责sofastack社区的开源治理，我们社区有多个项目，我希望通过数字化运营的方式直观的展示每个项目每周的活跃度，通过发数据周报的方式激励大家更多的投入开源。
相信其他社区或者基金会也会有类似需求。

## 方案
1. 数据：可以基于github API获取指定仓库的历史日志
2. 前端可以不用做，只要能把统计出来的结果写入文件或者数据库即可，用户可以自行用excel生成报表或者用grafana生成dashboard

我也可以参与开发该功能

**Comment by frank-zsy** [comment]
@seeflood Thanks for open the issue. We actually can generate weekly report for different community and projects to online version and also publish to image or pdf file.

I will write a component to do this recently and welcome to feedback your own requirements, join the development will be excellent as well. Thanks again.
