### ISSUE TITLE
[Metrics] Common Metrics - Technical Fork

### ISSUE THREAD

**Issue by xiaoya-yaya** [X-lab2017/open-digger#570]
**Description**:

- The number of technical forks indicates the number of copies of a project on the same code development platform.
- Analysis of technical forks may provide insight into forking intentions **(different types of forks such as contributing, and non-contributing forks)**

**Filters**
- Time Period (e.g., Weekly, Monthly, Annually)
- Ratio of contributing fork to total forks `(A contributing fork is a fork that has opened a change request against the original repository.)`
- Ratio of non-contributing fork to total forks `(A non-contributing fork is a fork that has never opened a change request against the original repository.)`

**Instances of Implementation** 
![image](https://user-images.githubusercontent.com/56542972/120320461-cbbf3480-c314-11eb-9f6b-779c92657492.png)

**Resource**
CHAOSS: Common Metrics -> What
https://chaoss.community/metric-technical-fork/

**Comment by frank-zsy** [comment]
closed by #1033
