### ISSUE TITLE
[Metrics] Common Mrtrics - Activity Dates and Times

### ISSUE THREAD

**Issue by xiaoya-yaya** [X-lab2017/open-digger#571]
**Description**:
- The dates and timestamps of when contributor activities occur.
- This metric is aimed at determining the dates and times of when individual activities were completed. **The data can be used to probabilistically estimate where on earth contributions come from in cases where the time zone is not UTC.**

**Filters**
- Individual by Organization
- Aggregation of time by UTC/local time
- Repository ID
- Segment of a community, `(e.g., GrimoireLab has more EU time zones activity and Augur more US time zones activity)`

**Instances of Implementation** 
![image](https://user-images.githubusercontent.com/56542972/120325210-08415f00-c31a-11eb-872f-5a703f3a48db.png)

**Resource**
- CHAOSS: Common Metrics -> When
- https://chaoss.community/metric-activity-dates-and-times/

**Comment by frank-zsy** [comment]
It is like the working hour distribution in our report, right? @xiaoya-yaya

**Comment by xiaoya-yaya** [comment]
> It is like the working hour distribution in our report, right? @xiaoya-yaya

Yes, I think it is!

**Comment by frank-zsy** [comment]
Good, I will take this one.

/self-assign
