### ISSUE TITLE
[Metrics] Common Metrics - Time to Close

### ISSUE THREAD

**Issue by xiaoya-yaya** [X-lab2017/open-digger#575]
**Description**:
- How much time passes between creating and closing an operation such as an issue, change request, or support ticket?
- The time to close is the total amount of time that passes between the creation and closing of an operation such as an issue, change request, or support ticket.

**Filters**
- Creator of operation (e.g., new contributor vs. maintainer)
- First closed, final closed
- Labels (e.g., bug vs. new feature)
- Change Request Merge Status (e.g. Time to Merge or Time to Close without Merge)

**Instances of Implementation** 
![image](https://user-images.githubusercontent.com/56542972/120345687-47c57680-c32d-11eb-8527-7d7d96835f6a.png)

**Resource**
CHAOSS: Common Metrics -> When
https://chaoss.community/metric-time-to-close/

**Comment by frank-zsy** [comment]
I think just like `issue resolution duration`, we just need `change request resolution duration` to close this issue.

**Comment by xiaoya-yaya** [comment]
Yes. `Time to close` and `Time to first response` are like two abstract functions, to initialize them, we can have `issue close time`, `pr close time`... and `issue response time`,` pr response time`, or `'mailinglist response time'`
