### ISSUE TITLE
[Metrics] Change Requests

### ISSUE THREAD

**Issue by xiaoya-yaya** [X-lab2017/open-digger#580]
**Description**
- What new change requests to the source code occurred during a certain period?
- **"Change requests" correspond to "pull requests" in the case of GitHub**, to "merge requests" in the case of GitLab, and to "code reviews" or in some contexts "changesets" in the case of Gerrit

**Implementation**
- Count per month over time
- Status (open, closed)
https://chaoss.biterg.io/app/kibana#/dashboard/GitHub-Pull-Requests
![image](https://user-images.githubusercontent.com/56542972/120423864-d540af00-c39d-11eb-9555-04ba107eab6d.png)

**Resource**
CHAOSS: Evolution -> Code Development Process Quality
https://chaoss.community/metric-change-requests/

**Comment by frank-zsy** [comment]
closed by #1036
