### ISSUE TITLE
[Metrics] Change Requests Accepted

### ISSUE THREAD

**Issue by xiaoya-yaya** [X-lab2017/open-digger#581]
**Description**
- Accepted change requests are those that end with the corresponding changes finally merged into the code base of the project.

**Implementation**
- Count. Total number of accepted change requests during the period.
- Ratio. Ratio of accepted change requests over total number of change requests during that period.
https://chaoss.biterg.io/app/kibana#/dashboard/a7b3fd70-ef16-11e8-9be6-c962f0cee9ae
![image](https://user-images.githubusercontent.com/56542972/120424099-5009ca00-c39e-11eb-85a8-c054bf72f6bf.png)

**Resource**
CHAOSS: Evolution -> Code Development Efficiency
https://chaoss.community/metric-change-requests-accepted/

**Comment by frank-zsy** [comment]
Close #927
