### ISSUE TITLE
[Metrics] Change Requests Declined

### ISSUE THREAD

**Issue by xiaoya-yaya** [X-lab2017/open-digger#582]
**Description**
- Declined change requests are those that are finally closed without being merged into the code base of the project.

**Implementation**
Count. Total number of declined change requests during the period.
Ratio. Ratio of declined change requests over the total number of change requests during that period.

**Resource**
CHAOSS: Evolution -> Code Development Activity

**Comment by frank-zsy** [comment]
Closed by #933
