### ISSUE TITLE
[Metrics] Active Issues

### ISSUE THREAD

**Issue by xiaoya-yaya** [X-lab2017/open-digger#586]
**Description**
- How many issues were active during a certain period?
- Issues showing some activity are those that had some comment, or some change in state (including closing the issue), during a certain period.
- In GitHub Issues, a comment, a new tag, or the action of closing an issue, is considered as a sign of activity.

**Implementation**
- Count. Total number of active issues during the period.
- Ratio. Ratio of active issues over total number of issues during that period.
- https://chaoss.biterg.io/app/kibana#/dashboard/GitHub-Issues

**Resource**
CHAOSS: Evolution -> Issue Resolution
https://chaoss.community/metric-issues-active/

**Comment by xgdyp** [comment]
We will reach the metric by counting how many issues are active in a certain period?
for example:
input a start time : 2022.9.1 and a stop time:2022.10.1
then return a count.
Is this right?

**Comment by xiaoya-yaya** [comment]
Yes. This metric measures the count of the number of issues that have been active during a given period.
