### ISSUE TITLE
[Metrics] Closed Issues

### ISSUE THREAD

**Issue by xiaoya-yaya** [X-lab2017/open-digger#587]
**Description**
- How many issues were closed during a certain period?
- Issues closed are those that changed to state closed during a certain period.

**Implementation**
- Count. Total number of active issues during the period.
- Ratio. Ratio of active issues over total number of issues during that period.
- Reactions. **Number of "thumb-ups" or other reactions on issues.**
https://chaoss.biterg.io/app/kibana#/dashboard/GitHub-Issues

**Resource**
CHAOSS: Evolution -> Issue Resolution
https://chaoss.community/metric-issues-closed/

**Comment by xiaoya-yaya** [comment]
I‘m trying to implement this metric referencing https://github.com/X-lab2017/open-digger/pull/866, and I‘m confused about:

- How do I run local tests?
- How do I add sample code and demonstrate the results in the jupyter notebook if I can't run local tests?

**Comment by frank-zsy** [comment]
You can run local test by start a sample data instance in local environment, following the doc [here](https://github.com/X-lab2017/open-digger/tree/master/sample_data). Top 50 repos or 2020 full data will be enough to test the metrics.
