### ISSUE TITLE
[Metrics] Inactive Contributors

### ISSUE THREAD

**Issue by xiaoya-yaya** [X-lab2017/open-digger#591]
**Description**
- How many Contributors have stopped contributing over a specific period of time.
- The period of time required for a contributor to be counted as inactive can be decided by a variable and this metric will display the number of contributors that have been labeled as inactive over a given time frame.

**Filters**
- Minimum contributions required to be considered active
- Period of time to determine inactivity
- Start date/End date

**Implementation**
The metric will take in two variables - **a time period** and a **interval.**
- time period: the period over which the number of inactive members will be displayed
- interval: determine how long it takes for a contributor to be labeled as inactive

The metric will work by:
1. getting a list of all contributors
2. checking the last contribution date
3. if the last contribution date is before the cutoff then add them to the inactivity count of the period they last contributed in.
4. create list of inactive contributors

**Resource**
CHAOSS: Evolution -> Community Growth
https://chaoss.community/metric-inactive-contributors/

**Comment by wangleo61** [comment]
Cool

On Jun 2, 2021, at 14:01, Xiaoya ***@***.***> wrote:


  *   Minimum contributions required to be considered active
