### ISSUE TITLE
[Metrics] New Contributors Closing Issues

### ISSUE THREAD

**Issue by xiaoya-yaya** [X-lab2017/open-digger#593]
**Description**
- This metric is an indication of the volume of contributors who are closing issues for their first time within a given project.
- When a contributor closes an issue for the first time it is some indication of "stickiness" of the individual within that project, especially for contributors who are not also committers.
- **That is, New Issue Closers**

**Implementation**
- Count. Total number of contributors closing issues on this project **for the first time** during a given time period.
- Ratio.  Proportion of contributors closing issues on this project **for the first time** during a given time period, computed against all contributors having closed issues on this project during the same time period.

e.g. Table with names of contributors who closed an issue for the first time and when that was.

**Resource**
CHAOSS: Evolution -> Community Growth
https://chaoss.community/metric-new-contributors-closing-issues/

**Comment by xgdyp** [comment]
Hi @xiaoya-yaya, how can a new contributor close issues? Do you mean a PR related issue closed by new contributors?

**Comment by xiaoya-yaya** [comment]
It represents the number of contributors closing an issue for the first time during a given period, **no matter what attributes of the issues**, i.e, opened by the contributor or not, related to PR or not, etc.

From the definition, **New Issue Closers** as a community role represents a kind of conversion that indicates the stickiness to the community

**Comment by xgdyp** [comment]
I see, but I mean a normal contributor only can close their own issue unless he has member access(or other). So I think we can do other metrics fisrt.

**Comment by xiaoya-yaya** [comment]
Agreed.

> I see, but I mean a normal contributor only can close their own issue unless he has member access(or other). So I think we can do other metrics fisrt.
