### ISSUE TITLE
about the code of Weekly Report

### ISSUE THREAD

**Issue by wey-gu** [X-lab2017/open-digger#599]
Dear open-digger-ers!
Awesome job!
May I ask if the bot code for generating Weekly Report is accessible or open-sourced? 
I did a rough search to find this: https://github.com/abhijeetps/weekly-digest/ , while it seems lacking in "new contributor" information.

Thanks!!!
BR//Wey

**Comment by frank-zsy** [comment]
@wey-gu Thanks for you attention. The weekly report is generated by https://github.com/hypertrons/hypertrons , the `open-digger-bot` is an instance of the project which we will back to maintain recently.

**Comment by wey-gu** [comment]
> @wey-gu Thanks for your attention. The weekly report is generated by https://github.com/hypertrons/hypertrons , the `open-digger-bot` is an instance of the project which we will back to maintain recently.

Dear Frank,
Thanks for the prompt response and the information :-), will look into hypertrons!
Good to know that you will continue to maintain `open-digger-bot`. 
From my understanding, `open-digger-bot` is now still a private repo or? part of the source code of open-digger?

BR//Wey

**Comment by frank-zsy** [comment]
You misunderstand here. The `open-digger-bot` is a GitHub App and the backend is `Hypertrons` which is open source too.

Actually the [weekly report component](https://github.com/hypertrons/hypertrons/tree/master/app/basic/helper/weekly-report) is in the project by default and there are lots of [default components](https://github.com/hypertrons/hypertrons/tree/master/app/component) in the project to help manage your open source project.

And `Hypertrons` also supports customize component like [this one](https://github.com/X-lab2017/open-digger/tree/master/.github/hypertrons-components/auto_update_contribution) in open-digger to generate [`CONTRIBUTORS`](https://github.com/X-lab2017/open-digger/blob/master/CONTRIBUTORS) file every week to track historical contributions in the community. I believe you can find your GitHub account in the file next week~~

**Comment by frank-zsy** [comment]
And to enable the component, you only need to configure it into the `Hypertrons` [config](https://github.com/X-lab2017/open-digger/blob/master/.github/hypertrons.json#L85) in your own repo.

BTW, the `open-digger-bot` is a private GitHub App so you can not access and only serves this repo.

**Comment by wey-gu** [comment]
> You misunderstand here. The `open-digger-bot` is a GitHub App and the backend is `Hypertrons` which is open source too.
> 
> Actually the [weekly report component](https://github.com/hypertrons/hypertrons/tree/master/app/basic/helper/weekly-report) is in the project by default and there are lots of [default components](https://github.com/hypertrons/hypertrons/tree/master/app/component) in the project to help manage your open source project.
> 
> And `Hypertrons` also supports customize component like [this one](https://github.com/X-lab2017/open-digger/tree/master/.github/hypertrons-components/auto_update_contribution) in open-digger to generate [`CONTRIBUTORS`](https://github.com/X-lab2017/open-digger/blob/master/CONTRIBUTORS) file every week to track historical contributions in the community. I believe you can find your GitHub account in the file next week~~

Aha, crystal clear for me now, sorry for the silly queries ;-).
Thank you, Frank, tons of thanks!

**Comment by frank-zsy** [comment]
No problem and we will back to maintain the project soon, very welcome to use the project in your community~~

I will close issue for now and if you have any more questions about Hypertrons, you can open an issue [here](https://github.com/hypertrons/hypertrons/issues).
