### ISSUE TITLE
[Feature Request]add a weekly case study for SOFAStack&MOSN community

### ISSUE THREAD

**Issue by seeflood** [X-lab2017/open-digger#602]
## Requirements
After submiting the issue #557 ,I talked with @frank-zsy and we managed to find out an easier way to generate weekly reports for the specific repositorys.
Here is the approach :
1. Add a case study about the repos,with a 'where 'statement in the sql to filter out the event logs only in last 7 days.
2. Run the case study every week to generate a weekly report,using the data in ClickHouse. (I would appreciate it if it can be generated on Saturday before 4 p.m.)

So I come here to submit a feature request to add a weekly case study for SOFAStack&MOSN community.

## Details
The dimensions and format displayed in the weekly report can be same with the "GitHub most active 20 repositories" report. The only difference is that I just want the statistics based on the event logs in **last week** and **in specific repositorys**.
![image](https://user-images.githubusercontent.com/26001097/121769587-f7ed7780-cb96-11eb-9072-26cd9721a70b.png)

It is better to add a new column 'new contributors'.But it is ok if the program don't do that automatically,since I can do it myself.

## Related Repositorys 
Here is the repos included in the report.

Org | Repo
-- | --
mosn | mosn
sofastack | sofa-jraft
sofastack | sofa-boot
sofastack | sofa-rpc
sofastack | sofa-rpc-node
sofastack | sofa-ark
sofastack | sofa-registry
sofastack | sofa-hessian-node
sofastack | sofa-bolt
sofastack | sofa-tracer
sofastack | sofa-hessian
sofastack | sofa-bolt-node
sofastack | sofa-bolt-cpp
sofastack | sofa-jarslink
sofastack | sofa-node
sofastack | sofa-bolt-python
sofastack | sofa-lookout
sofastack | sofa-acts
sofastack | sofa-dashboard

Thanks a lot!

**Comment by wengzhenjie** [comment]
Thanks for your issue！ Our data is based on github event log. There is no contributors info in this data. If you want to know the new contributors, you can use github API to get info. In the future, we will add new data including the contributor info to support our report. 
For other info, I will add the component recently.  Thanks for your issue again!

**Comment by seeflood** [comment]
> Thanks for your issue！ Our data is based on github event log. There is no contributors info in this data. If you want to know the new contributors, you can use github API to get info. In the future, we will add new data including the contributor info to support our report.
> For other info, I will add the component recently. Thanks for your issue again!

Yep,the contributor data is not necessary here and I will count it by myself.
Thank you very much! This component  will definitely help us a lot in operating the communities,and maybe in the future it can help many more open source projects!

**Comment by frank-zsy** [comment]
/self-assign

I will add a sample report this week and you can give us feedback about your report.
