### ISSUE TITLE
[Discussion] We need to label issues and prs

### ISSUE THREAD

**Issue by sunshinemingo** [X-lab2017/open-digger#607]
Label issues and prs in different dimensions, such as category, importance, difficulty and other dimensions, so that developers can better understand the situation of issues and prs.

This is the labels I organized: https://shimo.im/docs/TjYkqT8CXGtdkcjG

**Comment by frank-zsy** [comment]
The labels are good but I think we don't need the metric details label because we are not exactly using CHAOSS metrics and we have more metrics about open source. So maybe we only need `metric` label.
