### ISSUE TITLE
[feature] Add links outside of GitHub to the README file

### ISSUE THREAD

**Issue by stevending1st** [X-lab2017/open-digger#610]
Now, we're talking about how to transfer the meeting notes to GitHub. I think we should add the link to the shimo document of the meeting notes to the README file first. In addition, a summary of resources and documentation should be added to GitHub. If feasible, add the meeting URL to GitHub as well.

List of links:
- [x] [OpenDigger Open Source Meeting](https://shimo.im/docs/THkd6GQYtTj6PT3t)
- [x] [{ GitHub 全域数字年报开源项目 } 文档与资源](https://shimo.im/docs/Hr8gJkrwdjRtW6DC/read)
- [x] [Meeting Room:](https://meeting.tencent.com/s/pCwYhCacOCOS) (Room ID: 627 8609 7587) Every Thursday at 12:00 am GMT+8

**Comment by frank-zsy** [comment]
Great suggestion, the second document may not be needed any more but we definitely should add meeting information and meeting notes into GitHub.

**Comment by stevending1st** [comment]
Done
