### ISSUE TITLE
[feature] [Discussion] Some suggestions on system design

### ISSUE THREAD

**Issue by stevending1st** [X-lab2017/open-digger#611]
There are currently some problems with this project:

Each customized requirement needs to be completed manually every time. If A customizes several index reports for Project A, and B customizes the same index report for B, it seems that it needs to be written twice at present. For the general index of the report, such as the monthly data growth, it cannot be completed by the customer. It needs to submit the requirements to the project team and the project team manually deploys it online.

Regarding the above questions, I put forward some suggestions for improvement of the system:

1. Modify some specific data in SQL as parameters, and pass the parameters to SQL through Shell to complete the data query. You can also check the parameters in the shell script.

2. Increase the account system, members can select the indicators they need according to the list, and let the background generate new reports according to the set time (of course these may incur additional expenses, and there are many rules that need to be discussed).

---
目前这个项目存在一些问题：

每个定制的需求需要每次手动的完成。如果A定制了A项目的几个指数报表，B定制了B同样的指数报表,目前似乎需要写两遍。对于报表的通用型指数——比如每月数据增长量，不能由客户自己完成，需要向项目组提交需求，项目组手动部署上线。

对于以上的问题，提出对系统的一些改进意见：

1.  将 SQL 中的一些具体的数据修改为参数，通过 Shell 将参数传递给 SQL, 完成数据的查询。在 shell 脚本中还可以对完成对参数的检查。

2.  增加账号系统，会员可以根据列表选择自己需要的指标，并让后台按设定的时间产生新的报告(当然这些可能会产生额外的开支，也有许多规则需要讨论)。

**Comment by frank-zsy** [comment]
Thanks for the suggestion, here is my thought.

- For the first issue, actually every SQL component has a config file right now which allows a report to pass in its own parameters like repos, weights and etc. With proper design, SQL components definitely can be reused by different reports.
- For any community who wants to use OpenDigger to generate reports, right now can add its report config file under case-study folder and schedule function will be added in the next version of the project. And with the online generation function in the next version we can allow anyone generate their reports from website and maybe with some fee.

**Comment by stevending1st** [comment]
I'm glad to hear these! 👍
