### ISSUE TITLE
[feature] Add more description and a link to Bilibili's video

### ISSUE THREAD

**Issue by stevending1st** [X-lab2017/open-digger#612]
The contributors to this repository have uploaded many of the videos to Bilibili, and it might be useful to include a brief description of the project and a link to the project in the introductory section of the video or in the comments section where it is Topped.

**Comment by frank-zsy** [comment]
Yes, we should add repo link to the videos and add week meetings links into the repo too. Are there any videos besides meetings every week? @stevending1st

**Comment by stevending1st** [comment]
> Are there any videos besides meetings every week?

I think you'd better to  ask this question to the bilibili's account administrator. I have no definite answer.

**Comment by stevending1st** [comment]
TODO

- [ ] []()
- [ ] []()
- [ ] []()
- [ ] []()
- [ ] []()
- [ ] []()

**Comment by sunshinemingo** [comment]
Thanks a lot, I think it very helpful.

Or we can organize our meeting video like this.
- [The sixteenth community meeting](https://www.bilibili.com/video/BV1JX4y1w7Jc/) - Framework refactor & Activity metric implementation

**Comment by stevending1st** [comment]
> Or we can organize our meeting video like this.
 
Could you specify what you mean?

**Comment by sunshinemingo** [comment]
> > Or we can organize our meeting video like this.
>  
> Could you specify what you mean?
> 

I mean we can use this format, like _meeting link - meeting description_

**Comment by stevending1st** [comment]
Done.

**Comment by stevending1st** [comment]
Done
