### ISSUE TITLE
[discussion] Star Should NOT be Counted as Activeness

### ISSUE THREAD

**Issue by stevending1st** [X-lab2017/open-digger#624]
The active of "star" is essentially a marker that expresses the prospective user's interest in the project, not the activity of the project itself.

If it is to be counted as activity, the weight should be adjusted to a very low level.

---

”star“这种行为本质上是一种标记，表达的是准用户对项目的观望，不能算项目本身的活动。

如果实在要算作活动，应该把权重调整到非常低。

**Comment by sunshinemingo** [comment]
- `star` is mainly used to measure the attention of project instead of the activity of the project. 

- `star` is indeed the lowest weight in the calculation of activity

**Comment by stevending1st** [comment]
Done
