### ISSUE TITLE
The label text of the ASF China graphic is garbled

### ISSUE THREAD

**Issue by zhangliqing** [X-lab2017/open-digger#669]
http://opendigger-oss.x-lab.info/case-study-ASF.html

![image](https://user-images.githubusercontent.com/5851575/140851001-e402f3cd-da5f-4b3e-bfd1-48b76a6d3fae.png)

**Comment by frank-zsy** [comment]
Confirmed, this is caused by the fact that we use OSS actions to upload the file but do not set the content type header properly, we need to set the encode to UTF-8 to avoid this.

Will fix in the future.

**Comment by frank-zsy** [comment]
The html version report won't be used in the future, we gonna update the reports into Jupyter Notebook later.
