### ISSUE TITLE
Add SRS to Chinese open source study report

### ISSUE THREAD

**Issue by winlinvip** [X-lab2017/open-digger#671]
Sorry, I don't know the issue format.

Od has a good definition of the activity of open source projects, which is better than star. It is the focus of open source projects.

I hope SRS can be added to [Chinese open source study report](http://opendigger-oss.x-lab.info/case-study-Chinese.html), because SRS is definitely an open source project in China, incubated in Mulan community.

SRS: https://github.com/ossrs/srs

After looking at about 35 in the lower row, I don't know the specific data or where I haven't done enough.

**Comment by frank-zsy** [comment]
Thanks for the PR, we will add the whole organization into the config file and welcome to use English in the repo.

**Comment by winlinvip** [comment]
Translate by baidu fanyi.
