### ISSUE TITLE
[Doc] We need an issue template file to help others to submit labeled data

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger#677]
We may need an issue template to help developers to submit their data like company repos, repos that they donate to foundations and community with multiple repos. Something like these.

They may submit the data as markdown format list and we can add them into config file ourselves.

**Comment by frank-zsy** [comment]
Can you do this one? @gymgym1212

**Comment by gymgym1212** [comment]
> Can you do this one? @gymgym1212

Yes

**Comment by gymgym1212** [comment]
I think the table syntax of markdown is too cumbersome, which will bring great obstacles to users to fill in. How about changing the syntax to something like a yaml file?
```
orgs:
  - 1234567 # org_name
    - ...
repos:
  - 7654321 # repo_name
  - ...
``` 

In addition, do users know how to get the ID of the organization or repo? Should we also add a paragraph of guidance to tell users how to obtain IDs?

**Comment by frank-zsy** [comment]
Yes, markdown table is too complex for others, bullet points is good enough but we don't really need to left the two whitespace to fit the yaml syntax, I think plain markdown list is good enough for this.
