### ISSUE TITLE
Pls help add labeled data into OpenDigger to help us for our community analysis[Alibaba]

### ISSUE THREAD

**Issue by alibaba-oss** [X-lab2017/open-digger#684]
I want to add some labeled data into OpenDigger to help us for our community analysis.

Label: Alibaba

Repos:
- apache/rocketmq
- apache/rocketmq-externals
- apache/rocketmq-streams
- apache/rocketmq-client-cpp
- apache/rocketmq-client-go
- apache/rocketmq-flink
- apache/rocketmq-dashboard
- apache/rocketmq-exporter
- apache/rocketmq-spring
- apache/rocketmq-operator
- apache/rocketmq-site
- apache/rocketmq-docker
- apache/rocketmq-client-python
- apache/rocketmq-client-nodejs
- apache/dubbo
- apache/dubbo-spring-boot-project
- apache/dubbo-go
- apache/dubbo-admin
- apache/dubbo-samples
- apache/dubbo-js
- apache/dubbo-website
- apache/dubbo-php-framework
- apache/dubbo-proxy
- apache/dubbo-go-pixiu
- apache/dubbo-python
- apache/dubbo-rpc-jsonrpc
- apache/dubbo-go-hessian2
- apache/dubbo-getty
- apache/dubbo-go-samples
- apache/dubbo-kubernetes
- apache/dubbo-docs
- apache/dubbo-spi-extensions
- apache/dubbo-sentinel-support
- apache/dubbo-erlang
- apache/dubbo-awesome
- apache/dubbo-benchmark
- apache/dubbo-hessian-lite
- apache/dubbo-python2
- apache/dubbo-async-processor
- apache/dubbo-feature-test
- apache/dubbo-logo
- apache/dubbo-serialization-gson
- openmessaging/benchmark
- openmessaging/openchaos
- openmessaging/dledger

Orgs/Repos:
- Alibaba-Sample
- AlibabaCloudDocs
- AlibabaPAI
- AliyunContainerService
- ApsaraDB
- GraphScope
- T-head-Semi
- XianyuTech
- alibaba
- alibaba-edu
- alibabacloud-go
- alibabacloud-howto
- alibabacloud-sdk-cpp
- alibabacloud-sdk-php
- alibabacloud-sdk-swift
- alipay
- aliqin
- aliyun
- aliyun-beta
- chaosblade-io
- cloudnativeapp
- dragonflyoss
- dubbo
- dvajs
- eggjs
- flink-extended
- hiloteam
- ice-lab
- kissyteam
- kubedl-io
- macaca-sample
- macacajs
- mars-project
- midwayjs
- node-honeycomb
- node-modules
- oecp
- openkraken
- openyurtio
- seata
- sentinel-group
- taobao
- teambition
- v6d-io
- weex-ui-team

Thanks.

**Comment by frank-zsy** [comment]
Thanks for your contribution on labeled data for Aliabab. 

All orgs and repos id are parsed correctly, we will add these data into OpenDigger.

**Comment by alibaba-oss** [comment]
I think we need to discuss how to label Apache Dubbo,RocketMQ Flink repos as they are have already been donoted to Apache Software Foundation and they are now "owned" by Alibaba. @gymgym1212 @frank-zsy
