### ISSUE TITLE
Pls help add labeled data into OpenDigger to help us for our community analysis[Alibaba]

### ISSUE THREAD

**Issue by alibaba-oss** [X-lab2017/open-digger#688]
I want to add some labeled data into OpenDigger to help us for our community analysis.
Label: Alibaba
Repos:
- apache/flink
- apache/flink-ml
- apache/flink-shaded
- apache/flink-web
- apache/flink-statefun
- apache/flink-benchmarks
- apache/flink-connectors
- apache/flink-training
- apache/flink-docker
- apache/flink-statefun-playground
- apache/flink-statefun-docker
- apache/flink-playgrounds
- apache/flink-jira-bot

Thanks.

**Comment by alibaba-oss** [comment]
I think we need to discuss how to label Apache Dubbo,RocketMQ Flink repos as they are have already been donoted to Apache Software Foundation and they are now "owned" by Alibaba. @gymgym1212 @frank-zsy

**Comment by AlexStocks** [comment]
I want to add some labeled data into OpenDigger to help us for our community analysis.
Label: Dubbo
Repos:

https://github.com/apache/dubbo
https://github.com/apache/dubbo-go
https://github.com/apache/dubbo-go-hessian2
https://github.com/apache/dubbo-go-pixiu
https://github.com/apache/dubbo-website
https://github.com/apache/dubbo-spi-extensions
https://github.com/apache/dubbo-admin
https://github.com/apache/dubbo-go-samples
https://github.com/apache/dubbo-getty
https://github.com/apache/dubbo-hessian-lite
https://github.com/apache/dubbo-js
https://github.com/apache/dubbo-spring-boot-project
https://github.com/apache/dubbo-benchmark
https://github.com/apache/dubbo-awesome
https://github.com/dubbogo/arana
https://github.com/dubbogo/dubbo-go-pixiu-filter
https://github.com/dubbogo/triple
https://github.com/dubbogo/grpc-go
https://github.com/dubbogo/tools
https://github.com/dubbogo/gost
https://github.com/dubbogo/dubbo-go-book
https://github.com/dubbogo/dubbo-go-benchmark
https://github.com/dubbogo/dubbogo.github.io
https://github.com/dubbogo/go-zookeeper
https://github.com/dubbogo/community
https://github.com/dubbogo/dubbo-go-proxy-samples
https://github.com/dubbogo/v3router
https://github.com/dubbogo/triple-benchmark
https://github.com/dubbogo/proxy-community
https://github.com/dubbogo/jsonparser
