### ISSUE TITLE
Submit Labeled Data [Linux Foundation] & [Chinese]

### ISSUE THREAD

**Issue by gymgym1212** [X-lab2017/open-digger#693]
I want to add some labeled data into OpenDigger to help us for our community analysis.

Label: 

Repos:
- Angel-ML/angel
- ForestFlow/ForestFlow
- linkedin/TonY
- datapractices/data-practices-site
- odpi/OpenDS4All
- Project-OpenBytes/OpenBytes
- OpenLineage/OpenLineage
- JanusGraph/janusgraph
- milvus-io/milvus
- amundsen-io/amundsen
- datashim-io/datashim
- MarquezProject/marquez
- feast-dev/feast
- nnstreamer/nnstreamer
- odpi/egeria
- Delta-ML/delta
- RosaeNLG/rosaenlg
- Adlik/Adlik
- kserve/kserve
- Substra/substra
- horovod/horovod
- ludwig-ai/ludwig
- onnx/onnx
- acumos/documentation
- machine-learning-exchange/mlx
- flyteorg/flyte
- quantumblacklabs/kedro
- KomputeProject/kompute
- pyro-ppl/pyro
- elasticdeeplearning/edl
- soajs/soajs
- sparklyr/sparklyr
- Trusted-AI/AIX360
- Trusted-AI/adversarial-robustness-toolbox
- Trusted-AI/AIF360
- hyperledger/caliper
- hyperledger/cello
- lf-edge/ekuiper
- journeymidnight/yig

Orgs/Users:

- projectacrn
- occlum
- cloud-hypervisor
- baetyl
- onap
- XGVela
- ifeilong
- openmessaging
- nextarchfoundation
- sodafoundation
- TarsCloud

**Comment by frank-zsy** [comment]
I noticed that some projects only include the main repo of the project like `JanusGraph/janusgraph`, `milvus-io/milvus`. Do all the projects under the org belong to Linux foundation, or just the main repo belongs to Linux foundation?

**Comment by frank-zsy** [comment]
And do all these projects directly belong to Linux Foundation or belong to some specific sub foundation?
