### ISSUE TITLE
Pls help add label date for community analysis[alibaba-dubbogo]

### ISSUE THREAD

**Issue by AlexStocks** [X-lab2017/open-digger#703]
I want to add some labeled data into OpenDigger to help us for our community analysis. Label: Alibaba 
Orgs/Repos:
  •  dubbogo

  •   https://github.com/dubbogo/arana
  •   https://github.com/dubbogo/dubbo-go-pixiu-filter
  •  https://github.com/dubbogo/triple
  •  https://github.com/dubbogo/grpc-go
  •  https://github.com/dubbogo/tools
  •  https://github.com/dubbogo/gost
  •  https://github.com/dubbogo/dubbo-go-book
  •  https://github.com/dubbogo/dubbo-go-benchmark
  •  https://github.com/dubbogo/dubbogo.github.io
  •  https://github.com/dubbogo/go-zookeeper
  •  https://github.com/dubbogo/community
  •  https://github.com/dubbogo/dubbo-go-proxy-samples
  •  https://github.com/dubbogo/v3router
  •  https://github.com/dubbogo/triple-benchmark
  •  https://github.com/dubbogo/proxy-community
  •  https://github.com/dubbogo/jsonparser

Thanks

**Comment by alibaba-oss** [comment]
I want to add some labeled data into OpenDigger to help us for our community analysis. Label: Alibaba 

Orgs/Repos:
  •  dubbogo

Thanks

**Comment by gymgym1212** [comment]
Hello @AlexStocks , thanks you for submitting labeled data of alibaba-dubbogo. It seems that another account has submitted the same content, so I will close this issue.
