### ISSUE TITLE
Submit labeled data [Fit2Cloud]

### ISSUE THREAD

**Issue by gymgym1212** [X-lab2017/open-digger#718]
I want to add some labeled data into OpenDigger to help us for our community analysis.

Label: Fit2Cloud

Type: Company

Repos:

Orgs/Users:

- jumpserver
- metersphere
- dataease
- halo-dev
- KubeOperator

**Comment by maninhill** [comment]
I want to add some labeled data into OpenDigger to help us for our community analysis.

Label: Fit2Cloud

Type: Company

Repos:

Orgs/Users:

- jumpserver
- metersphere
- dataease
- halo-dev
- KubeOperator

**Comment by frank-zsy** [comment]
> /parse-github-id

The command only parse the issue body so the comment won't take effect. I modify the issue body and will add the label data to OpenDigger now.

**Comment by maninhill** [comment]
Thank you very much, Frank.

**Comment by frank-zsy** [comment]
> Thank you very much, Frank.

You are welcome, sorry for the late reply.
