### ISSUE TITLE
Change one label

### ISSUE THREAD

**Issue by stevending1st** [X-lab2017/open-digger#720]
I want to **delete** one Chinese developer labeled data into OpenDigger to help us for our community analysis.

1148 line :

fit2bot | 37.5 |   | 否 | 中国 | FIT2CLOUD 飞致云旗下 JumpServer 项目（https://github.com/jumpserver/jumpserver）用于自动处理 pull request 的账号
-- | -- | -- | -- | -- | --

this label should be **bot**。

Label: China

Type: Region

**Comment by frank-zsy** [comment]
Bot is not labeled in OpenDigger right now, we will add bot label in the future.
