### ISSUE TITLE
[Data] Add Microsoft label data

### ISSUE THREAD

**Issue by xiaoya-Esther** [X-lab2017/open-digger#733]
I want to add some labeled data into OpenDigger to help us for our community analysis.

Label: microsoft

Type: Company

Repos:
- microsoft/Web-Dev-For-Beginners
- microsoft/ML-For-Beginners
- microsoft/PowerToys
- microsoft/vscode
- microsoft/terminal
- microsoft/playwright
- microsoft/TypeScript
- microsoft/IoT-For-Beginners
- microsoft/Data-Science-For-Beginners
- dotnet/maui
- microsoft/calculator
- microsoft/wslg
- microsoft/Swin-Transformer
- microsoft/winget-cli
- PowerShell/PowerShell
- microsoft/cascadia-code
- microsoft/qlib
- microsoft/NUWA
- microsoft/monaco-editor
- microsoft/Bringing-Old-Photos-Back-to-Life
- dotnet/aspnetcore
- dotnet-architecture/eShopOnContainers
- dotnet/runtime
- microsoft/recommenders
- microsoft/ai-edu
- microsoft/STL
- microsoft/api-guidelines
- microsoft/nni
- microsoft/vcpkg
- microsoft/DeepSpeed
- microsoft/playwright-python
- microsoft/pyright
- microsoft/griffel
- microsoft/windows-rs
- microsoft/LightGBM
- microsoft/dotnet-podcasts
- microsoft/reverse-proxy
- microsoft/Power-Fx
- microsoft/fluentui
- microsoft/winget-pkgs

Data source: https://opensource.microsoft.com/projects/explore/

Orgs:
- microsoft
- dotnet
- dotnet-architecture

**Comment by frank-zsy** [comment]
I think actually you can just put `microsoft` org and `dotnet` org under `Microsoft` company label rather than add few repos into it.

**Comment by xiaoya-Esther** [comment]
Make sense. I presumed since Microsoft OSPO decided to display only these projects on the websites. Maybe they are the ones that are worth counting.

Calculating according to `org` is way more convenient.

**Comment by frank-zsy** [comment]
Yes, actually companies tend to display the most important projects on their website but all the repos under their org should be treat as their projects. You can modify the issue body and run `/parse-github-id` again to get the new result.

**Comment by xiaoya-Esther** [comment]
Thank you!
