### ISSUE TITLE
[Data] Add Salesforce label data

### ISSUE THREAD

**Issue by xiaoya-Esther** [X-lab2017/open-digger#735]
I want to add some labeled data into OpenDigger to help us for our community analysis.

Label: Company

Type: 

Repos:

- apache/predictionio/

Orgs/Users:

- salesforce
- oclif
- raml-org
- datorama

Data source: https://opensource.salesforce.com/

**Comment by frank-zsy** [comment]
I looked into the repos and I think `oclif`, `raml-org` and `datorama` are all under Salesforce company so we can include the orgs directly.
