### ISSUE TITLE
[Data] Add Meta label data

### ISSUE THREAD

**Issue by xiaoya-Esther** [X-lab2017/open-digger#736]
I want to add some labeled data into OpenDigger to help us for our community analysis.

Label: 

Type: Company

Repos:

Data Source: https://opensource.fb.com/projects

Note: There are 600+ projects displayed, I only selected the most popular ones.

Orgs/Users:

- facebook
- facebookresearch
- pytorch
- facebookexperimental
- fbsamples
- Instagram
- facebookincubator

**Comment by frank-zsy** [comment]
Actually if you already include the orgs then you do not need to add the repos under the orgs individually.
