### ISSUE TITLE
[Feature] Add new Chinese Hacking Force data format

### ISSUE THREAD

**Issue by sy-records** [X-lab2017/open-digger#768]
The data is now a yaml file. see https://github.com/X-lab2017/open-digger/blob/e1691bf52cc7ebd7adb443b9ed981d97accf1046/labeled_data/regions/China.yml#L104-L119

Is it possible to add a new format file? This way we can use CI for continuous updates. https://github.com/OpenSourceWin/hacking-force/issues/8

The new format uses `json`, e.g.

```json
{
    "GitHub Login": "Active participation in contributed projects"
}
```

```json
{
    "zhenglaizhang": "Azure/azure-rest-api-specs,openapi-env-test/azure-rest-api-specs,zhenglaizhang/github-scala,zhenglaizhang/azure-rest-api-specs,test-repo-billy/azure-rest-api-specs,Azure/azure-sdk-tools,Azure/git-rest-api,test-repo-billy/sdk-release-request,Azure/oav,zhenglaizhang/azure-rest-api-specs",
    "hsluoyz": "casdoor/casdoor,casbin/casbin,casbin/casnode,casbin/jcasbin,casbin/pycasbin,casbin/node-casbin,casbin/casbin-website,casbin/gorm-adapter,casbin/casbin-cpp,casbin/Casbin.NET",
    "tiye": "calcit-lang/calcit_runner.rs,calcit-lang/calcit-runner-apis,Respo/respo.calcit,calcit-lang/calcit-runner.nim,calcit-lang/respo-calcit-workflow,Quatrefoil-GL/quatrefoil,Quamolit/phlox.calcit,Cirru/cirru-edn.rs,calcit-lang/calcit-paint,Cirru/parser.rs"
}
```

**Comment by frank-zsy** [comment]
@sy-records Actually all the data like most active repos are also in the database, the labeled data only provide what is missing in GitHub data.

So we can use a crontab task to generate what you need for website update, all we need is the data structure and I will implement in the [task](https://github.com/X-lab2017/open-digger/blob/master/src/cron/tasks/hacking_force_month.ts) and put the data online.

And also we need to know the time range to generate the data, yearly, seasonly or monthly?

**Comment by sy-records** [comment]
First we need a yearly data for 2021. for 2022 we can provide monthly or quarterly data and then we need to discuss how to display it in the website.

**Comment by frank-zsy** [comment]
Maybe before we decide how to display the new data, I will modify the task to generate data for 2021 annually first.

**Comment by frank-zsy** [comment]
@sy-records I have added a task and upload the result on to OSS [here](https://hypertrons-oss.x-lab.info/hacking_force/annual_2021.json), can you checkout whether it can be used or some other fields need to be added?

**Comment by sy-records** [comment]
This list seems to be different from the users of the site, are new users being added?

**Comment by frank-zsy** [comment]
> This list seems to be different from the users of the site, are new users being added?

Yes, some other accounts also added, should I truncate the data to 99 users? Here is a total list of all known Chinese developers.

**Comment by sy-records** [comment]
No need to intercept to 99, I just have some questions about the ranking.

There are currently more than 99 users in the [site](https://opensource.win/#detail).
