### ISSUE TITLE
Like DB-Engines, Is it possible for Open-Digger to publish reports on time every month?

### ISSUE THREAD

**Issue by maninhill** [X-lab2017/open-digger#770]
The DB-Engines Ranking(https://db-engines.com/en/ranking) ranks database management systems according to their popularity. 

The ranking is updated **monthly**.

I hope Open-Digger can publish similar rankings monthly, and improve the official website to DB-Engines level.

**Comment by frank-zsy** [comment]
Thanks for the advise. And the answer is yes, actually we are already have the work done for the first edition and will publish in this month. Users can find out all the ranking by month or by year from 2015 up to now.

**Comment by maninhill** [comment]
That's great. I am looking forward to the result.

**Comment by frank-zsy** [comment]
And as an open source for research, we will also publish all the historical data as JSON format for anyone to use as well.
