### ISSUE TITLE
《2022 中国开源发展蓝皮书》数据支撑

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger#781]
### Discussed in https://github.com/X-lab2017/open-digger/discussions/779

<div type='discussions-op-text'>

<sup>Originally posted by **will-ww** March 17, 2022</sup>
去年 OpenDigger 的部分内容支持了《2021 中国开源发展蓝皮书》：http://www.copu.org.cn/new/308

今年我们继续，和 Frank 讨论后，今年可以直接提供一个 Jupyter Notebook 的文件，然后让编委方进行加工，这样我们给不同方面输出的成果能够标准化，便于我们开发。

还请 Frank 将框架中的几个内容跑出来（目前还无法做到的删掉即可），我增加点文字，即可交付过去了。（直接参考了我们”GitHub 2021 数字洞察报告“的结构内容 ）

**1.  总体情况**

- 全球日志事件、活跃仓库数量、活跃开发者数量，近5年的总体数量与每年的增长率。
- 中国日志事件、活跃仓库数量、活跃开发者数量，近5年的总体数量与每年的增长率。

即这部分，展示全球以及中国的整体趋势状况即可，如果能有些时空分布图则更好，特别是全球开发者的地理位置分布。

**2. 中美企业对比情况**

- 2021年美国企业活跃度 Top10 榜单，包括：排名、企业名、总活跃度、日均活跃度、项目总数、参与贡献者总数，人均活跃度
- 2021年中国企业活跃度 Top10 榜单，包括：排名、企业名、总活跃度、日均活跃度、项目总数、参与贡献者总数，人均活跃度
- 2021年美国企业影响力 Top10 榜单，包括：排名、企业名、影响力、项目总数、参与贡献者总数，人均影响力
- 2021年中国企业影响力 Top10 榜单，包括：排名、企业名、影响力、项目总数、参与贡献者总数，人均影响力
- 近十年中国厂商开源活跃度 TOP 10。（类似《中国十年开源洞察报告》）
- 近十年中国厂商开源影响力 TOP 10。
- 某种方式的对比，最好能体现中国某一个方面的上升或接近（项目数量、参与人数、总体/人均等）

**3. 中国项目情况**

- GitHub 2021 年全球项目活跃度 Top 20
- GitHub 2021 年中国项目活跃度 Top 20
- GitHub 2021 年全球项目影响力 Top 20
- GitHub 2021 年中国项目影响力 Top 20
- 近5年，中国 Top10 项目活跃度变化趋势图
- 近5年，中国 Top10 项目影响力变化趋势图
- 某种方式的对比，最好能体现中国某一个方面的上升或接近（项目活跃度/影响力、参与人数、总体/人均等）

以上内容是我想到的适合放到《2022 中国开源发展蓝皮书》，可以任意修改和删减~ @frank-zsy 
</div>

**Comment by will-ww** [comment]
Many thanks, great work~
