### ISSUE TITLE
Add  EMQ open source data

### ISSUE THREAD

**Issue by maninhill** [X-lab2017/open-digger#788]
I want to add some labeled data into OpenDigger to help us for our community analysis.

Label: EMQ

Type: Company

Repos:

- 

Orgs:

- emqx
- hstreamdb

**Comment by frank-zsy** [comment]
Thanks for the issue and this one should be under `Chinese` label too?

**Comment by maninhill** [comment]
> Thanks for the issue and this one should be under `Chinese` label too?

Exactly.

**Comment by frank-zsy** [comment]
Thanks for the issue, the data has been merged in #792 and you can check the new company data on [leaderboard](http://open-leaderboard.x-lab.info/).
