### ISSUE TITLE
Add Zilliz open source data

### ISSUE THREAD

**Issue by maninhill** [X-lab2017/open-digger#791]
I want to add some labeled data into OpenDigger to help us for our community analysis.

Label: Zilliz

Type: Company

Repos:

- 

Orgs:

- milvus-io

**Comment by maninhill** [comment]
This should be under Chinese label too.

**Comment by frank-zsy** [comment]
Thanks for the issue, the data has been merged in #792 and you can check the new company data on [leaderboard](http://open-leaderboard.x-lab.info/).
