### ISSUE TITLE
About remove GitHub App data from OpenRank

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger#793]
We removed GitHub App data (which created by [bot] like account) from the OpenRank calculation with the following reason:

- The OpenRank is a PageRank like algorithm which not only use statistic data but also look into the relationship between users and repos. But GitHub App like dependabot can be installed on any repo which will break the deeper information the collaboration relationships offer. So we choose to remove bot from the OpenRank calculation but we will still include them in activity calculation.

**Comment by gymgym1212** [comment]
It may be a good choice to improve the performance of OpenRank. I'll create an issue in open-leaderboard discussing about it.

**Comment by frank-zsy** [comment]
OK
