### ISSUE TITLE
[Proposal] Add COSS proejct list

### ISSUE THREAD

**Issue by guilin-f2c** [X-lab2017/open-digger#794]
In the last several years, there are more and more commerial open source projects (COSS) rised in China. Compare to many opensource projects hosted by internet companies, COSS is typical drived by independent software companies.

In America, there is a Venture Captial (OSS Captial，https://oss.capital/ ） focused to invest COSS projects and they mantain one COSS project list （https://docs.google.com/spreadsheets/d/17nKMpi_Dh5slCqzLSFBoWMxNvWiwt2R-t4e_l7LPLhU/edit#gid=0）

I think open-digger project can do similar thing to maintain COSS project list in China.  Not Only does it help open-digger to analyze more open-source project in China, but also it can help team to do more deep investigation on COSS projects in China.

**Comment by frank-zsy** [comment]
Thanks, great idea and excellent resource, we can add a new label of COSS as a sub label of company and add the lists to the label.

And even we can add a notebook to analyze COSS company rather than put them together with internet company like Google or Alibaba.

**Comment by xiaoya-yaya** [comment]
COSS list aboard: 
https://docs.google.com/spreadsheets/d/17nKMpi_Dh5slCqzLSFBoWMxNvWiwt2R-t4e_l7LPLhU/edit#gid=0

COSS list in China:
https://gitcode.net/open-source-lab/List-of-Chinese-Open-Source-Project-Financing
https://github.com/chenzhepeter/ChinaCOSS
