### ISSUE TITLE
Add Mulan Labeled Data in GitHub Platform

### ISSUE THREAD

**Issue by gymgym1212** [X-lab2017/open-digger#814]
I want to add some labeled data into OpenDigger to help us for Mulan community analysis.

Label:  Mulan

Type: Community

Repos:

- kubeovn/kube-ovn
- cas-bigdatalab/piflow
- oceanbase/obclient
- ossrs/srs
- rcore-os/zCore
- MonkSoul/Furion
- X-lab2017/open-digger

Orgs/Users:

- jianmu-dev

**Comment by frank-zsy** [comment]
It's hard to compare with repos and orgs, can we divide them into different projects. And like `kubeovn` maybe a project contains all the repos under `kubeovn` org rather than only the `kube-ovn` repo? Or we can say only the repo is under Mulan community but not other repos under the org?
