### ISSUE TITLE
attlee-wang is a chinese developer

### ISSUE THREAD

**Issue by attlee-wang** [X-lab2017/open-digger#817]
I want to add some Chinese developer labeled data into OpenDigger to help us for our community analysis.

Label: China

Type: Region

beijing 

Users:

- attlee-wang

**Comment by frank-zsy** [comment]
Thank you for the issue, I will handle this soon.

/parse-github-id

**Comment by frank-zsy** [comment]
@attlee-wang The data has been merged be #818 , online data will be updated next month~
