### ISSUE TITLE
[Doc] Add Summer2022 challenges to website

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger#830]
We may need to add [Summer2022](https://summer-ospp.ac.cn/#/org/orgdetail/7f0cf08e-d4fc-4459-899b-f37f99007720/) related information into website as the all three challenges has been published.

So developers from community can learn about the challenges and pick up whatever they want to join the event.

**Comment by xiaoya-Esther** [comment]
Website meaning here? http://www.x-lab.info/open-digger/#/

Which section should we put the information?

**Comment by frank-zsy** [comment]
@xiaoya-Esther Yes, maybe we can start a new section like `events` and put `summer2022` into it. So we can spread out the page to developers.
