### ISSUE TITLE
No data.md

### ISSUE THREAD

**Issue by xgdyp** [X-lab2017/open-digger#848]
I click the link "data" in README but no such file
<img width="932" alt="image" src="https://user-images.githubusercontent.com/37795442/171331822-abec966c-a516-42bb-ac2c-b508309852bf.png">

<img width="1087" alt="image" src="https://user-images.githubusercontent.com/37795442/171331692-c10db175-fafd-4925-9d00-d3c2ff0833fb.png">

**Comment by frank-zsy** [comment]
Thanks, fixed.
