### ISSUE TITLE
Add OpenMMLab open source data

### ISSUE THREAD

**Issue by yaqi0510** [X-lab2017/open-digger#851]
I want to add some labeled data into OpenDigger to help us for our community analysis.

Label: Shanghai AI Lab - OpenMMLab

Type: 'Company' & 'Project'

Repos:

- 

Orgs/Users:

- open-mmlab

**Comment by frank-zsy** [comment]
@yaqi0510 Thanks, the data has been merged and will take effect in rank list for next month.
