### ISSUE TITLE
[Refactor] SQL optimize for activity

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger#861]
Right now, `index.activity` uses ClickHouse and script to implement a quite complex and not quite efficient version to calculate activity for repos and developers. But with some powerful functions provided by ClickHouse engine, we can do this more elegant and efficient.

We could use `groupArrayInsertAt` and `limit by (key)` to get the general SQL better. Be aware that the server version is 20.8.7.15 which does support dynamic array length so we need to calculate the array length first in the script.

**Comment by tyn1998** [comment]
Hello, @frank-zsy. Is the `index.activity` you mentioned same to the "Activity" metrics that Hypercrx presents?

<img width="325" alt="image" src="https://user-images.githubusercontent.com/32434520/172287617-d46531fc-a7b1-45ca-a8db-4623ea24a796.png">

**Comment by frank-zsy** [comment]
Yes, it is. Right now, the value is calculated from here https://github.com/X-lab2017/open-digger/blob/master/src/metrics/activity_openrank.ts#L71. In order to support different needs, we need the function to support configurable repo/org range, time range and various group function(like with group by month/quarter/year and repo/org/label). So the script right now is quite ugly and need to be optimized with a more elegant and efficient version of SQL.

**Comment by tyn1998** [comment]
Really looking forward to the elegant version~

**Comment by frank-zsy** [comment]
@tyn1998 The new version is online, we can use a single SQL without any script modification to get data for any configuration now. Feel free to check it out.

**Comment by tyn1998** [comment]
<img width="333" alt="image" src="https://user-images.githubusercontent.com/32434520/172743561-6e41e021-351f-4c06-b1de-597a3c90d6c8.png">

Cool~
