### ISSUE TITLE
使用sample data中的数据源在容器的data目录挂载，首次启动容器时容器秒退

### ISSUE THREAD

**Issue by Angelia-Wang** [X-lab2017/open-digger#868]
## 问题

使用 sample data中的2015_2021_top_50_year数据源，通过运行以下命令启动容器，发现容器并未成功启动。

```shell
docker run -d -it --name top_50_container -m 3G -p 8123:8123 -p 9000:9000 --ulimit nofile=262144:262144 --volume=/home/course/data/ossdevgov_2022_final/:/data/ docker-hub.x-lab.info/opendigger/open-digger-clickhouse-base:v1
```

通过 `docker ps -a` 发现该容器启动后秒退。

![91654871137_ pic](https://user-images.githubusercontent.com/61470228/173090384-9f77dce0-4f01-451c-b6fa-5b36c7fe27c7.jpg)

查看报错日志显示， github_log这个数据库在CK中已存在。

![111654871137_ pic_hd](https://user-images.githubusercontent.com/61470228/173090496-f81429fb-8353-4e61-be98-b1036f19dbaf.jpg)

## 解决方法

此问题通过删除该容器，并重新启动解决。猜测此问题应该是容器首次启动没有初始化完成导致的。

**Comment by frank-zsy** [comment]
@Angelia-Wang Thanks for the bug report, welcome to use English to communicate in the community. The issue is caused by partial initialization of the container instance.

Drop the database on init first will solve the problem.
