### ISSUE TITLE
[Documentation] Enrich the sample data usage documentation with the guide of courses

### ISSUE THREAD

**Issue by xiaoya-yaya** [X-lab2017/open-digger#875]
### Issue
I'm using the sample data `label_2015 ` referring [this document](https://github.com/X-lab2017/open-digger/tree/master/sample_data). It's not clear as a tiro about how to mount data into the container. Suggest add a command example like this:

`docker run -d -it --name container_name -m 4G -p 8123:8123 -p 9000:9000 --ulimit nofile=262144:262144 --volume=path:/data/ docker-hub.x-lab.info/opendigger/open-digger-clickhouse-base:v1`

The documentation should be enriched of the content from the guide of [final practice](https://shimo.im/docs/0l3NV8Z8MMhMNj3R/read) and [mid-term practice ](https://shimo.im/docs/XKq4MybL2bU9dKkN/read)

**Comment by frank-zsy** [comment]
@xiaoya-yaya there is demo script here https://github.com/X-lab2017/open-digger/blob/master/sample_data/start_server.sh , do you want to add it directly into documentation? The command is mentioned here https://github.com/X-lab2017/open-digger/blob/master/sample_data/README.md?plain=1#L13
