### ISSUE TITLE
Add Guojusoft open source data

### ISSUE THREAD

**Issue by maninhill** [X-lab2017/open-digger#882]
I want to add some labeled data into OpenDigger to help us for our community analysis.

Label: Guojusoft

Type: Company

Repos:

- 

Orgs:

- jeecgboot

**Comment by frank-zsy** [comment]
Thanks for the data improvement.

/parse-github-id

**Comment by frank-zsy** [comment]
This should be also in China region right? @maninhill

**Comment by maninhill** [comment]
> This should be also in China region right? @maninhill

Yes, you are right.
