### ISSUE TITLE
[bug]github repos table have Duplicated data

### ISSUE THREAD

**Issue by bifenglin** [X-lab2017/open-digger#887]
I find the the table github_repos have Duplicated data sometimes. Is that my fault? here is the data what copy from the table.
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/15813364/174792658-f870fc7b-1225-491a-a498-916d5c783c84.png">

**Comment by frank-zsy** [comment]
This is something with MongoDB and MaxCompute which has nothing to do with OpenDigger.

**Comment by bifenglin** [comment]
thx to @frank-zsy . The reason is mongoDB `$unwind` method which makes the changed data with one repo_id into numbers row with one repo_id.
