### ISSUE TITLE
[ospp] Some thoughts on Python SDK

### ISSUE THREAD

**Issue by xgdyp** [X-lab2017/open-digger#896]
In open-digger, we can create a query easily by `openDigger.driver.clickhouse.query`.
In our Python SDK, I think this can be matched by Pandas and SQLAlchemy.
I did some previous attempts with mysql like：
```
import pandas as pd 
import numpy as np
from sqlalchemy import create_engine

class MySQL():
    
    def __init__(self) -> None:
        self.uri = 'mysql+pymysql://xx:xxx@xxx3306/md?charset=utf8'
        self.engine= create_engine(self.uri)
    
    def read_table(self, tablename):
        return pd.read_sql_table(tablename,self.engine)
    def read_sql(self,query:str)->pd.DataFrame:
        return pd.read_sql_query(query,self.engine)

    def write_table(self, tablename,df,if_exists = "replace",index = False,chunksize = 100 ):
        return df.to_sql(tablename, self.engine, if_exists=if_exists ,index=index,chunksize=chunksize)
```
I think this can be used in ClickHouse too. But I'm not sure if `array` can be parsed into `list` 
automatically .

**Comment by frank-zsy** [comment]
If we have a proper JupyterLab docker image with Python kernel and libraries installed, we can easily add a Python version to OpenDigger. Actually the work is under developing by @Best-Eminem right now.

**Comment by xgdyp** [comment]
> If we have a proper JupyterLab docker image with Python kernel and libraries installed, we can easily add a Python version to OpenDigger. Actually the work is under developing by @Best-Eminem right now.

OK, I just had some ideas on it

**Comment by frank-zsy** [comment]
Thanks for the ideas, I think you can give a review after the PR is raised~

**Comment by Best-Eminem** [comment]
I prefer to use [clickhouse-driver](https://clickhouse-driver.readthedocs.io/en/latest/index.html#) to create a query for ClickHouse in our Python SDK, and [Py2neo](https://py2neo.org#) for Neo4j. Both these two drivers are well designed and easy to use. And they can both convert the results into `list` easily. @[xgdyp](https://github.com/xgdyp)

**Comment by xgdyp** [comment]
> I prefer to use [clickhouse-driver](https://clickhouse-driver.readthedocs.io/en/latest/index.html#) to create a query for ClickHouse in our Python SDK, and [Py2neo](https://py2neo.org#) for Neo4j. Both these two drivers are well designed and easy to use. And they can both convert the results into `list` easily. @[xgdyp](https://github.com/xgdyp)

How can I use the query result? Is query return a dict? or a cursor? Can I import the result into pandas?

**Comment by Best-Eminem** [comment]
> > I prefer to use [clickhouse-driver](https://clickhouse-driver.readthedocs.io/en/latest/index.html#) to create a query for ClickHouse in our Python SDK, and [Py2neo](https://py2neo.org#) for Neo4j. Both these two drivers are well designed and easy to use. And they can both convert the results into `list` easily. @[xgdyp](https://github.com/xgdyp)
> 
> How can I use the query result? Is query return a dict? or a cursor? Can I import the result into pandas?

The result list only have the tuples but no dict `[('YTVanced/VancedManager', 2884), ('dnSpy/dnSpy', 1379)]`. Do you mean that you need the result including the label like this? `{ repo_name: 'YTVanced/VancedManager', cnt: '2884' }`

**Comment by xgdyp** [comment]
> > > I prefer to use [clickhouse-driver](https://clickhouse-driver.readthedocs.io/en/latest/index.html#) to create a query for ClickHouse in our Python SDK, and [Py2neo](https://py2neo.org#) for Neo4j. Both these two drivers are well designed and easy to use. And they can both convert the results into `list` easily. @[xgdyp](https://github.com/xgdyp)
> > 
> > 
> > How can I use the query result? Is query return a dict? or a cursor? Can I import the result into pandas?
> 
> The result list only have the tuples but no dict `[('YTVanced/VancedManager', 2884), ('dnSpy/dnSpy', 1379)]`. Do you mean that you need the result including the label like this? `{ repo_name: 'YTVanced/VancedManager', cnt: '2884' }`

It seems that the tuples can convert to dataframe. I just think tuples may be complicating in subsequent tasks

**Comment by Best-Eminem** [comment]
We can continue to communicate if there are any questions. @[xgdyp](https://github.com/xgdyp)

**Comment by xgdyp** [comment]
@Best-Eminem I found that in clickhouse-driver, we can use `query_dataframe` function to achieve the requirements we discussed earlier.
That's awesome!
<img width="679" alt="image" src="https://user-images.githubusercontent.com/37795442/180350855-4e62bac1-68fe-4163-8639-7d4693ad01b1.png">

**Comment by xgdyp** [comment]
and `array` can convert to `list` too

**Comment by Best-Eminem** [comment]
> @Best-Eminem I found that in clickhouse-driver, we can use `query_dataframe` function to achieve the requirements we discussed earlier. That's awesome! <img alt="image" width="679" src="https://user-images.githubusercontent.com/37795442/180350855-4e62bac1-68fe-4163-8639-7d4693ad01b1.png">

Yeah, that's great. I can add another query function with using `query_dataframe(query)`.

**Comment by xgdyp** [comment]
> > @Best-Eminem I found that in clickhouse-driver, we can use `query_dataframe` function to achieve the requirements we discussed earlier. That's awesome! <img alt="image" width="679" src="https://user-images.githubusercontent.com/37795442/180350855-4e62bac1-68fe-4163-8639-7d4693ad01b1.png">
> 
> Yeah, that's great. I can add another query function with using `query_dataframe(query)`.

Thanks!

**Comment by Best-Eminem** [comment]
![image](https://user-images.githubusercontent.com/66980876/180354732-5e5e7a4e-ffcd-4d68-b6c1-3276ca1f4393.png)
The above output is the original one, and the bottom is the output using `query_dataframe(query)`. @xgdyp

**Comment by xgdyp** [comment]
> ![image](https://user-images.githubusercontent.com/66980876/180354732-5e5e7a4e-ffcd-4d68-b6c1-3276ca1f4393.png) The above output is the original one, and the bottom is the output using `query_dataframe(query)`. @xgdyp

yes, it converts raw return data to dataframe and return a dataframe

**Comment by frank-zsy** [comment]
@Best-Eminem Can you update the Python kernel progress here? How far did you get and what support you need?

**Comment by Best-Eminem** [comment]
> @Best-Eminem Can you update the Python kernel progress here? How far did you get and what support you need?

Ok, the python kernel have almost done, I have already tested some metrics using clickhouse mirror, but I need latest clickhouse mirror and neo4j mirror to test other function implemented by python.

**Comment by frank-zsy** [comment]
We don't have Neo4j mirror right now since related graph data is quite complex and hard to split. Maybe you can open a pull request with the Python kernel and I can test the global data for you.

**Comment by Best-Eminem** [comment]
> We don't have Neo4j mirror right now since related graph data is quite complex and hard to split. Maybe you can open a pull request with the Python kernel and I can test the global data for you.

ok, I will open a pull request in one day or two.
