### ISSUE TITLE
[Doc] The command line to initialize a clickhouse database may cause a bug.

### ISSUE THREAD

**Issue by yoyo-wu98** [X-lab2017/open-digger#917]
### Description

According to the following README:

https://github.com/X-lab2017/open-digger/blob/982da928364ff8c30a4517e9c19b036dde1f7660/sample_data/README.md?plain=1#L13

When we want to initialize a clickhouse database of open-digger, the docker command line is `docker run -d --name container_name -m 6G -p 8123:8123 -p 9000:9000 --ulimit nofile=262144:262144 --volume=./folder_path/:/data/ open-digger-clickhouse-base:v1`.

Pay attention to the VOLUME part `--volume=./folder_path/:/data/`. This command line may lead to a bug.

For example, if I want to bind-mount the `./label_2015` to container's `/data`, we will get an error:

```shell
$ docker run -d --name opendigger_demo -m 6G -p 8123:8123 -p 9000:9000 --ulimit nofile=262144:262144 --volume=./label_2015/:/data/ docker-hub.x-lab.info/opendigger/open-digger-clickhouse-base:v1
docker: Error response from daemon: create label_2015/: "./label_2015/" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
```

And if we remove the `.` and  `/` in `./label_2015`, we will get another error:

```shell
$ docker run -d --name opendigger_demo -m 6G -p 8123:8123 -p 9000:9000 --ulimit nofile=262144:262144 --volume=label_2015:/data/ docker-hub.x-lab.info/opendigger/open-digger-clickhouse-base:v1
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
24f0cb088c7c5cd8ebf60c6e56580d01124c3e7dc6a67cc33bb900ca6d24ce3a

$ docker ps -a
CONTAINER ID        IMAGE                                                             COMMAND             CREATED             STATUS                       PORTS               NAMES
24f0cb088c7c        docker-hub.x-lab.info/opendigger/open-digger-clickhouse-base:v1   "/entrypoint.sh"    7 seconds ago       Exited (255) 5 seconds ago                       opendigger_demo

$ docker logs opendigger_demo
Processing configuration file '/etc/clickhouse-server/config.xml'.
Merging configuration file '/etc/clickhouse-server/config.d/docker_related_config.xml'.
Include not found: clickhouse_remote_servers
Include not found: clickhouse_compression
Logging trace to /var/log/clickhouse-server/clickhouse-server.log
Logging errors to /var/log/clickhouse-server/clickhouse-server.err.log
Processing configuration file '/etc/clickhouse-server/users.xml'.
Include not found: networks
Saved preprocessed configuration to '/var/lib/clickhouse//preprocessed_configs/users.xml'.

/entrypoint.sh: sourcing /docker-entrypoint-initdb.d/initdb.sh
Data or table file not exists under /data folder
```

We can see that there is something wrong with the `/data` in the container and it must be caused by the argument `label_2015`.

### Reason

The reason of this bug is the rule of `host-src` in `--volume=[host-src:]container-dest[:<options>]`.

As referred in [Docker's Doc](https://docs.docker.com/engine/reference/run/#volume-shared-filesystems), the `host-src` in `--volume=[host-src:]container-dest[:<options>]` must be an absolute path or a name value.
- If you supply an absolute path for the `host-src`, Docker bind-mounts to the path you specify. 
- If you supply a name, Docker creates a named volume by that name.

**A name value must start with an alphanumeric character, followed by `a-z0-9`, `_` (underscore), `.` (period) or `-` (hyphen). An absolute path starts with a `/` (forward slash).**

**So, the `./folder_path` in our README may mislead the reader to use a relative path in the command line.**(Guess who have been misled already.) 

### Suggestion

I think may be we should modify this part in README and place a notice right after it?

**Comment by frank-zsy** [comment]
Yes, thanks for the remind. It's true that the volume src path should be an absolute path. We should modify the doc here.

I think we can use `$(pwd)` before the folder name to complete the path, which will lead another thing that under windows, this should be replaced by `%cd%`. This will give the command an absolute path of the folder.

Please feel free to modify it by comment `/self-assign` to claim this issue and raise a PR.

**Comment by yoyo-wu98** [comment]
> I think we can use `$(pwd)` before the folder name to complete the path, which will lead another thing that under windows, this should be replaced by `%cd%`. This will give the command an absolute path of the folder.

Thanks for reply, I will have a try.

**Comment by yoyo-wu98** [comment]
With PR #918 being merged, I will close this issue.
