### ISSUE TITLE
 process.env. GITHUB_ EVENT_ Path

### ISSUE THREAD

**Issue by 9luchai** [X-lab2017/open-digger#919]
Run pulll_ labe_ file_ test. ts, GitHub_ EVENT_ Path cannot get value，and I don't know how to get it.
The following is the output：
```
PS D:\IdeaWorkspace\open-digger> npm run pull-label-file-test
> open-digger@1.0.0 pull-label-file-test D:\IdeaWorkspace\open-digger
> tsc && node lib/ci/pull_label_file_test.js
Not in GitHub actions env or event file not found at path=undefined.
```

**Comment by frank-zsy** [comment]
The scripts under `src/ci` folder is not for local environment. It is used in GitHub actions for PR related functions.

The file `pull_label_file_test.ts` is used to test `.yml` file with GitHub ID config to make sure the ID is identical with the repo/org/actor name like [this](https://github.com/X-lab2017/open-digger/pull/904).

So the `GITHUB_EVENT_PATH` is injected by GitHub in actions that triggered by PR events. You can find all default actions environment variables documentation [here](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables).

**Comment by frank-zsy** [comment]
I will close this issue for now and if you have more questions about the scripts, please feel free to reopen this issue. @9luchai
