### ISSUE TITLE
How to import data to Clickhouse?

### ISSUE THREAD

**Issue by longranger2** [X-lab2017/open-digger#921]
Despite your revised documentation, I'm still not sure how to import data into Clickhouse, can you provide a dynamic diagram of the process? This will make it easier to understand
![屏幕快照 2022-07-23 下午3 49 34](https://user-images.githubusercontent.com/52858395/180596029-58a0f6e1-81ec-4051-a331-cb21322be255.png)

**Comment by frank-zsy** [comment]
@longranger2 Is there anything problem with the data process? If you follow the steps, then the data should be imported into the Clickhouse server automatically. If you want to know more about the process, the import work is done by [this script](https://github.com/X-lab2017/open-digger/blob/master/sample_data/build/initdb.sh).

**Comment by longranger2** [comment]
Yes, I'm having some problems importing data, but I don't know how to fix it
![屏幕快照 2022-07-23 下午4 45 49](https://user-images.githubusercontent.com/52858395/180597825-77f2c9c7-25d5-405b-a8cd-da3364ca150e.png)

**Comment by yoyo-wu98** [comment]
hi @longranger2 , it seems like you run the docker image before it is pulled.
So, I think you should first pull the docker image and then run the docker.
 Hope this would help.

**Comment by zhicheng-ning** [comment]
> Yes, I'm having some problems importing data, but I don't know how to fix it

Suppose your machine's platform is x86, as show below. 
Firstly, You should make sure you have pulled ClickHouse server image. You can use 
```shell
docker pull docker-hub.x-lab.info/opendigger/open-digger-clickhouse-base:v1
```
to get the clickhouse image,then you can use
```shell
docker run -d --name paddle_container -m 6G -p 8123:8123 -p 9000:9000 --ulimit nofile=262144:262144 \
> --volume=/your-data-path/:/data/ docker-hub.x-lab.info/opendigger/open-digger-clickhouse-base:v1
```
to instantiate a container image which name is paddle_container.After that, you can use 
```shell
docker ps
```
to check whether the container started successfully.

![image](https://user-images.githubusercontent.com/39022409/180603445-4e027e87-0cd2-4824-8359-75c9e15c3ac9.png)

**Comment by longranger2** [comment]
@zhicheng-ning Thank you very much! It works! But I also have another question: how can I know the data being imported correctly into the Clickhouse database? Also I find that the created container stays closed, even if I use `sudo docker start paddle_container`,It will close quickly.
![屏幕快照 2022-07-23 下午8 54 43](https://user-images.githubusercontent.com/52858395/180605849-617a0393-ff5e-490e-b837-7376166372df.png)

**Comment by yoyo-wu98** [comment]
> Clickhouse database? Also I find that the created container stays closed, even if I use `sudo docker start paddle_container`,It will close quickly.

hi @longranger2 can you show us your docker's log?
In your example the corresponding command should be
```shell
docker logs paddle_container
```
The log may tell us what's going on.

**Comment by zhicheng-ning** [comment]
> how can I know the data being imported correctly into the Clickhouse database?

Actually, You can use 
```shell
docker exec -it container_name /bin/bash
```
enter the container. If you can find `/docker-entrypoint-initdb.d/inited.lock` file is exist, it means that the database has been initialized and completed.

```bash
[root@standard-dev-centos ~]# docker ps
CONTAINER ID   IMAGE                                                             COMMAND            CREATED             STATUS         PORTS                                                                                            NAMES
6a9955063335   docker-hub.x-lab.info/opendigger/open-digger-clickhouse-base:v1   "/entrypoint.sh"   About an hour ago   Up 3 seconds   0.0.0.0:8123->8123/tcp, :::8123->8123/tcp, 0.0.0.0:9000->9000/tcp, :::9000->9000/tcp, 9009/tcp   paddle_container
[root@standard-dev-centos ~]# docker exec -it paddle_container /bin/bash
root@6a9955063335:/# ls
bin  boot  data  dev  docker-entrypoint-initdb.d  entrypoint.sh  etc  home  lib  lib32  lib64  libx32  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
root@6a9955063335:/# cd docker-entrypoint-initdb.d/
root@6a9955063335:/docker-entrypoint-initdb.d# ls
initdb.sh  inited.lock
root@6a9955063335:/docker-entrypoint-initdb.d# 
```

**Comment by longranger2** [comment]
@yoyo-wu98  It say "Data or table file not exists under /data folder".
![屏幕快照 2022-07-23 下午9 05 38](https://user-images.githubusercontent.com/52858395/180606275-4bb0389c-4810-4ade-8846-5a60af24693a.png)
But actually, I have put the table and data under the directory`/home/ubuntu/open-digger/data/paddle_hackathon_3/data`. And I use the command `docker run -d --name paddle_container -m 6G -p 8124:8124 -p 9001:9001 --ulimit nofile=262144:262144 --volume=/home/ubuntu/open-digger/data/paddle_hackathon_3/:/data/ docker-hub.x-lab.info/opendigger/open-digger-clickhouse-base:v1` to create the paddle_container
![屏幕快照 2022-07-23 下午9 18 47](https://user-images.githubusercontent.com/52858395/180606802-5db5c634-c641-4253-b470-5e1278fd8ed7.png)

**Comment by zhicheng-ning** [comment]
> I have put the table and data under the directory`/home/ubuntu/open-digger/data/paddle_hackathon_3/data`. And I use the below command to create the paddle_container.

The host directory for the container data volume should be `/home/ubuntu/open-digger/data/paddle_hackathon_3/data/` in your case.Try to use the following commands.
```shell
docker run -d --name paddle_container -m 6G -p 8124:8124 -p 9001:9001 --ulimit nofile=262144:262144 --volume=/home/ubuntu/open-digger/data/paddle_hackathon_3/data/:/data/ docker-hub.x-lab.info/opendigger/open-digger-clickhouse-base:v1
```

**Comment by longranger2** [comment]
My fault, my data files were nested so much that I didn't notice the data file path was wrong. Thank you so much for pointing out my mistake! Now the container can start normally. Thank you for your help! @zhicheng-ning @yoyo-wu98 

![屏幕快照 2022-07-23 下午9 44 18](https://user-images.githubusercontent.com/52858395/180607711-fb2dc787-3608-4af6-a919-79657a3d97f8.png)

**Comment by yoyo-wu98** [comment]
You are welcome. @longranger2 
We can continue to communicate here if you get some other error with importing the data.

**Comment by frank-zsy** [comment]
@longranger2 I will close this issue for now and if you have more questions about importing data, please feel free to reopen this issue or raise a new one.
