### ISSUE TITLE
How to analyze the timing of code merges?

### ISSUE THREAD

**Issue by longranger2** [X-lab2017/open-digger#930]
I'm trying to see how long it takes to analyze an open source organization 's code review, i.e. from the time the code changes are submitted to the time they are passed, but I can only find the `pull_merged_at` that when this pull request was merged, I can't find the attribute when this pull request was created. May be I should use the attribute `pull_review_comment_created_at`?[The Reference Links](https://github.com/X-lab2017/open-digger/blob/master/docs/assets/data_description.csv)

![屏幕快照 2022-07-31 下午9 09 54](https://user-images.githubusercontent.com/52858395/182028042-ab50ca99-faa5-459b-aa75-5454306dafe1.png)

**Comment by frank-zsy** [comment]
`pull_` related events and `issue_` related events share columns, so you can use `WHERE type='PullRequestEvent' AND action='opened'` to get the create time of pull requests.

**Comment by longranger2** [comment]
Thank you! And I would also like to ask if open-digger integrates some algorithms to analyze the data, such as sentiment analysis algorithms.

**Comment by frank-zsy** [comment]
Not yet, you may need to analysis by yourself with other tools. We will add more functions when Python kernel ready.

**Comment by longranger2** [comment]
So my understanding is that right now open-digger is still focused on analyzing statistical line data, right? And I am looking forward to the arrival of the Python kernel !

**Comment by frank-zsy** [comment]
Yes, right now statistical data can be retrieved by simple SQLs, but you can still use other lib like `tensorflow.js` to do the downstream works in Node.js kernel too.

**Comment by longranger2** [comment]
ok, Thank you ! I'll do some research first
