### ISSUE TITLE
Please add CloudWeGo to the open-leaderboard

### ISSUE THREAD

**Issue by GuangmingLuo** [X-lab2017/open-digger#940]
Please add CloudWeGo to the open-leaderboard, thanks ~

https://github.com/cloudwego
- https://github.com/cloudwego/kitex
- https://github.com/cloudwego/hertz
- https://github.com/cloudwego/netpoll

**Comment by frank-zsy** [comment]
Thanks, do you want add it as a part of ByteDance?

**Comment by GuangmingLuo** [comment]
It is part of ByteDance now, but also an independent community with its own brand.

**Comment by frank-zsy** [comment]
OK，I will add it as a independent project as well as a part of ByteDance too.

/self-assign

**Comment by frank-zsy** [comment]
@GuangmingLuo The labeled data has been merged in #943 and will take effect in next month in OpenLeaderboard.
