### ISSUE TITLE
Question about src/label_data_utils.ts

### ISSUE THREAD

**Issue by Best-Eminem** [X-lab2017/open-digger#941]
When I test my Python API, or when I use local notebook data rather than notebook mirror, some problems occurs in src/label_data_utils.ts  'parseItem' function:
![image](https://user-images.githubusercontent.com/66980876/183594223-e4ca591a-0212-4aee-ac36-41a773299801.png)
However,  the parameter `'map'` passed in the `parseItem` function, the key values in `map` includes `":communities\\xlab\\hypertrons"` but not includes `":communities\\xlab\\index\\hypertrons"`, which will cause an error and throw this error: `Exception: Can not find nest identifier :communities\xlab\index\hypertrons for :communities\xlab\index`

**Comment by Best-Eminem** [comment]
> I am not sure what do you mean? When you say test Python API, you mean you implement the whole underlying part in Python or you call function in Node.js from Python.
> 
> There should not be a label with identifier `:communites\xlab\index\hypertrons`, I don't know why the upper layer need this label? Can you give the whole calling chain of your test?

For example, if I use local notebook `handbook_zh.ipynb` rather than notebook mirror, the same error occured:
![image](https://user-images.githubusercontent.com/66980876/183600429-3cf168cc-3266-464a-9050-b81e791326d1.png)

**Comment by frank-zsy** [comment]
I assume this may involve something with Windows path resolution, I will check this.

**Comment by Best-Eminem** [comment]
> I assume this may involve something with Windows path resolution, I will check this.

Thanks!

**Comment by frank-zsy** [comment]
@Best-Eminem Sorry that I don't have Windows env to test the fix. Can you checkout the `fix/win-path` branch and test in your local env and feedback the result.

**Comment by Best-Eminem** [comment]
> @Best-Eminem Sorry that I don't have Windows env to test the fix. Can you checkout the `fix/win-path` branch and test in your local env and feedback the result.

Pre problem has fixed, but the other problem occurs, this maybe because the Windows path always use `\` but linux use `/`:
![image](https://user-images.githubusercontent.com/66980876/183626507-f6db8b0f-2036-46fd-9061-856d0e598cd7.png)

**Comment by frank-zsy** [comment]
Yes, I use `path.join` to construct the label, but `join` will use `path.sep` which is different in Windows and Linux to link the components.

**Comment by frank-zsy** [comment]
I update the code, I convert the identifier to linux favor path in the last step since the application layer will still use linux favor path as identifier now. Can you test the branch in your env?

**Comment by Best-Eminem** [comment]
> I update the code, I convert the identifier to linux favor path in the last step since the application layer will still use linux favor path as identifier now. Can you test the branch in your env?

It still has the problem:
![image](https://user-images.githubusercontent.com/66980876/183665264-4d1bc4d7-e9c4-47a6-97ce-081216aee400.png)

**Comment by frank-zsy** [comment]
Orz, I think I need a Windows env to test the code.

You can test it again and if there is still something wrong, can you debug in your env?

**Comment by Best-Eminem** [comment]
> Orz, I think I need a Windows env to test the code.
> 
> You can test it again and if there is still something wrong, can you debug in your env?

It works now:
![image](https://user-images.githubusercontent.com/66980876/183681597-ae95d6a9-2d56-4836-ba3b-089886f37fcd.png)

**Comment by frank-zsy** [comment]
Good, I will raise a PR to fix this. Thanks for the report.
