### ISSUE TITLE
Request for latest Clickhouse mirror

### ISSUE THREAD

**Issue by Best-Eminem** [X-lab2017/open-digger#946]
I was wondering if you could make an updated Clickhouse data mirror because I need it to test Python API, thanks. @frank-zsy

**Comment by frank-zsy** [comment]
I am not sure what do you mean by update data mirror. I think it is my fault to use charts with data from 2015 to 2022 which means notebook demo may need to access all the data.

The whole data set is too large for most developer to deploy locally, so maybe you can change the demos to only use data in `label_2015` data set. I think most metrics demo use this data set now.

**Comment by Best-Eminem** [comment]
> I am not sure what do you mean by update data mirror. I think it is my fault to use charts with data from 2015 to 2022 which means notebook demo may need to access all the data.
> 
> The whole data set is too large for most developer to deploy locally, so maybe you can change the demos to only use data in `label_2015` data set. I think most metrics demo use this data set now.

For example, the database `github_log` in docker container `github-archived-log` only have these tables below:
![image](https://user-images.githubusercontent.com/66980876/184561653-307f7160-55aa-4968-b78b-dd32a95a90ad.png)
But some querys use table like `github_log.events`, and I don't know the specific structure in `github_log.events`:
![7e43576983652c61759f197774e9c93](https://user-images.githubusercontent.com/66980876/184561800-0597046f-79e3-45c9-9dff-e644128e6939.png)

**Comment by Best-Eminem** [comment]
> I am not sure what do you mean by update data mirror. I think it is my fault to use charts with data from 2015 to 2022 which means notebook demo may need to access all the data.
> 
> The whole data set is too large for most developer to deploy locally, so maybe you can change the demos to only use data in `label_2015` data set. I think most metrics demo use this data set now.

Oh, I known what you mean now, thanks.

**Comment by frank-zsy** [comment]
Yes, the old data mirror uses separate table to store data and new data mirror uses single table `events`. I may need to update `github-archived-log` mirror. Thanks.
