### ISSUE TITLE
Pls help add labeled data into OpenDigger to help us for our community analysis [AntGroup]

### ISSUE THREAD

**Issue by antfin-oss** [X-lab2017/open-digger#956]
I want to add some labeled data into OpenDigger to help us for our community analysis.

Label: AntGroup

Type: Company

Orgs/Repos:

- secretflow
- ceresdb
- kusionstack
- traasstack
- eggjs
- Tongsuo-Project
- tugraph-db

**Comment by frank-zsy** [comment]
Thanks for the data, I will handle this.

**Comment by frank-zsy** [comment]
The data has been merged by #958 , we will update OpenLeaderboard now. Thanks for the data.
