### ISSUE TITLE
[Notebook] Add more Python kernel notebook

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger#961]
We need to transform all Node.js kernel notebook into Python kernel notebook.

We can add a `_py` suffix right now to Node.js kernel notebook.

**Comment by yanchaomei** [comment]
Hi, I want to do this task. I see that most notebooks are written with node.js. Is this task required to rewrite all notebooks written by node.js into notebooks written by python?

**Comment by xgdyp** [comment]
Hi, in fact, our python kernel has lagged behind js kernel a lot. So if you want to do some work on the python kernel, we can rewrite the basic framework and metrics in Python together.

**Comment by yanchaomei** [comment]
Ok, I'm willing to try to do this task

**Comment by birdflyi** [comment]
Hi, due to personal needs, I'd like to take another try~
