### ISSUE TITLE
[Docs] Add docs for Python kernel

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-digger#968]
We need to add docs for Python kernel and also push Python kernel docker image for developers to use.

**Comment by yoyo-wu98** [comment]
During writing the doc of Sample Data Usage for Python Kernel #998 , I find the doc a bit difficult to read through.
I think the structure of the open-digger is a bit complex and unfriendly to both node.js and python developers.
Is there any plan to tell the 2 versions(node.js and python) apart? Or some better idea? Or is this the current structure the best choice?

**Comment by frank-zsy** [comment]
Yes, actually I think a better idea is to separate the python and node.js kernel file into different folders like `src/node/` and `src/python`, so developers can understand better and focused on a certain kernel.

**Comment by xgdyp** [comment]
Hello @frank-zsy , I think we can store our python_kernel image into our remote DockerHub so we don't have to build image again. What do you think?

**Comment by xgdyp** [comment]
Would you like to test the new docs？@Zi1l

**Comment by frank-zsy** [comment]
> 

Yes, of course.

**Comment by lhbvvvvv** [comment]
> Would you like to test the new docs on #998？@Zi1l

Based on the new docs with python_kernel, open-digger can run successfully. Besides, I am sorry that I didn't see the message in time because of the chage of my ID.
