### ISSUE TITLE
OpenDigger Biweekly Meetings, 2022-2023 Autumn Term

### ISSUE THREAD

**Issue by xgdyp** [X-lab2017/open-digger#977]
## <p align="center">🍁 OpenDigger Biweekly Meetings, 2022-2023 Autumn Term</p >

- 🕣Time: 12:00~12:30, Wednesday of every two weeks
- 📞Tencent Meeting：755-1645-1474（[link](https://meeting.tencent.com/dm/2p9cBy32diTG)）

****

| Week📆| Date🕣| Host💂‍♂️ | Core Content🔑 | Discussion🔗  | Video🎥 |
| :------: | :-----: | :------: | :--------------: | :------------: | :-------: |
|  01   | 09-28 |  @xgdyp  |    Introduction to OpenDigger    | |    |
|  03   | 10-12 |  @xgdyp  |    python_kernel demo & desgin of questionnaire    | |    |
|  03   | 10-26 |   @xgdyp  |    tutorial on sample data    | |    |

**Comment by will-ww** [comment]
> This issue has not been replied for 24 hours, please pay attention to this issue: @gymgym1212 @xiaoya-yaya

Reaction can be counted as rely ? So if someone use the Emoji (such as thumbs) on the issue, the bot will not be trigged. :-)
