### ISSUE TITLE
[Proposal]Update a OpenDigger Dashboard

### ISSUE THREAD

**Issue by xgdyp** [X-lab2017/open-digger#986]

**Comment by xgdyp** [comment]
In DevLake Community, they use a data dashboard to support there weekly report. 
![image](https://user-images.githubusercontent.com/37795442/193542587-3af3f415-0ddc-44c8-a7bf-ab496e7129a6.png)
![image](https://user-images.githubusercontent.com/37795442/193542756-8f4d35bf-26b5-4609-b14f-cca9f6ec9774.png)

I think we can also make a dashboard, using data to support our weekly report.

**Comment by xgdyp** [comment]
@tyn1998 What do you think?

**Comment by tyn1998** [comment]
Hi @xgdyp, we are [developing a new feature](https://github.com/hypertrons/hypertrons-crx/pull/455) of Hypercrx to present some basic statistical data in GitHub UI, and some of the data are similar with those presented on the DevLake dashboard.

In Hypercrx, we are going to put our data in different places to make the extension more immersive. But the form of dashboard is also needed if people want to check the statistics in one place.

So I really appreciate the idea! Where are you going to put the dashboard? A new website? Or by Hypercrx?

**Comment by xgdyp** [comment]
> So I really appreciate the idea! Where are you going to put the dashboard? A new website? Or by Hypercrx?

A new website I think.

**Comment by tyn1998** [comment]
Perceptor tab of Hypercrx is originally designed to be a dashboard! But now there is only two graph chart in this tab.

Maybe we can move the two graph charts to other places and make them embeded, too. Then we can use the Perceptor tab as a dashboard to provide overview information for users.

**Comment by xgdyp** [comment]
We've done this.
![image](https://user-images.githubusercontent.com/37795442/198937909-6121d30e-7b33-4f28-988b-8bdd41d4d449.png)
