### ISSUE TITLE
We need a issue template to support sample data request

### ISSUE THREAD

**Issue by xgdyp** [X-lab2017/open-digger#995]
In OpenDigger, everyone who want to get their customized data can create a issue so we can help them export sample data from clickhouse server.But now, we don't have a issue endpoint to help user handle their data requirements. So, we should update our Issue template (add a data requirements template).
A template of  template like 
![image](https://user-images.githubusercontent.com/37795442/195246320-7202f276-46d6-46e7-ba25-099f49429feb.png)
![image](https://user-images.githubusercontent.com/37795442/195246344-9481c370-d700-443a-bd2a-a5499de6aa00.png)

**Comment by tyn1998** [comment]
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/32434520/195249034-7c4b50d2-78ac-4cdc-98f6-fefd9628ebae.png">

Hi @xgdyp, .yml templates might be good, since they make a sense of "filling the blanks" :)

**Comment by xgdyp** [comment]
> <img alt="image" width="1079" src="https://user-images.githubusercontent.com/32434520/195249034-7c4b50d2-78ac-4cdc-98f6-fefd9628ebae.png">
> 
> Hi @xgdyp, .yml templates might be good, since they make a sense of "filling the blanks" :)

You are right!
