### ISSUE TITLE
[CI] auto add issues comment reply status

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/open-digger#999]
Open-digger may also need to have this workflow according to what @xgdyp  said. 
The workflow reference to https://github.com/hypertrons/hypertrons-crx/issues/475

**Comment by xgdyp** [comment]
I have created the corresponding labels @zhicheng-ning 
<img width="594" alt="image" src="https://user-images.githubusercontent.com/37795442/195747640-3b9a18f8-e405-48f6-a75b-39147054be0e.png">

**Comment by zhicheng-ning** [comment]
ok. I will pull request soon.
